var annotated_dup =
[
    [ "orm", null, [
      [ "db", null, [
        [ "binding", null, [
          [ "BindingPayload", "structorm_1_1db_1_1binding_1_1BindingPayload.html", null ],
          [ "OptionalValue", "structorm_1_1db_1_1binding_1_1OptionalValue.html", null ],
          [ "OptionalValue&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1db_1_1binding_1_1OptionalValue_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "ConversionError", "classorm_1_1db_1_1binding_1_1ConversionError.html", null ],
          [ "PrimaryKeyLess", "structorm_1_1db_1_1binding_1_1PrimaryKeyLess.html", null ],
          [ "IsOptional", "structorm_1_1db_1_1binding_1_1IsOptional.html", null ],
          [ "IsOptional&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1db_1_1binding_1_1IsOptional_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "IsOptionalBoundField", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField.html", null ],
          [ "IsOptionalBoundField&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "ObjectFieldFromValues", "structorm_1_1db_1_1binding_1_1ObjectFieldFromValues.html", null ],
          [ "IsOptionalScalarField", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField.html", null ],
          [ "IsOptionalScalarField&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "ObjectFieldToValues", "structorm_1_1db_1_1binding_1_1ObjectFieldToValues.html", null ],
          [ "BindingInfo", "structorm_1_1db_1_1binding_1_1BindingInfo.html", null ],
          [ "CollectionPayload", "structorm_1_1db_1_1binding_1_1CollectionPayload.html", null ],
          [ "ProjectionPayload", "structorm_1_1db_1_1binding_1_1ProjectionPayload.html", null ],
          [ "ObjectFieldFromProjectionValues", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues.html", null ],
          [ "ObjectFieldFromProjectionValues&lt; ResultField &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ],
          [ "ObjectFieldFromProjectionValues&lt; std::optional&lt; ResultField &gt; &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01std_1_1optional_3_01ResultField_01_4_01_4.html", null ],
          [ "ObjectFieldFromProjectionValuesWithCast", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", null ]
        ] ],
        [ "commands", null, [
          [ "CreateTableCommand", "classorm_1_1db_1_1commands_1_1CreateTableCommand.html", null ],
          [ "DefaultCreateTableCommand", "classorm_1_1db_1_1commands_1_1DefaultCreateTableCommand.html", null ],
          [ "DefaultDeleteCommand", "classorm_1_1db_1_1commands_1_1DefaultDeleteCommand.html", null ],
          [ "DefaultDropTableCommand", "classorm_1_1db_1_1commands_1_1DefaultDropTableCommand.html", null ],
          [ "DefaultInsertCommand", "classorm_1_1db_1_1commands_1_1DefaultInsertCommand.html", null ],
          [ "DefaultSelectCommand", "classorm_1_1db_1_1commands_1_1DefaultSelectCommand.html", null ],
          [ "DefaultUpdateCommand", "classorm_1_1db_1_1commands_1_1DefaultUpdateCommand.html", null ],
          [ "DeleteCommand", "classorm_1_1db_1_1commands_1_1DeleteCommand.html", null ],
          [ "DropTableCommand", "classorm_1_1db_1_1commands_1_1DropTableCommand.html", null ],
          [ "InsertCommand", "classorm_1_1db_1_1commands_1_1InsertCommand.html", null ],
          [ "RenderContext", "structorm_1_1db_1_1commands_1_1RenderContext.html", null ],
          [ "SelectCommand", "classorm_1_1db_1_1commands_1_1SelectCommand.html", null ],
          [ "UpdateCommand", "classorm_1_1db_1_1commands_1_1UpdateCommand.html", null ],
          [ "WriteColumn", "structorm_1_1db_1_1commands_1_1WriteColumn.html", null ]
        ] ],
        [ "detail", null, [
          [ "SqlSource", "structorm_1_1db_1_1detail_1_1SqlSource.html", null ],
          [ "SqlNode", "structorm_1_1db_1_1detail_1_1SqlNode.html", null ],
          [ "SqlOrder", "structorm_1_1db_1_1detail_1_1SqlOrder.html", null ],
          [ "SqlProjection", "structorm_1_1db_1_1detail_1_1SqlProjection.html", null ],
          [ "SqlAssignment", "structorm_1_1db_1_1detail_1_1SqlAssignment.html", null ],
          [ "SqlBindingDescriptor", "structorm_1_1db_1_1detail_1_1SqlBindingDescriptor.html", null ],
          [ "SqlQueryView", "structorm_1_1db_1_1detail_1_1SqlQueryView.html", null ],
          [ "SqlProgram", "structorm_1_1db_1_1detail_1_1SqlProgram.html", null ],
          [ "StaticSqlPolicy", "structorm_1_1db_1_1detail_1_1StaticSqlPolicy.html", null ],
          [ "RuntimeSqlPolicy", "structorm_1_1db_1_1detail_1_1RuntimeSqlPolicy.html", null ],
          [ "SqlColumnInfo", "structorm_1_1db_1_1detail_1_1SqlColumnInfo.html", null ],
          [ "SqlRenderScope", "structorm_1_1db_1_1detail_1_1SqlRenderScope.html", null ]
        ] ],
        [ "SchemaCapabilities", "structorm_1_1db_1_1SchemaCapabilities.html", null ],
        [ "QueryCapabilities", "structorm_1_1db_1_1QueryCapabilities.html", null ],
        [ "MutationCapabilities", "structorm_1_1db_1_1MutationCapabilities.html", null ],
        [ "RelationCapabilities", "structorm_1_1db_1_1RelationCapabilities.html", null ],
        [ "BackendValueLimits", "structorm_1_1db_1_1BackendValueLimits.html", "structorm_1_1db_1_1BackendValueLimits" ],
        [ "BackendCapabilities", "structorm_1_1db_1_1BackendCapabilities.html", null ],
        [ "BackendRuntimeLimits", "structorm_1_1db_1_1BackendRuntimeLimits.html", null ],
        [ "BackendProvider", "classorm_1_1db_1_1BackendProvider.html", null ],
        [ "BoundValue", "structorm_1_1db_1_1BoundValue.html", null ],
        [ "StatementParameter", "structorm_1_1db_1_1StatementParameter.html", null ],
        [ "Statement", "structorm_1_1db_1_1Statement.html", null ],
        [ "StatementView", "structorm_1_1db_1_1StatementView.html", null ],
        [ "BackendRuntime", "classorm_1_1db_1_1BackendRuntime.html", null ],
        [ "CommandGenerator", "classorm_1_1db_1_1CommandGenerator.html", null ],
        [ "CommandGeneratorFactory", "classorm_1_1db_1_1CommandGeneratorFactory.html", null ],
        [ "PaginationSpec", "structorm_1_1db_1_1PaginationSpec.html", null ],
        [ "InsertIfAbsentSpec", "structorm_1_1db_1_1InsertIfAbsentSpec.html", null ],
        [ "SqlDialect", "classorm_1_1db_1_1SqlDialect.html", null ],
        [ "TypeTranslator", "classorm_1_1db_1_1TypeTranslator.html", null ]
      ] ],
      [ "detail", null, [
        [ "IsManyToManyDescriptor", "structorm_1_1detail_1_1IsManyToManyDescriptor.html", null ],
        [ "IsManyToManyDescriptor&lt; ManyToManyDescriptor&lt; Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames &gt; &gt;", "structorm_1_1detail_1_1IsManyToManyDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMfa910bcc35e07f6cd9a576dac2955950.html", null ],
        [ "IsOneToManyDescriptor", "structorm_1_1detail_1_1IsOneToManyDescriptor.html", null ],
        [ "IsOneToManyDescriptor&lt; OneToManyDescriptor&lt; Member, MappedByMember, MappedByName &gt; &gt;", "structorm_1_1detail_1_1IsOneToManyDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
        [ "IsRelationDescriptor", "structorm_1_1detail_1_1IsRelationDescriptor.html", null ],
        [ "IsRelationDescriptor&lt; ManyToManyDescriptor&lt; Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames &gt; &gt;", "structorm_1_1detail_1_1IsRelationDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMemdc34019d2abea938502bc7c526da741a.html", null ],
        [ "IsRelationDescriptor&lt; OneToManyDescriptor&lt; Member, MappedByMember, MappedByName &gt; &gt;", "structorm_1_1detail_1_1IsRelationDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
        [ "OptionalRelationCollectionTraits", "structorm_1_1detail_1_1OptionalRelationCollectionTraits.html", null ],
        [ "OptionalRelationCollectionTraits&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1detail_1_1OptionalRelationCollectionTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
        [ "ProjectionResultField", "structorm_1_1detail_1_1ProjectionResultField.html", null ],
        [ "RelationCollection", "classorm_1_1detail_1_1RelationCollection.html", null ],
        [ "RelationCollectionTraits", "structorm_1_1detail_1_1RelationCollectionTraits.html", null ],
        [ "RelationCollectionTraits&lt; ManyToMany&lt; T &gt; &gt;", "structorm_1_1detail_1_1RelationCollectionTraits_3_01ManyToMany_3_01T_01_4_01_4.html", null ],
        [ "RelationCollectionTraits&lt; OneToMany&lt; T &gt; &gt;", "structorm_1_1detail_1_1RelationCollectionTraits_3_01OneToMany_3_01T_01_4_01_4.html", null ],
        [ "RelationColumnNames", "structorm_1_1detail_1_1RelationColumnNames.html", null ],
        [ "RelationMemberPointerTraits", "structorm_1_1detail_1_1RelationMemberPointerTraits.html", null ],
        [ "RelationMemberPointerTraits&lt; Value Owner::* &gt;", "structorm_1_1detail_1_1RelationMemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ]
      ] ],
      [ "model", null, [
        [ "detail", null, [
          [ "StaticOptionalTraits", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits.html", null ],
          [ "StaticOptionalTraits&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "MemberPointerTraits", "structorm_1_1model_1_1detail_1_1MemberPointerTraits.html", null ],
          [ "MemberPointerTraits&lt; Value Owner::* &gt;", "structorm_1_1model_1_1detail_1_1MemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ],
          [ "StaticSchemaTraits", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits.html", null ],
          [ "StaticSchemaTraits&lt; Schema&lt; Models... &gt; &gt;", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits_3_01Schema_3_01Models_8_8_8_01_4_01_4.html", null ],
          [ "IsFixedString", "structorm_1_1model_1_1detail_1_1IsFixedString.html", null ],
          [ "IsFixedString&lt; reflection::FixedString&lt; Size &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsFixedString_3_01reflection_1_1FixedString_3_01Size_01_4_01_4.html", null ],
          [ "IsColumnNames", "structorm_1_1model_1_1detail_1_1IsColumnNames.html", null ],
          [ "IsColumnNames&lt; ColumnNames&lt; Definitions... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsColumnNames_3_01ColumnNames_3_01Definitions_8_8_8_01_4_01_4.html", null ],
          [ "IsPrimaryKey", "structorm_1_1model_1_1detail_1_1IsPrimaryKey.html", null ],
          [ "IsPrimaryKey&lt; PrimaryKey&lt; Members... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsPrimaryKey_3_01PrimaryKey_3_01Members_8_8_8_01_4_01_4.html", null ],
          [ "IsAutoIncrement", "structorm_1_1model_1_1detail_1_1IsAutoIncrement.html", null ],
          [ "IsAutoIncrement&lt; AutoIncrement&lt; Members... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsAutoIncrement_3_01AutoIncrement_3_01Members_8_8_8_01_4_01_4.html", null ],
          [ "IsRelations", "structorm_1_1model_1_1detail_1_1IsRelations.html", null ],
          [ "IsRelations&lt; std::tuple&lt; Descriptors... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsRelations_3_01std_1_1tuple_3_01Descriptors_8_8_8_01_4_01_4.html", null ],
          [ "RelationNameBuffer", "structorm_1_1model_1_1detail_1_1RelationNameBuffer.html", null ],
          [ "DefaultJunctionColumnStorage", "structorm_1_1model_1_1detail_1_1DefaultJunctionColumnStorage.html", null ],
          [ "JunctionStorage", "structorm_1_1model_1_1detail_1_1JunctionStorage.html", null ]
        ] ],
        [ "ColumnName", "structorm_1_1model_1_1ColumnName.html", null ],
        [ "ColumnNames", "structorm_1_1model_1_1ColumnNames.html", null ],
        [ "PrimaryKey", "structorm_1_1model_1_1PrimaryKey.html", null ],
        [ "AutoIncrement", "structorm_1_1model_1_1AutoIncrement.html", null ],
        [ "LogicalTypeTraits", "structorm_1_1model_1_1LogicalTypeTraits.html", null ],
        [ "LogicalTypeTraits&lt; bool &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01bool_01_4.html", null ],
        [ "LogicalTypeTraits&lt; char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01char_01_4.html", null ],
        [ "LogicalTypeTraits&lt; signed char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01signed_01char_01_4.html", null ],
        [ "LogicalTypeTraits&lt; unsigned char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01char_01_4.html", null ],
        [ "LogicalTypeTraits&lt; short &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01short_01_4.html", null ],
        [ "LogicalTypeTraits&lt; unsigned short &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01short_01_4.html", null ],
        [ "LogicalTypeTraits&lt; int &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01int_01_4.html", null ],
        [ "LogicalTypeTraits&lt; unsigned int &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01int_01_4.html", null ],
        [ "LogicalTypeTraits&lt; long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01_4.html", null ],
        [ "LogicalTypeTraits&lt; unsigned long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01_4.html", null ],
        [ "LogicalTypeTraits&lt; long long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01long_01_4.html", null ],
        [ "LogicalTypeTraits&lt; unsigned long long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01long_01_4.html", null ],
        [ "LogicalTypeTraits&lt; float &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01float_01_4.html", null ],
        [ "LogicalTypeTraits&lt; double &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01double_01_4.html", null ],
        [ "LogicalTypeTraits&lt; std::string &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01std_1_1string_01_4.html", null ],
        [ "TypeId", "structorm_1_1model_1_1TypeId.html", null ],
        [ "ColumnView", "structorm_1_1model_1_1ColumnView.html", "structorm_1_1model_1_1ColumnView" ],
        [ "JunctionView", "structorm_1_1model_1_1JunctionView.html", null ],
        [ "RelationView", "structorm_1_1model_1_1RelationView.html", null ],
        [ "ModelDataView", "structorm_1_1model_1_1ModelDataView.html", null ],
        [ "ModelView", "structorm_1_1model_1_1ModelView.html", null ],
        [ "SchemaView", "structorm_1_1model_1_1SchemaView.html", null ],
        [ "Schema", "structorm_1_1model_1_1Schema.html", null ],
        [ "StaticModel", "structorm_1_1model_1_1StaticModel.html", null ]
      ] ],
      [ "query", null, [
        [ "detail", null, [
          [ "compiled", null, [
            [ "TupleEligible", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible.html", null ],
            [ "TupleEligible&lt; std::tuple&lt; Items... &gt; &gt;", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible_3_01std_1_1tuple_3_01Items_8_8_8_01_4_01_4.html", null ],
            [ "CheckingPolicy", "structorm_1_1query_1_1detail_1_1compiled_1_1CheckingPolicy.html", null ],
            [ "FrozenProgram", "structorm_1_1query_1_1detail_1_1compiled_1_1FrozenProgram.html", null ],
            [ "CompiledStatement", "structorm_1_1query_1_1detail_1_1compiled_1_1CompiledStatement.html", null ]
          ] ],
          [ "AggregateComparisonExpression", "structorm_1_1query_1_1detail_1_1AggregateComparisonExpression.html", null ],
          [ "AggregateExpression", "structorm_1_1query_1_1detail_1_1AggregateExpression.html", null ],
          [ "AggregateLogicalExpression", "structorm_1_1query_1_1detail_1_1AggregateLogicalExpression.html", null ],
          [ "AggregateMeta", "structorm_1_1query_1_1detail_1_1AggregateMeta.html", null ],
          [ "AggregateNotExpression", "structorm_1_1query_1_1detail_1_1AggregateNotExpression.html", null ],
          [ "AggregatePredicate", "classorm_1_1query_1_1detail_1_1AggregatePredicate.html", null ],
          [ "AggregatePredicateNode", "structorm_1_1query_1_1detail_1_1AggregatePredicateNode.html", null ],
          [ "Assignment", "structorm_1_1query_1_1detail_1_1Assignment.html", null ],
          [ "BetweenExpression", "structorm_1_1query_1_1detail_1_1BetweenExpression.html", null ],
          [ "BetweenMeta", "structorm_1_1query_1_1detail_1_1BetweenMeta.html", null ],
          [ "CapturedText", "structorm_1_1query_1_1detail_1_1CapturedText.html", null ],
          [ "CollectionExpression", "structorm_1_1query_1_1detail_1_1CollectionExpression.html", null ],
          [ "CollectionMeta", "structorm_1_1query_1_1detail_1_1CollectionMeta.html", null ],
          [ "CollectionTraits", "structorm_1_1query_1_1detail_1_1CollectionTraits.html", null ],
          [ "Column", "classorm_1_1query_1_1detail_1_1Column.html", "classorm_1_1query_1_1detail_1_1Column" ],
          [ "ColumnTraits", "structorm_1_1query_1_1detail_1_1ColumnTraits.html", null ],
          [ "ColumnTraits&lt; Member &gt;", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Member_01_4.html", null ],
          [ "ColumnTraits&lt; Relation, Member &gt;", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Relation_00_01Member_01_4.html", null ],
          [ "ComparisonExpression", "structorm_1_1query_1_1detail_1_1ComparisonExpression.html", null ],
          [ "ComparisonMeta", "structorm_1_1query_1_1detail_1_1ComparisonMeta.html", null ],
          [ "ContainerTraits", "structorm_1_1query_1_1detail_1_1ContainerTraits.html", null ],
          [ "ContainerTraits&lt; std::array&lt; T, N &gt; &gt;", "structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
          [ "ContainerTraits&lt; std::initializer_list&lt; T &gt; &gt;", "structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1initializer__list_3_01T_01_4_01_4.html", null ],
          [ "ContainerTraits&lt; std::vector&lt; T, A &gt; &gt;", "structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1vector_3_01T_00_01A_01_4_01_4.html", null ],
          [ "ExpressionMeta", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", null ],
          [ "FixedValues", "structorm_1_1query_1_1detail_1_1FixedValues.html", null ],
          [ "IncludeTag", "structorm_1_1query_1_1detail_1_1IncludeTag.html", null ],
          [ "IsExpression", "structorm_1_1query_1_1detail_1_1IsExpression.html", null ],
          [ "IsExpression&lt; Expression&lt; K, M, C... &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsExpression_3_01Expression_3_01K_00_01M_00_01C_8_8_8_01_4_01_4.html", null ],
          [ "IsParameter", "structorm_1_1query_1_1detail_1_1IsParameter.html", null ],
          [ "IsParameter&lt; Parameter&lt; T, I &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsParameter_3_01Parameter_3_01T_00_01I_01_4_01_4.html", null ],
          [ "IsTypedAggregate", "structorm_1_1query_1_1detail_1_1IsTypedAggregate.html", null ],
          [ "IsTypedAggregate&lt; TypedAggregate&lt; M, V, N &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsTypedAggregate_3_01TypedAggregate_3_01M_00_01V_00_01N_01_4_01_4.html", null ],
          [ "IsTypedAggregatePredicate", "structorm_1_1query_1_1detail_1_1IsTypedAggregatePredicate.html", null ],
          [ "IsTypedAggregatePredicate&lt; TypedAggregatePredicate&lt; M &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsTypedAggregatePredicate_3_01TypedAggregatePredicate_3_01M_01_4_01_4.html", null ],
          [ "IsTypedColumn", "structorm_1_1query_1_1detail_1_1IsTypedColumn.html", null ],
          [ "IsTypedColumn&lt; TypedColumn&lt; Members... &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsTypedColumn_3_01TypedColumn_3_01Members_8_8_8_01_4_01_4.html", null ],
          [ "IsTypedOrderBy", "structorm_1_1query_1_1detail_1_1IsTypedOrderBy.html", null ],
          [ "IsTypedOrderBy&lt; TypedOrderBy&lt; M &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsTypedOrderBy_3_01TypedOrderBy_3_01M_01_4_01_4.html", null ],
          [ "IsTypedPredicate", "structorm_1_1query_1_1detail_1_1IsTypedPredicate.html", null ],
          [ "IsTypedPredicate&lt; TypedPredicate&lt; M, W, C &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsTypedPredicate_3_01TypedPredicate_3_01M_00_01W_00_01C_01_4_01_4.html", null ],
          [ "IsTypedProjection", "structorm_1_1query_1_1detail_1_1IsTypedProjection.html", null ],
          [ "IsTypedProjection&lt; TypedProjection&lt; M &gt; &gt;", "structorm_1_1query_1_1detail_1_1IsTypedProjection_3_01TypedProjection_3_01M_01_4_01_4.html", null ],
          [ "ListExpression", "structorm_1_1query_1_1detail_1_1ListExpression.html", null ],
          [ "ListMeta", "structorm_1_1query_1_1detail_1_1ListMeta.html", null ],
          [ "ListTraits", "structorm_1_1query_1_1detail_1_1ListTraits.html", null ],
          [ "ListTraits&lt; FixedValues&lt; V... &gt; &gt;", "structorm_1_1query_1_1detail_1_1ListTraits_3_01FixedValues_3_01V_8_8_8_01_4_01_4.html", null ],
          [ "ListTraits&lt; Parameter&lt; std::array&lt; V, N &gt;, I &gt; &gt;", "structorm_1_1query_1_1detail_1_1ListTraits_3_01Parameter_3_01std_1_1array_3_01V_00_01N_01_4_00_01I_01_4_01_4.html", null ],
          [ "LogicalExpression", "structorm_1_1query_1_1detail_1_1LogicalExpression.html", null ],
          [ "LogicalMeta", "structorm_1_1query_1_1detail_1_1LogicalMeta.html", null ],
          [ "NoClause", "structorm_1_1query_1_1detail_1_1NoClause.html", null ],
          [ "NotExpression", "structorm_1_1query_1_1detail_1_1NotExpression.html", null ],
          [ "NotMeta", "structorm_1_1query_1_1detail_1_1NotMeta.html", null ],
          [ "NullExpression", "structorm_1_1query_1_1detail_1_1NullExpression.html", null ],
          [ "NullMeta", "structorm_1_1query_1_1detail_1_1NullMeta.html", null ],
          [ "OrderBy", "structorm_1_1query_1_1detail_1_1OrderBy.html", null ],
          [ "OrderMeta", "structorm_1_1query_1_1detail_1_1OrderMeta.html", null ],
          [ "ParameterTypesTrait", "structorm_1_1query_1_1detail_1_1ParameterTypesTrait.html", null ],
          [ "ParameterTypesTrait&lt; std::tuple&lt; T... &gt;, void &gt;", "structorm_1_1query_1_1detail_1_1ParameterTypesTrait_3_01std_1_1tuple_3_01T_8_8_8_01_4_00_01void_01_4.html", null ],
          [ "ParameterTypesTrait&lt; T, std::void_t&lt; typename T::ParameterTypes &gt; &gt;", "structorm_1_1query_1_1detail_1_1ParameterTypesTrait_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1ParameterTypes_01_4_01_4.html", null ],
          [ "ParameterValue", "structorm_1_1query_1_1detail_1_1ParameterValue.html", null ],
          [ "ParameterValue&lt; Parameter&lt; T, I &gt; &gt;", "structorm_1_1query_1_1detail_1_1ParameterValue_3_01Parameter_3_01T_00_01I_01_4_01_4.html", null ],
          [ "PlanAccess", "structorm_1_1query_1_1detail_1_1PlanAccess.html", null ],
          [ "Predicate", "classorm_1_1query_1_1detail_1_1Predicate.html", "classorm_1_1query_1_1detail_1_1Predicate" ],
          [ "PredicateNode", "structorm_1_1query_1_1detail_1_1PredicateNode.html", null ],
          [ "Projection", "structorm_1_1query_1_1detail_1_1Projection.html", null ],
          [ "ProjectionMeta", "structorm_1_1query_1_1detail_1_1ProjectionMeta.html", null ],
          [ "RawExpression", "structorm_1_1query_1_1detail_1_1RawExpression.html", null ],
          [ "RuntimeProjectionMeta", "structorm_1_1query_1_1detail_1_1RuntimeProjectionMeta.html", null ],
          [ "SelectSpec", "structorm_1_1query_1_1detail_1_1SelectSpec.html", null ],
          [ "SlotIndices", "structorm_1_1query_1_1detail_1_1SlotIndices.html", null ],
          [ "SlotIndices&lt; std::tuple&lt; P... &gt; &gt;", "structorm_1_1query_1_1detail_1_1SlotIndices_3_01std_1_1tuple_3_01P_8_8_8_01_4_01_4.html", null ],
          [ "SlotTypesCompatible", "structorm_1_1query_1_1detail_1_1SlotTypesCompatible.html", null ],
          [ "SlotTypesCompatible&lt; P, std::tuple&lt; Slots... &gt; &gt;", "structorm_1_1query_1_1detail_1_1SlotTypesCompatible_3_01P_00_01std_1_1tuple_3_01Slots_8_8_8_01_4_01_4.html", null ],
          [ "TypedAccess", "structorm_1_1query_1_1detail_1_1TypedAccess.html", null ],
          [ "UpdateAssignment", "structorm_1_1query_1_1detail_1_1UpdateAssignment.html", null ],
          [ "UpdateSpec", "structorm_1_1query_1_1detail_1_1UpdateSpec.html", null ],
          [ "UpdateValue", "structorm_1_1query_1_1detail_1_1UpdateValue.html", null ]
        ] ],
        [ "Expression", "classorm_1_1query_1_1Expression.html", null ],
        [ "Parameter", "classorm_1_1query_1_1Parameter.html", null ],
        [ "QueryParameter", "structorm_1_1query_1_1QueryParameter.html", null ],
        [ "QueryValue", "classorm_1_1query_1_1QueryValue.html", null ],
        [ "StaticPlan", "classorm_1_1query_1_1StaticPlan.html", null ],
        [ "TypedAggregate", "classorm_1_1query_1_1TypedAggregate.html", null ],
        [ "TypedAggregatePredicate", "classorm_1_1query_1_1TypedAggregatePredicate.html", null ],
        [ "TypedColumn", "classorm_1_1query_1_1TypedColumn.html", null ],
        [ "TypedOrderBy", "classorm_1_1query_1_1TypedOrderBy.html", null ],
        [ "TypedPredicate", "classorm_1_1query_1_1TypedPredicate.html", null ],
        [ "TypedProjection", "classorm_1_1query_1_1TypedProjection.html", null ]
      ] ],
      [ "reflection", null, [
        [ "detail", null, [
          [ "Any", "structorm_1_1reflection_1_1detail_1_1Any.html", null ],
          [ "BindingTraits", "structorm_1_1reflection_1_1detail_1_1BindingTraits.html", null ],
          [ "InactiveStorage", "unionorm_1_1reflection_1_1detail_1_1InactiveStorage.html", null ],
          [ "NameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1NameSignatureSentinel.html", null ],
          [ "PointerWrapper", "structorm_1_1reflection_1_1detail_1_1PointerWrapper.html", null ],
          [ "ReflectionTraits", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits.html", null ],
          [ "ReflectionTraits&lt; T, false &gt;", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01false_01_4.html", null ],
          [ "ReflectionTraits&lt; T, true &gt;", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01true_01_4.html", null ],
          [ "TypeNameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1TypeNameSignatureSentinel.html", null ]
        ] ],
        [ "FixedString", "structorm_1_1reflection_1_1FixedString.html", null ],
        [ "FieldDescriptor", "structorm_1_1reflection_1_1FieldDescriptor.html", null ]
      ] ],
      [ "Database", "classorm_1_1Database.html", "classorm_1_1Database" ],
      [ "DatabaseCore", "classorm_1_1DatabaseCore.html", "classorm_1_1DatabaseCore" ],
      [ "DatabaseError", "classorm_1_1DatabaseError.html", null ],
      [ "ManyToMany", "classorm_1_1ManyToMany.html", null ],
      [ "ManyToManyDescriptor", "structorm_1_1ManyToManyDescriptor.html", null ],
      [ "OneToMany", "classorm_1_1OneToMany.html", null ],
      [ "OneToManyDescriptor", "structorm_1_1OneToManyDescriptor.html", null ],
      [ "ProjectionQuery", "classorm_1_1ProjectionQuery.html", null ],
      [ "Query", "classorm_1_1Query.html", "classorm_1_1Query" ],
      [ "Update", "classorm_1_1Update.html", null ]
    ] ],
    [ "soci", null, [
      [ "type_conversion&lt; BindingPayload&lt; T, SchemaType, JoinedValues &gt; &gt;", "structsoci_1_1type__conversion_3_01BindingPayload_3_01T_00_01SchemaType_00_01JoinedValues_01_4_01_4.html", null ],
      [ "type_conversion&lt; orm::db::binding::CollectionPayload&lt; Owner, Target, SchemaType, JoinedValues &gt; &gt;", "structsoci_1_1type__conversion_3_01orm_1_1db_1_1binding_1_1CollectionPayload_3_01Owner_00_01Targffa2c747085deef29bc443f637394051.html", null ],
      [ "type_conversion&lt; ProjectionPayload&lt; T &gt; &gt;", "structsoci_1_1type__conversion_3_01ProjectionPayload_3_01T_01_4_01_4.html", null ]
    ] ]
];