var annotated_dup =
[
    [ "orm", null, [
      [ "db", null, [
        [ "binding", null, [
          [ "BindingInfo", "structorm_1_1db_1_1binding_1_1BindingInfo.html", null ],
          [ "BindingPayload", "structorm_1_1db_1_1binding_1_1BindingPayload.html", null ],
          [ "CollectionPayload", "structorm_1_1db_1_1binding_1_1CollectionPayload.html", null ],
          [ "ConversionError", "classorm_1_1db_1_1binding_1_1ConversionError.html", null ],
          [ "IsOptional", "structorm_1_1db_1_1binding_1_1IsOptional.html", null ],
          [ "IsOptional< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptional_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "IsOptionalBoundField", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField.html", null ],
          [ "IsOptionalBoundField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "IsOptionalScalarField", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField.html", null ],
          [ "IsOptionalScalarField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "ObjectFieldFromProjectionValues", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues.html", null ],
          [ "ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ],
          [ "ObjectFieldFromProjectionValues< std::optional< ResultField > >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01std_1_1optional_3_01ResultField_01_4_01_4.html", null ],
          [ "ObjectFieldFromProjectionValuesWithCast", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", null ],
          [ "ObjectFieldFromValues", "structorm_1_1db_1_1binding_1_1ObjectFieldFromValues.html", null ],
          [ "ObjectFieldToValues", "structorm_1_1db_1_1binding_1_1ObjectFieldToValues.html", null ],
          [ "OptionalValue", "structorm_1_1db_1_1binding_1_1OptionalValue.html", null ],
          [ "OptionalValue< std::optional< T > >", "structorm_1_1db_1_1binding_1_1OptionalValue_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "PrimaryKeyLess", "structorm_1_1db_1_1binding_1_1PrimaryKeyLess.html", null ],
          [ "ProjectionPayload", "structorm_1_1db_1_1binding_1_1ProjectionPayload.html", null ]
        ] ],
        [ "commands", null, [
          [ "CreateTableCommand", "classorm_1_1db_1_1commands_1_1CreateTableCommand.html", null ],
          [ "DefaultCreateTableCommand", "classorm_1_1db_1_1commands_1_1DefaultCreateTableCommand.html", null ],
          [ "DefaultDeleteCommand", "classorm_1_1db_1_1commands_1_1DefaultDeleteCommand.html", null ],
          [ "DeleteCommand", "classorm_1_1db_1_1commands_1_1DeleteCommand.html", null ],
          [ "DropTableCommand", "classorm_1_1db_1_1commands_1_1DropTableCommand.html", null ],
          [ "InsertCommand", "classorm_1_1db_1_1commands_1_1InsertCommand.html", null ],
          [ "RenderContext", "structorm_1_1db_1_1commands_1_1RenderContext.html", null ],
          [ "SelectCommand", "classorm_1_1db_1_1commands_1_1SelectCommand.html", null ],
          [ "UpdateCommand", "classorm_1_1db_1_1commands_1_1UpdateCommand.html", null ],
          [ "WriteColumn", "structorm_1_1db_1_1commands_1_1WriteColumn.html", null ]
        ] ],
        [ "detail", null, [
          [ "RuntimeSqlPolicy", "structorm_1_1db_1_1detail_1_1RuntimeSqlPolicy.html", null ],
          [ "SqlAssignment", "structorm_1_1db_1_1detail_1_1SqlAssignment.html", null ],
          [ "SqlBindingDescriptor", "structorm_1_1db_1_1detail_1_1SqlBindingDescriptor.html", null ],
          [ "SqlColumnInfo", "structorm_1_1db_1_1detail_1_1SqlColumnInfo.html", null ],
          [ "SqlNode", "structorm_1_1db_1_1detail_1_1SqlNode.html", null ],
          [ "SqlOrder", "structorm_1_1db_1_1detail_1_1SqlOrder.html", null ],
          [ "SqlProgram", "structorm_1_1db_1_1detail_1_1SqlProgram.html", null ],
          [ "SqlProjection", "structorm_1_1db_1_1detail_1_1SqlProjection.html", null ],
          [ "SqlQueryView", "structorm_1_1db_1_1detail_1_1SqlQueryView.html", null ],
          [ "SqlRenderScope", "structorm_1_1db_1_1detail_1_1SqlRenderScope.html", null ],
          [ "SqlSource", "structorm_1_1db_1_1detail_1_1SqlSource.html", null ],
          [ "StaticSqlPolicy", "structorm_1_1db_1_1detail_1_1StaticSqlPolicy.html", null ]
        ] ],
        [ "BackendCapabilities", "structorm_1_1db_1_1BackendCapabilities.html", null ],
        [ "BackendProvider", "classorm_1_1db_1_1BackendProvider.html", null ],
        [ "BackendRuntime", "classorm_1_1db_1_1BackendRuntime.html", null ],
        [ "BackendRuntimeLimits", "structorm_1_1db_1_1BackendRuntimeLimits.html", null ],
        [ "BackendValueLimits", "structorm_1_1db_1_1BackendValueLimits.html", "structorm_1_1db_1_1BackendValueLimits" ],
        [ "BoundValue", "structorm_1_1db_1_1BoundValue.html", null ],
        [ "CommandGenerator", "classorm_1_1db_1_1CommandGenerator.html", null ],
        [ "MutationCapabilities", "structorm_1_1db_1_1MutationCapabilities.html", null ],
        [ "QueryCapabilities", "structorm_1_1db_1_1QueryCapabilities.html", null ],
        [ "RelationCapabilities", "structorm_1_1db_1_1RelationCapabilities.html", null ],
        [ "SchemaCapabilities", "structorm_1_1db_1_1SchemaCapabilities.html", null ],
        [ "Statement", "structorm_1_1db_1_1Statement.html", null ],
        [ "StatementParameter", "structorm_1_1db_1_1StatementParameter.html", null ],
        [ "StatementView", "structorm_1_1db_1_1StatementView.html", null ],
        [ "TypeTranslator", "classorm_1_1db_1_1TypeTranslator.html", null ]
      ] ],
      [ "detail", null, [
        [ "IsManyToManyDescriptor", "structorm_1_1detail_1_1IsManyToManyDescriptor.html", null ],
        [ "IsManyToManyDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsManyToManyDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMfa910bcc35e07f6cd9a576dac2955950.html", null ],
        [ "IsOneToManyDescriptor", "structorm_1_1detail_1_1IsOneToManyDescriptor.html", null ],
        [ "IsOneToManyDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsOneToManyDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
        [ "IsRelationDescriptor", "structorm_1_1detail_1_1IsRelationDescriptor.html", null ],
        [ "IsRelationDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMemdc34019d2abea938502bc7c526da741a.html", null ],
        [ "IsRelationDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
        [ "OptionalRelationCollectionTraits", "structorm_1_1detail_1_1OptionalRelationCollectionTraits.html", null ],
        [ "OptionalRelationCollectionTraits< std::optional< T > >", "structorm_1_1detail_1_1OptionalRelationCollectionTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
        [ "RelationCollectionTraits", "structorm_1_1detail_1_1RelationCollectionTraits.html", null ],
        [ "RelationCollectionTraits< ManyToMany< T > >", "structorm_1_1detail_1_1RelationCollectionTraits_3_01ManyToMany_3_01T_01_4_01_4.html", null ],
        [ "RelationCollectionTraits< OneToMany< T > >", "structorm_1_1detail_1_1RelationCollectionTraits_3_01OneToMany_3_01T_01_4_01_4.html", null ],
        [ "RelationColumnNames", "structorm_1_1detail_1_1RelationColumnNames.html", null ],
        [ "RelationMemberPointerTraits", "structorm_1_1detail_1_1RelationMemberPointerTraits.html", null ],
        [ "RelationMemberPointerTraits< Value Owner::* >", "structorm_1_1detail_1_1RelationMemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ]
      ] ],
      [ "model", null, [
        [ "detail", null, [
          [ "DefaultJunctionColumnStorage", "structorm_1_1model_1_1detail_1_1DefaultJunctionColumnStorage.html", null ],
          [ "IsAutoIncrement", "structorm_1_1model_1_1detail_1_1IsAutoIncrement.html", null ],
          [ "IsAutoIncrement< AutoIncrement< Members... > >", "structorm_1_1model_1_1detail_1_1IsAutoIncrement_3_01AutoIncrement_3_01Members_8_8_8_01_4_01_4.html", null ],
          [ "IsColumnNames", "structorm_1_1model_1_1detail_1_1IsColumnNames.html", null ],
          [ "IsColumnNames< ColumnNames< Definitions... > >", "structorm_1_1model_1_1detail_1_1IsColumnNames_3_01ColumnNames_3_01Definitions_8_8_8_01_4_01_4.html", null ],
          [ "IsFixedString", "structorm_1_1model_1_1detail_1_1IsFixedString.html", null ],
          [ "IsFixedString< reflection::FixedString< Size > >", "structorm_1_1model_1_1detail_1_1IsFixedString_3_01reflection_1_1FixedString_3_01Size_01_4_01_4.html", null ],
          [ "IsPrimaryKey", "structorm_1_1model_1_1detail_1_1IsPrimaryKey.html", null ],
          [ "IsPrimaryKey< PrimaryKey< Members... > >", "structorm_1_1model_1_1detail_1_1IsPrimaryKey_3_01PrimaryKey_3_01Members_8_8_8_01_4_01_4.html", null ],
          [ "IsRelations", "structorm_1_1model_1_1detail_1_1IsRelations.html", null ],
          [ "IsRelations< std::tuple< Descriptors... > >", "structorm_1_1model_1_1detail_1_1IsRelations_3_01std_1_1tuple_3_01Descriptors_8_8_8_01_4_01_4.html", null ],
          [ "JunctionStorage", "structorm_1_1model_1_1detail_1_1JunctionStorage.html", null ],
          [ "MemberPointerTraits", "structorm_1_1model_1_1detail_1_1MemberPointerTraits.html", null ],
          [ "MemberPointerTraits< Value Owner::* >", "structorm_1_1model_1_1detail_1_1MemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ],
          [ "RelationNameBuffer", "structorm_1_1model_1_1detail_1_1RelationNameBuffer.html", null ],
          [ "StaticOptionalTraits", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits.html", null ],
          [ "StaticOptionalTraits< std::optional< T > >", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
          [ "StaticSchemaTraits", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits.html", null ],
          [ "StaticSchemaTraits< Schema< Models... > >", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits_3_01Schema_3_01Models_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "AutoIncrement", "structorm_1_1model_1_1AutoIncrement.html", null ],
        [ "ColumnName", "structorm_1_1model_1_1ColumnName.html", null ],
        [ "ColumnNames", "structorm_1_1model_1_1ColumnNames.html", null ],
        [ "ColumnView", "structorm_1_1model_1_1ColumnView.html", null ],
        [ "JunctionView", "structorm_1_1model_1_1JunctionView.html", null ],
        [ "LogicalTypeTraits", "structorm_1_1model_1_1LogicalTypeTraits.html", null ],
        [ "LogicalTypeTraits< bool >", "structorm_1_1model_1_1LogicalTypeTraits_3_01bool_01_4.html", null ],
        [ "LogicalTypeTraits< char >", "structorm_1_1model_1_1LogicalTypeTraits_3_01char_01_4.html", null ],
        [ "LogicalTypeTraits< double >", "structorm_1_1model_1_1LogicalTypeTraits_3_01double_01_4.html", null ],
        [ "LogicalTypeTraits< float >", "structorm_1_1model_1_1LogicalTypeTraits_3_01float_01_4.html", null ],
        [ "LogicalTypeTraits< int >", "structorm_1_1model_1_1LogicalTypeTraits_3_01int_01_4.html", null ],
        [ "LogicalTypeTraits< long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01_4.html", null ],
        [ "LogicalTypeTraits< long long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01long_01_4.html", null ],
        [ "LogicalTypeTraits< short >", "structorm_1_1model_1_1LogicalTypeTraits_3_01short_01_4.html", null ],
        [ "LogicalTypeTraits< signed char >", "structorm_1_1model_1_1LogicalTypeTraits_3_01signed_01char_01_4.html", null ],
        [ "LogicalTypeTraits< std::string >", "structorm_1_1model_1_1LogicalTypeTraits_3_01std_1_1string_01_4.html", null ],
        [ "LogicalTypeTraits< unsigned char >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01char_01_4.html", null ],
        [ "LogicalTypeTraits< unsigned int >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01int_01_4.html", null ],
        [ "LogicalTypeTraits< unsigned long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01_4.html", null ],
        [ "LogicalTypeTraits< unsigned long long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01long_01_4.html", null ],
        [ "LogicalTypeTraits< unsigned short >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01short_01_4.html", null ],
        [ "ModelDataView", "structorm_1_1model_1_1ModelDataView.html", null ],
        [ "ModelView", "structorm_1_1model_1_1ModelView.html", null ],
        [ "PrimaryKey", "structorm_1_1model_1_1PrimaryKey.html", null ],
        [ "RelationView", "structorm_1_1model_1_1RelationView.html", null ],
        [ "Schema", "structorm_1_1model_1_1Schema.html", null ],
        [ "SchemaView", "structorm_1_1model_1_1SchemaView.html", null ],
        [ "StaticModel", "structorm_1_1model_1_1StaticModel.html", null ],
        [ "TypeId", "structorm_1_1model_1_1TypeId.html", null ]
      ] ],
      [ "query", null, [
        [ "detail", null, [
          [ "compiled", null, [
            [ "CheckingPolicy", "structorm_1_1query_1_1detail_1_1compiled_1_1CheckingPolicy.html", null ],
            [ "CompiledStatement", "structorm_1_1query_1_1detail_1_1compiled_1_1CompiledStatement.html", null ],
            [ "FrozenProgram", "structorm_1_1query_1_1detail_1_1compiled_1_1FrozenProgram.html", null ],
            [ "TupleEligible", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible.html", null ],
            [ "TupleEligible< std::tuple< Items... > >", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible_3_01std_1_1tuple_3_01Items_8_8_8_01_4_01_4.html", null ]
          ] ],
          [ "AggregateComparisonExpression", "structorm_1_1query_1_1detail_1_1AggregateComparisonExpression.html", null ],
          [ "AggregateExpression", "structorm_1_1query_1_1detail_1_1AggregateExpression.html", null ],
          [ "AggregateLogicalExpression", "structorm_1_1query_1_1detail_1_1AggregateLogicalExpression.html", null ],
          [ "AggregateNotExpression", "structorm_1_1query_1_1detail_1_1AggregateNotExpression.html", null ],
          [ "AggregatePredicate", "classorm_1_1query_1_1detail_1_1AggregatePredicate.html", null ],
          [ "AggregatePredicateNode", "structorm_1_1query_1_1detail_1_1AggregatePredicateNode.html", null ],
          [ "Assignment", "structorm_1_1query_1_1detail_1_1Assignment.html", null ],
          [ "BetweenExpression", "structorm_1_1query_1_1detail_1_1BetweenExpression.html", null ],
          [ "CollectionExpression", "structorm_1_1query_1_1detail_1_1CollectionExpression.html", null ],
          [ "CollectionTraits", "structorm_1_1query_1_1detail_1_1CollectionTraits.html", null ],
          [ "Column", "classorm_1_1query_1_1detail_1_1Column.html", "classorm_1_1query_1_1detail_1_1Column" ],
          [ "ColumnTraits", "structorm_1_1query_1_1detail_1_1ColumnTraits.html", null ],
          [ "ColumnTraits< Member >", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Member_01_4.html", null ],
          [ "ColumnTraits< Relation, Member >", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Relation_00_01Member_01_4.html", null ],
          [ "ComparisonExpression", "structorm_1_1query_1_1detail_1_1ComparisonExpression.html", null ],
          [ "IncludeTag", "structorm_1_1query_1_1detail_1_1IncludeTag.html", null ],
          [ "ListExpression", "structorm_1_1query_1_1detail_1_1ListExpression.html", null ],
          [ "LogicalExpression", "structorm_1_1query_1_1detail_1_1LogicalExpression.html", null ],
          [ "NoClause", "structorm_1_1query_1_1detail_1_1NoClause.html", null ],
          [ "NotExpression", "structorm_1_1query_1_1detail_1_1NotExpression.html", null ],
          [ "NullExpression", "structorm_1_1query_1_1detail_1_1NullExpression.html", null ],
          [ "OrderBy", "structorm_1_1query_1_1detail_1_1OrderBy.html", null ],
          [ "PlanAccess", "structorm_1_1query_1_1detail_1_1PlanAccess.html", null ],
          [ "Predicate", "classorm_1_1query_1_1detail_1_1Predicate.html", "classorm_1_1query_1_1detail_1_1Predicate" ],
          [ "PredicateNode", "structorm_1_1query_1_1detail_1_1PredicateNode.html", null ],
          [ "Projection", "structorm_1_1query_1_1detail_1_1Projection.html", null ],
          [ "RawExpression", "structorm_1_1query_1_1detail_1_1RawExpression.html", null ],
          [ "SelectSpec", "structorm_1_1query_1_1detail_1_1SelectSpec.html", null ],
          [ "UpdateAssignment", "structorm_1_1query_1_1detail_1_1UpdateAssignment.html", null ],
          [ "UpdateSpec", "structorm_1_1query_1_1detail_1_1UpdateSpec.html", null ],
          [ "UpdateValue", "structorm_1_1query_1_1detail_1_1UpdateValue.html", null ]
        ] ],
        [ "QueryParameter", "structorm_1_1query_1_1QueryParameter.html", null ],
        [ "QueryValue", "classorm_1_1query_1_1QueryValue.html", null ],
        [ "StaticPlan", "classorm_1_1query_1_1StaticPlan.html", null ],
        [ "TypedColumn", "classorm_1_1query_1_1TypedColumn.html", null ],
        [ "TypedOrderBy", "classorm_1_1query_1_1TypedOrderBy.html", null ],
        [ "TypedProjection", "classorm_1_1query_1_1TypedProjection.html", null ]
      ] ],
      [ "reflection", null, [
        [ "detail", null, [
          [ "Any", "structorm_1_1reflection_1_1detail_1_1Any.html", null ],
          [ "BindingTraits", "structorm_1_1reflection_1_1detail_1_1BindingTraits.html", null ],
          [ "InactiveStorage", "unionorm_1_1reflection_1_1detail_1_1InactiveStorage.html", null ],
          [ "NameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1NameSignatureSentinel.html", null ],
          [ "PointerWrapper", "structorm_1_1reflection_1_1detail_1_1PointerWrapper.html", null ],
          [ "ReflectionTraits", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits.html", null ],
          [ "ReflectionTraits< T, false >", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01false_01_4.html", null ],
          [ "ReflectionTraits< T, true >", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01true_01_4.html", null ],
          [ "TypeNameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1TypeNameSignatureSentinel.html", null ]
        ] ],
        [ "FieldDescriptor", "structorm_1_1reflection_1_1FieldDescriptor.html", null ],
        [ "FixedString", "structorm_1_1reflection_1_1FixedString.html", null ]
      ] ],
      [ "Database", "classorm_1_1Database.html", "classorm_1_1Database" ],
      [ "DatabaseError", "classorm_1_1DatabaseError.html", null ],
      [ "OrmContext", "classorm_1_1OrmContext.html", null ],
      [ "Query", "classorm_1_1Query.html", "classorm_1_1Query" ]
    ] ],
    [ "soci", null, [
      [ "type_conversion< BindingPayload< T, SchemaType, JoinedValues > >", "structsoci_1_1type__conversion_3_01BindingPayload_3_01T_00_01SchemaType_00_01JoinedValues_01_4_01_4.html", null ],
      [ "type_conversion< orm::db::binding::CollectionPayload< Owner, Target, SchemaType, JoinedValues > >", "structsoci_1_1type__conversion_3_01orm_1_1db_1_1binding_1_1CollectionPayload_3_01Owner_00_01Targffa2c747085deef29bc443f637394051.html", null ],
      [ "type_conversion< ProjectionPayload< T > >", "structsoci_1_1type__conversion_3_01ProjectionPayload_3_01T_01_4_01_4.html", null ]
    ] ]
];