comment: no # do not comment PR with the result

ignore:
  - "externals/**"
  - "tests/**"
  - "src/**/*Test.cpp"

coverage:
  range: 90..100 # project code is expected to remain fully covered

  status:
    project:
      default:
        target: 100%
        threshold: 0%

    # do not run coverage on patch nor changes
    patch: false
