var hierarchy =
[
    [ "orm::query::detail::AggregateComparisonExpression", "structorm_1_1query_1_1detail_1_1AggregateComparisonExpression.html", null ],
    [ "orm::query::detail::AggregateExpression", "structorm_1_1query_1_1detail_1_1AggregateExpression.html", null ],
    [ "orm::query::detail::AggregateLogicalExpression", "structorm_1_1query_1_1detail_1_1AggregateLogicalExpression.html", null ],
    [ "orm::query::detail::AggregateNotExpression", "structorm_1_1query_1_1detail_1_1AggregateNotExpression.html", null ],
    [ "orm::query::detail::AggregatePredicate", "classorm_1_1query_1_1detail_1_1AggregatePredicate.html", null ],
    [ "orm::query::detail::AggregatePredicateNode", "structorm_1_1query_1_1detail_1_1AggregatePredicateNode.html", null ],
    [ "orm::reflection::detail::Any", "structorm_1_1reflection_1_1detail_1_1Any.html", null ],
    [ "orm::query::detail::Assignment&lt; Column, ValueStorage &gt;", "structorm_1_1query_1_1detail_1_1Assignment.html", null ],
    [ "orm::model::AutoIncrement&lt; Members &gt;", "structorm_1_1model_1_1AutoIncrement.html", null ],
    [ "orm::db::BackendCapabilities", "structorm_1_1db_1_1BackendCapabilities.html", null ],
    [ "orm::db::BackendProvider", "classorm_1_1db_1_1BackendProvider.html", null ],
    [ "orm::db::BackendRuntime", "classorm_1_1db_1_1BackendRuntime.html", null ],
    [ "orm::db::BackendRuntimeLimits", "structorm_1_1db_1_1BackendRuntimeLimits.html", null ],
    [ "orm::db::BackendValueLimits", "structorm_1_1db_1_1BackendValueLimits.html", null ],
    [ "orm::query::detail::BetweenExpression", "structorm_1_1query_1_1detail_1_1BetweenExpression.html", null ],
    [ "orm::db::binding::BindingInfo", "structorm_1_1db_1_1binding_1_1BindingInfo.html", null ],
    [ "orm::db::binding::BindingPayload&lt; T, SchemaType, JoinedValues &gt;", "structorm_1_1db_1_1binding_1_1BindingPayload.html", null ],
    [ "orm::reflection::detail::BindingTraits&lt; TupleType, FieldsAreAddressable &gt;", "structorm_1_1reflection_1_1detail_1_1BindingTraits.html", null ],
    [ "std::bool_constant", null, [
      [ "orm::model::detail::IsRelations< std::tuple< Descriptors... > >", "structorm_1_1model_1_1detail_1_1IsRelations_3_01std_1_1tuple_3_01Descriptors_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::compiled::TupleEligible< std::tuple< Items... > >", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible_3_01std_1_1tuple_3_01Items_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "orm::db::BoundValue", "structorm_1_1db_1_1BoundValue.html", null ],
    [ "orm::query::detail::CapturedText&lt; N &gt;", "structorm_1_1query_1_1detail_1_1CapturedText.html", null ],
    [ "orm::query::detail::CollectionExpression", "structorm_1_1query_1_1detail_1_1CollectionExpression.html", null ],
    [ "orm::db::binding::CollectionPayload&lt; Owner, Target, SchemaType, JoinedValues &gt;", "structorm_1_1db_1_1binding_1_1CollectionPayload.html", null ],
    [ "orm::query::detail::CollectionTraits&lt; Member &gt;", "structorm_1_1query_1_1detail_1_1CollectionTraits.html", null ],
    [ "orm::query::detail::Column", "classorm_1_1query_1_1detail_1_1Column.html", null ],
    [ "orm::model::ColumnName&lt; Member, SqlName &gt;", "structorm_1_1model_1_1ColumnName.html", null ],
    [ "orm::model::ColumnNames&lt; Definitions &gt;", "structorm_1_1model_1_1ColumnNames.html", null ],
    [ "orm::query::detail::ColumnTraits&lt; Members &gt;", "structorm_1_1query_1_1detail_1_1ColumnTraits.html", null ],
    [ "orm::query::detail::ColumnTraits&lt; Member &gt;", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Member_01_4.html", null ],
    [ "orm::query::detail::ColumnTraits&lt; Relation, Member &gt;", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Relation_00_01Member_01_4.html", null ],
    [ "orm::model::ColumnView", "structorm_1_1model_1_1ColumnView.html", null ],
    [ "orm::db::CommandGenerator", "classorm_1_1db_1_1CommandGenerator.html", null ],
    [ "orm::db::CommandGeneratorFactory", "classorm_1_1db_1_1CommandGeneratorFactory.html", null ],
    [ "orm::query::detail::ComparisonExpression", "structorm_1_1query_1_1detail_1_1ComparisonExpression.html", null ],
    [ "orm::query::detail::compiled::CompiledStatement&lt; Frozen, Length &gt;", "structorm_1_1query_1_1detail_1_1compiled_1_1CompiledStatement.html", null ],
    [ "orm::query::detail::ContainerTraits&lt; T &gt;", "structorm_1_1query_1_1detail_1_1ContainerTraits.html", null ],
    [ "orm::query::detail::ContainerTraits&lt; std::array&lt; T, N &gt; &gt;", "structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html", null ],
    [ "orm::query::detail::ContainerTraits&lt; std::initializer_list&lt; T &gt; &gt;", "structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1initializer__list_3_01T_01_4_01_4.html", null ],
    [ "orm::query::detail::ContainerTraits&lt; std::vector&lt; T, A &gt; &gt;", "structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1vector_3_01T_00_01A_01_4_01_4.html", null ],
    [ "orm::db::commands::CreateTableCommand", "classorm_1_1db_1_1commands_1_1CreateTableCommand.html", [
      [ "orm::db::commands::DefaultCreateTableCommand", "classorm_1_1db_1_1commands_1_1DefaultCreateTableCommand.html", null ]
    ] ],
    [ "orm::DatabaseCore", "classorm_1_1DatabaseCore.html", [
      [ "orm::Database< SchemaType >", "classorm_1_1Database.html", null ]
    ] ],
    [ "orm::model::detail::DefaultJunctionColumnStorage&lt; Model, SchemaType &gt;", "structorm_1_1model_1_1detail_1_1DefaultJunctionColumnStorage.html", null ],
    [ "orm::db::commands::DeleteCommand", "classorm_1_1db_1_1commands_1_1DeleteCommand.html", [
      [ "orm::db::commands::DefaultDeleteCommand", "classorm_1_1db_1_1commands_1_1DefaultDeleteCommand.html", null ]
    ] ],
    [ "orm::db::commands::DropTableCommand", "classorm_1_1db_1_1commands_1_1DropTableCommand.html", [
      [ "orm::db::commands::DefaultDropTableCommand", "classorm_1_1db_1_1commands_1_1DefaultDropTableCommand.html", null ]
    ] ],
    [ "orm::query::detail::ExpressionMeta&lt; M, W, C &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", null ],
    [ "orm::query::detail::ExpressionMeta&lt; C::Model &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", [
      [ "orm::query::detail::OrderMeta< C, Direction >", "structorm_1_1query_1_1detail_1_1OrderMeta.html", null ]
    ] ],
    [ "orm::query::detail::ExpressionMeta&lt; CollectionTraits&lt; Member &gt;::Model, true, true &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", [
      [ "orm::query::detail::CollectionMeta< Member, Op, C >", "structorm_1_1query_1_1detail_1_1CollectionMeta.html", null ]
    ] ],
    [ "orm::query::detail::ExpressionMeta&lt; E::Model, E::writeSafe, E::containsCollection &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", [
      [ "orm::query::detail::NotMeta< E >", "structorm_1_1query_1_1detail_1_1NotMeta.html", null ]
    ] ],
    [ "orm::query::detail::ExpressionMeta&lt; L::Model, L::writeSafe &amp;&amp;R::writeSafe, L::containsCollection||R::containsCollection &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", [
      [ "orm::query::detail::LogicalMeta< L, R, Op >", "structorm_1_1query_1_1detail_1_1LogicalMeta.html", null ]
    ] ],
    [ "orm::query::detail::ExpressionMeta&lt; M, false &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", [
      [ "orm::query::detail::AggregateMeta< Function, C, M, V, N >", "structorm_1_1query_1_1detail_1_1AggregateMeta.html", null ]
    ] ],
    [ "orm::query::detail::ExpressionMeta&lt; S::Model &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", [
      [ "orm::query::detail::ProjectionMeta< S, Alias >", "structorm_1_1query_1_1detail_1_1ProjectionMeta.html", null ],
      [ "orm::query::detail::RuntimeProjectionMeta< S >", "structorm_1_1query_1_1detail_1_1RuntimeProjectionMeta.html", null ]
    ] ],
    [ "orm::query::detail::ExpressionMeta&lt; S::Model, S::writeSafe, S::containsCollection &gt;", "structorm_1_1query_1_1detail_1_1ExpressionMeta.html", [
      [ "orm::query::detail::BetweenMeta< S, Op >", "structorm_1_1query_1_1detail_1_1BetweenMeta.html", null ],
      [ "orm::query::detail::ComparisonMeta< S, Op >", "structorm_1_1query_1_1detail_1_1ComparisonMeta.html", null ],
      [ "orm::query::detail::ListMeta< S, Op, Stored >", "structorm_1_1query_1_1detail_1_1ListMeta.html", null ],
      [ "orm::query::detail::NullMeta< S, Op >", "structorm_1_1query_1_1detail_1_1NullMeta.html", null ]
    ] ],
    [ "std::false_type", null, [
      [ "orm::db::binding::IsOptional< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptional_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::db::binding::IsOptionalBoundField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::db::binding::IsOptionalScalarField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::detail::IsManyToManyDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsManyToManyDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMfa910bcc35e07f6cd9a576dac2955950.html", null ],
      [ "orm::detail::IsOneToManyDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsOneToManyDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
      [ "orm::detail::IsRelationDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMemdc34019d2abea938502bc7c526da741a.html", null ],
      [ "orm::detail::IsRelationDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
      [ "orm::model::detail::IsAutoIncrement< AutoIncrement< Members... > >", "structorm_1_1model_1_1detail_1_1IsAutoIncrement_3_01AutoIncrement_3_01Members_8_8_8_01_4_01_4.html", null ],
      [ "orm::model::detail::IsColumnNames< ColumnNames< Definitions... > >", "structorm_1_1model_1_1detail_1_1IsColumnNames_3_01ColumnNames_3_01Definitions_8_8_8_01_4_01_4.html", null ],
      [ "orm::model::detail::IsFixedString< reflection::FixedString< Size > >", "structorm_1_1model_1_1detail_1_1IsFixedString_3_01reflection_1_1FixedString_3_01Size_01_4_01_4.html", null ],
      [ "orm::model::detail::IsPrimaryKey< PrimaryKey< Members... > >", "structorm_1_1model_1_1detail_1_1IsPrimaryKey_3_01PrimaryKey_3_01Members_8_8_8_01_4_01_4.html", null ],
      [ "orm::model::detail::IsRelations< std::tuple< Descriptors... > >", "structorm_1_1model_1_1detail_1_1IsRelations_3_01std_1_1tuple_3_01Descriptors_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::IsExpression< Expression< K, M, C... > >", "structorm_1_1query_1_1detail_1_1IsExpression_3_01Expression_3_01K_00_01M_00_01C_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::IsParameter< Parameter< T, I > >", "structorm_1_1query_1_1detail_1_1IsParameter_3_01Parameter_3_01T_00_01I_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedAggregate< TypedAggregate< M, V, N > >", "structorm_1_1query_1_1detail_1_1IsTypedAggregate_3_01TypedAggregate_3_01M_00_01V_00_01N_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedAggregatePredicate< TypedAggregatePredicate< M > >", "structorm_1_1query_1_1detail_1_1IsTypedAggregatePredicate_3_01TypedAggregatePredicate_3_01M_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedColumn< TypedColumn< Members... > >", "structorm_1_1query_1_1detail_1_1IsTypedColumn_3_01TypedColumn_3_01Members_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedOrderBy< TypedOrderBy< M > >", "structorm_1_1query_1_1detail_1_1IsTypedOrderBy_3_01TypedOrderBy_3_01M_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedPredicate< TypedPredicate< M, W, C > >", "structorm_1_1query_1_1detail_1_1IsTypedPredicate_3_01TypedPredicate_3_01M_00_01W_00_01C_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedProjection< TypedProjection< M > >", "structorm_1_1query_1_1detail_1_1IsTypedProjection_3_01TypedProjection_3_01M_01_4_01_4.html", null ],
      [ "orm::db::binding::IsOptional< T >", "structorm_1_1db_1_1binding_1_1IsOptional.html", null ],
      [ "orm::db::binding::IsOptionalBoundField< T >", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField.html", null ],
      [ "orm::db::binding::IsOptionalScalarField< T >", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField.html", null ],
      [ "orm::detail::IsManyToManyDescriptor< T >", "structorm_1_1detail_1_1IsManyToManyDescriptor.html", null ],
      [ "orm::detail::IsOneToManyDescriptor< T >", "structorm_1_1detail_1_1IsOneToManyDescriptor.html", null ],
      [ "orm::detail::IsRelationDescriptor< T >", "structorm_1_1detail_1_1IsRelationDescriptor.html", null ],
      [ "orm::model::detail::IsAutoIncrement< typename >", "structorm_1_1model_1_1detail_1_1IsAutoIncrement.html", null ],
      [ "orm::model::detail::IsColumnNames< typename >", "structorm_1_1model_1_1detail_1_1IsColumnNames.html", null ],
      [ "orm::model::detail::IsFixedString< typename >", "structorm_1_1model_1_1detail_1_1IsFixedString.html", null ],
      [ "orm::model::detail::IsPrimaryKey< typename >", "structorm_1_1model_1_1detail_1_1IsPrimaryKey.html", null ],
      [ "orm::model::detail::IsRelations< typename >", "structorm_1_1model_1_1detail_1_1IsRelations.html", null ],
      [ "orm::query::detail::IsExpression< E >", "structorm_1_1query_1_1detail_1_1IsExpression.html", null ],
      [ "orm::query::detail::IsParameter< T >", "structorm_1_1query_1_1detail_1_1IsParameter.html", null ],
      [ "orm::query::detail::IsTypedAggregate< E >", "structorm_1_1query_1_1detail_1_1IsTypedAggregate.html", null ],
      [ "orm::query::detail::IsTypedAggregatePredicate< E >", "structorm_1_1query_1_1detail_1_1IsTypedAggregatePredicate.html", null ],
      [ "orm::query::detail::IsTypedColumn< E >", "structorm_1_1query_1_1detail_1_1IsTypedColumn.html", null ],
      [ "orm::query::detail::IsTypedOrderBy< E >", "structorm_1_1query_1_1detail_1_1IsTypedOrderBy.html", null ],
      [ "orm::query::detail::IsTypedPredicate< E >", "structorm_1_1query_1_1detail_1_1IsTypedPredicate.html", null ],
      [ "orm::query::detail::IsTypedProjection< E >", "structorm_1_1query_1_1detail_1_1IsTypedProjection.html", null ]
    ] ],
    [ "orm::reflection::FieldDescriptor", "structorm_1_1reflection_1_1FieldDescriptor.html", null ],
    [ "orm::reflection::FixedString&lt; N &gt;", "structorm_1_1reflection_1_1FixedString.html", null ],
    [ "orm::query::detail::FixedValues&lt; V &gt;", "structorm_1_1query_1_1detail_1_1FixedValues.html", null ],
    [ "orm::query::detail::compiled::FrozenProgram&lt; Nodes, Orders, Groups, Projections, Assignments, Includes, Bindings &gt;", "structorm_1_1query_1_1detail_1_1compiled_1_1FrozenProgram.html", null ],
    [ "orm::reflection::detail::InactiveStorage&lt; T &gt;", "unionorm_1_1reflection_1_1detail_1_1InactiveStorage.html", null ],
    [ "orm::query::detail::IncludeTag&lt; Member &gt;", "structorm_1_1query_1_1detail_1_1IncludeTag.html", null ],
    [ "orm::db::commands::InsertCommand", "classorm_1_1db_1_1commands_1_1InsertCommand.html", [
      [ "orm::db::commands::DefaultInsertCommand", "classorm_1_1db_1_1commands_1_1DefaultInsertCommand.html", null ]
    ] ],
    [ "orm::db::InsertIfAbsentSpec", "structorm_1_1db_1_1InsertIfAbsentSpec.html", null ],
    [ "orm::model::detail::JunctionStorage&lt; Descriptor, Owner, Target, SchemaType &gt;", "structorm_1_1model_1_1detail_1_1JunctionStorage.html", null ],
    [ "orm::model::JunctionView", "structorm_1_1model_1_1JunctionView.html", null ],
    [ "orm::query::detail::ListExpression", "structorm_1_1query_1_1detail_1_1ListExpression.html", null ],
    [ "orm::query::detail::ListTraits&lt; T &gt;", "structorm_1_1query_1_1detail_1_1ListTraits.html", null ],
    [ "orm::query::detail::ListTraits&lt; FixedValues&lt; V... &gt; &gt;", "structorm_1_1query_1_1detail_1_1ListTraits_3_01FixedValues_3_01V_8_8_8_01_4_01_4.html", null ],
    [ "orm::query::detail::ListTraits&lt; Parameter&lt; std::array&lt; V, N &gt;, I &gt; &gt;", "structorm_1_1query_1_1detail_1_1ListTraits_3_01Parameter_3_01std_1_1array_3_01V_00_01N_01_4_00_01I_01_4_01_4.html", null ],
    [ "orm::query::detail::LogicalExpression", "structorm_1_1query_1_1detail_1_1LogicalExpression.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; T &gt;", "structorm_1_1model_1_1LogicalTypeTraits.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; bool &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01bool_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01char_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; double &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01double_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; float &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01float_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; int &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01int_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; long long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; short &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01short_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; signed char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01signed_01char_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; std::string &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01std_1_1string_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; unsigned char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01char_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; unsigned int &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01int_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; unsigned long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; unsigned long long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits&lt; unsigned short &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01short_01_4.html", null ],
    [ "orm::ManyToManyDescriptor&lt; Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames &gt;", "structorm_1_1ManyToManyDescriptor.html", null ],
    [ "orm::model::detail::MemberPointerTraits&lt; T &gt;", "structorm_1_1model_1_1detail_1_1MemberPointerTraits.html", null ],
    [ "orm::model::detail::MemberPointerTraits&lt; Value Owner::* &gt;", "structorm_1_1model_1_1detail_1_1MemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ],
    [ "Meta", null, [
      [ "orm::query::Expression< Kind, Meta, Children >", "classorm_1_1query_1_1Expression.html", null ]
    ] ],
    [ "orm::model::ModelDataView", "structorm_1_1model_1_1ModelDataView.html", null ],
    [ "orm::model::ModelView", "structorm_1_1model_1_1ModelView.html", null ],
    [ "orm::db::MutationCapabilities", "structorm_1_1db_1_1MutationCapabilities.html", null ],
    [ "orm::reflection::detail::NameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1NameSignatureSentinel.html", null ],
    [ "orm::query::detail::NoClause", "structorm_1_1query_1_1detail_1_1NoClause.html", null ],
    [ "orm::query::detail::NotExpression", "structorm_1_1query_1_1detail_1_1NotExpression.html", null ],
    [ "orm::query::detail::NullExpression", "structorm_1_1query_1_1detail_1_1NullExpression.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValues&lt; ResultField &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValues&lt; std::optional&lt; ResultField &gt; &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01std_1_1optional_3_01ResultField_01_4_01_4.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast&lt; ResultField, SociType &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast&lt; ResultField, double &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast&lt; ResultField, int &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast&lt; ResultField, long long &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast&lt; ResultField, unsigned long long &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromValues&lt; ModelField &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldFromValues.html", null ],
    [ "orm::db::binding::ObjectFieldToValues&lt; ModelField &gt;", "structorm_1_1db_1_1binding_1_1ObjectFieldToValues.html", null ],
    [ "orm::OneToManyDescriptor&lt; Member, MappedByMember, MappedByName &gt;", "structorm_1_1OneToManyDescriptor.html", null ],
    [ "orm::detail::OptionalRelationCollectionTraits&lt; T &gt;", "structorm_1_1detail_1_1OptionalRelationCollectionTraits.html", null ],
    [ "orm::detail::OptionalRelationCollectionTraits&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1detail_1_1OptionalRelationCollectionTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
    [ "orm::db::binding::OptionalValue&lt; T &gt;", "structorm_1_1db_1_1binding_1_1OptionalValue.html", null ],
    [ "orm::db::binding::OptionalValue&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1db_1_1binding_1_1OptionalValue_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
    [ "orm::query::detail::OrderBy", "structorm_1_1query_1_1detail_1_1OrderBy.html", null ],
    [ "orm::db::PaginationSpec", "structorm_1_1db_1_1PaginationSpec.html", null ],
    [ "orm::query::Parameter&lt; T, Index &gt;", "classorm_1_1query_1_1Parameter.html", null ],
    [ "orm::query::detail::ParameterTypesTrait&lt; T, typename &gt;", "structorm_1_1query_1_1detail_1_1ParameterTypesTrait.html", null ],
    [ "orm::query::detail::ParameterTypesTrait&lt; std::tuple&lt; T... &gt;, void &gt;", "structorm_1_1query_1_1detail_1_1ParameterTypesTrait_3_01std_1_1tuple_3_01T_8_8_8_01_4_00_01void_01_4.html", null ],
    [ "orm::query::detail::ParameterTypesTrait&lt; T, std::void_t&lt; typename T::ParameterTypes &gt; &gt;", "structorm_1_1query_1_1detail_1_1ParameterTypesTrait_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1ParameterTypes_01_4_01_4.html", null ],
    [ "orm::query::detail::ParameterValue&lt; T &gt;", "structorm_1_1query_1_1detail_1_1ParameterValue.html", null ],
    [ "orm::query::detail::ParameterValue&lt; Parameter&lt; T, I &gt; &gt;", "structorm_1_1query_1_1detail_1_1ParameterValue_3_01Parameter_3_01T_00_01I_01_4_01_4.html", null ],
    [ "orm::query::detail::PlanAccess", "structorm_1_1query_1_1detail_1_1PlanAccess.html", null ],
    [ "orm::reflection::detail::PointerWrapper&lt; T &gt;", "structorm_1_1reflection_1_1detail_1_1PointerWrapper.html", null ],
    [ "orm::query::detail::Predicate", "classorm_1_1query_1_1detail_1_1Predicate.html", null ],
    [ "orm::query::detail::PredicateNode", "structorm_1_1query_1_1detail_1_1PredicateNode.html", null ],
    [ "orm::model::PrimaryKey&lt; Members &gt;", "structorm_1_1model_1_1PrimaryKey.html", null ],
    [ "orm::db::binding::PrimaryKeyLess", "structorm_1_1db_1_1binding_1_1PrimaryKeyLess.html", null ],
    [ "orm::query::detail::Projection", "structorm_1_1query_1_1detail_1_1Projection.html", null ],
    [ "orm::db::binding::ProjectionPayload&lt; T &gt;", "structorm_1_1db_1_1binding_1_1ProjectionPayload.html", null ],
    [ "orm::ProjectionQuery&lt; Source, Result &gt;", "classorm_1_1ProjectionQuery.html", null ],
    [ "orm::detail::ProjectionResultField", "structorm_1_1detail_1_1ProjectionResultField.html", null ],
    [ "orm::Query&lt; T &gt;", "classorm_1_1Query.html", null ],
    [ "orm::db::QueryCapabilities", "structorm_1_1db_1_1QueryCapabilities.html", null ],
    [ "orm::query::QueryParameter", "structorm_1_1query_1_1QueryParameter.html", null ],
    [ "orm::query::QueryValue", "classorm_1_1query_1_1QueryValue.html", null ],
    [ "orm::query::detail::RawExpression", "structorm_1_1query_1_1detail_1_1RawExpression.html", null ],
    [ "orm::reflection::detail::ReflectionTraits&lt; T, bool &gt;", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits.html", null ],
    [ "orm::reflection::detail::ReflectionTraits&lt; T, false &gt;", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01false_01_4.html", null ],
    [ "orm::reflection::detail::ReflectionTraits&lt; T, true &gt;", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01true_01_4.html", null ],
    [ "orm::db::RelationCapabilities", "structorm_1_1db_1_1RelationCapabilities.html", null ],
    [ "orm::detail::RelationCollection&lt; T &gt;", "classorm_1_1detail_1_1RelationCollection.html", [
      [ "orm::ManyToMany< T >", "classorm_1_1ManyToMany.html", null ],
      [ "orm::OneToMany< T >", "classorm_1_1OneToMany.html", null ]
    ] ],
    [ "orm::detail::RelationCollectionTraits&lt; T &gt;", "structorm_1_1detail_1_1RelationCollectionTraits.html", null ],
    [ "orm::detail::RelationCollectionTraits&lt; ManyToMany&lt; T &gt; &gt;", "structorm_1_1detail_1_1RelationCollectionTraits_3_01ManyToMany_3_01T_01_4_01_4.html", null ],
    [ "orm::detail::RelationCollectionTraits&lt; OneToMany&lt; T &gt; &gt;", "structorm_1_1detail_1_1RelationCollectionTraits_3_01OneToMany_3_01T_01_4_01_4.html", null ],
    [ "orm::detail::RelationColumnNames&lt; Names &gt;", "structorm_1_1detail_1_1RelationColumnNames.html", null ],
    [ "orm::detail::RelationMemberPointerTraits&lt; typename &gt;", "structorm_1_1detail_1_1RelationMemberPointerTraits.html", null ],
    [ "orm::detail::RelationMemberPointerTraits&lt; Value Owner::* &gt;", "structorm_1_1detail_1_1RelationMemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ],
    [ "orm::model::detail::RelationNameBuffer&lt; Capacity &gt;", "structorm_1_1model_1_1detail_1_1RelationNameBuffer.html", null ],
    [ "orm::model::RelationView", "structorm_1_1model_1_1RelationView.html", null ],
    [ "orm::db::commands::RenderContext", "structorm_1_1db_1_1commands_1_1RenderContext.html", null ],
    [ "std::runtime_error", null, [
      [ "orm::DatabaseError", "classorm_1_1DatabaseError.html", null ],
      [ "orm::db::binding::ConversionError", "classorm_1_1db_1_1binding_1_1ConversionError.html", null ]
    ] ],
    [ "orm::db::detail::RuntimeSqlPolicy", "structorm_1_1db_1_1detail_1_1RuntimeSqlPolicy.html", null ],
    [ "orm::model::Schema&lt; Models &gt;", "structorm_1_1model_1_1Schema.html", null ],
    [ "orm::db::SchemaCapabilities", "structorm_1_1db_1_1SchemaCapabilities.html", null ],
    [ "orm::model::SchemaView", "structorm_1_1model_1_1SchemaView.html", null ],
    [ "orm::db::commands::SelectCommand", "classorm_1_1db_1_1commands_1_1SelectCommand.html", [
      [ "orm::db::commands::DefaultSelectCommand", "classorm_1_1db_1_1commands_1_1DefaultSelectCommand.html", null ]
    ] ],
    [ "orm::query::detail::SelectSpec", "structorm_1_1query_1_1detail_1_1SelectSpec.html", null ],
    [ "orm::query::detail::SlotIndices&lt; Tuple &gt;", "structorm_1_1query_1_1detail_1_1SlotIndices.html", null ],
    [ "orm::query::detail::SlotIndices&lt; std::tuple&lt; P... &gt; &gt;", "structorm_1_1query_1_1detail_1_1SlotIndices_3_01std_1_1tuple_3_01P_8_8_8_01_4_01_4.html", null ],
    [ "orm::query::detail::SlotTypesCompatible&lt; P, Slots &gt;", "structorm_1_1query_1_1detail_1_1SlotTypesCompatible.html", null ],
    [ "orm::query::detail::SlotTypesCompatible&lt; P, std::tuple&lt; Slots... &gt; &gt;", "structorm_1_1query_1_1detail_1_1SlotTypesCompatible_3_01P_00_01std_1_1tuple_3_01Slots_8_8_8_01_4_01_4.html", null ],
    [ "orm::db::detail::SqlAssignment", "structorm_1_1db_1_1detail_1_1SqlAssignment.html", null ],
    [ "orm::db::detail::SqlBindingDescriptor", "structorm_1_1db_1_1detail_1_1SqlBindingDescriptor.html", null ],
    [ "orm::db::detail::SqlColumnInfo", "structorm_1_1db_1_1detail_1_1SqlColumnInfo.html", null ],
    [ "orm::db::SqlDialect", "classorm_1_1db_1_1SqlDialect.html", null ],
    [ "orm::db::detail::SqlNode", "structorm_1_1db_1_1detail_1_1SqlNode.html", null ],
    [ "orm::db::detail::SqlOrder", "structorm_1_1db_1_1detail_1_1SqlOrder.html", null ],
    [ "orm::db::detail::SqlProgram", "structorm_1_1db_1_1detail_1_1SqlProgram.html", null ],
    [ "orm::db::detail::SqlProjection", "structorm_1_1db_1_1detail_1_1SqlProjection.html", null ],
    [ "orm::db::detail::SqlQueryView", "structorm_1_1db_1_1detail_1_1SqlQueryView.html", null ],
    [ "orm::db::detail::SqlRenderScope", "structorm_1_1db_1_1detail_1_1SqlRenderScope.html", null ],
    [ "orm::db::detail::SqlSource", "structorm_1_1db_1_1detail_1_1SqlSource.html", null ],
    [ "orm::db::Statement", "structorm_1_1db_1_1Statement.html", null ],
    [ "orm::db::StatementParameter", "structorm_1_1db_1_1StatementParameter.html", null ],
    [ "orm::db::StatementView", "structorm_1_1db_1_1StatementView.html", null ],
    [ "orm::model::StaticModel&lt; T, SchemaType &gt;", "structorm_1_1model_1_1StaticModel.html", null ],
    [ "orm::model::detail::StaticOptionalTraits&lt; T &gt;", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits.html", null ],
    [ "orm::model::detail::StaticOptionalTraits&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
    [ "orm::query::StaticPlan&lt; Operation, Owner, ResultType, StateTuple, Distinct, Join &gt;", "classorm_1_1query_1_1StaticPlan.html", null ],
    [ "orm::model::detail::StaticSchemaTraits&lt; typename &gt;", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits.html", null ],
    [ "orm::model::detail::StaticSchemaTraits&lt; Schema&lt; Models... &gt; &gt;", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits_3_01Schema_3_01Models_8_8_8_01_4_01_4.html", null ],
    [ "orm::db::detail::StaticSqlPolicy&lt; Flavor &gt;", "structorm_1_1db_1_1detail_1_1StaticSqlPolicy.html", [
      [ "orm::query::detail::compiled::CheckingPolicy< Flavor >", "structorm_1_1query_1_1detail_1_1compiled_1_1CheckingPolicy.html", null ]
    ] ],
    [ "std::true_type", null, [
      [ "orm::db::binding::IsOptional< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptional_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::db::binding::IsOptionalBoundField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::db::binding::IsOptionalScalarField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::detail::IsManyToManyDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsManyToManyDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMfa910bcc35e07f6cd9a576dac2955950.html", null ],
      [ "orm::detail::IsOneToManyDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsOneToManyDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
      [ "orm::detail::IsRelationDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMemdc34019d2abea938502bc7c526da741a.html", null ],
      [ "orm::detail::IsRelationDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
      [ "orm::model::detail::IsAutoIncrement< AutoIncrement< Members... > >", "structorm_1_1model_1_1detail_1_1IsAutoIncrement_3_01AutoIncrement_3_01Members_8_8_8_01_4_01_4.html", null ],
      [ "orm::model::detail::IsColumnNames< ColumnNames< Definitions... > >", "structorm_1_1model_1_1detail_1_1IsColumnNames_3_01ColumnNames_3_01Definitions_8_8_8_01_4_01_4.html", null ],
      [ "orm::model::detail::IsFixedString< reflection::FixedString< Size > >", "structorm_1_1model_1_1detail_1_1IsFixedString_3_01reflection_1_1FixedString_3_01Size_01_4_01_4.html", null ],
      [ "orm::model::detail::IsPrimaryKey< PrimaryKey< Members... > >", "structorm_1_1model_1_1detail_1_1IsPrimaryKey_3_01PrimaryKey_3_01Members_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::IsExpression< Expression< K, M, C... > >", "structorm_1_1query_1_1detail_1_1IsExpression_3_01Expression_3_01K_00_01M_00_01C_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::IsParameter< Parameter< T, I > >", "structorm_1_1query_1_1detail_1_1IsParameter_3_01Parameter_3_01T_00_01I_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedAggregate< TypedAggregate< M, V, N > >", "structorm_1_1query_1_1detail_1_1IsTypedAggregate_3_01TypedAggregate_3_01M_00_01V_00_01N_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedAggregatePredicate< TypedAggregatePredicate< M > >", "structorm_1_1query_1_1detail_1_1IsTypedAggregatePredicate_3_01TypedAggregatePredicate_3_01M_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedColumn< TypedColumn< Members... > >", "structorm_1_1query_1_1detail_1_1IsTypedColumn_3_01TypedColumn_3_01Members_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedOrderBy< TypedOrderBy< M > >", "structorm_1_1query_1_1detail_1_1IsTypedOrderBy_3_01TypedOrderBy_3_01M_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedPredicate< TypedPredicate< M, W, C > >", "structorm_1_1query_1_1detail_1_1IsTypedPredicate_3_01TypedPredicate_3_01M_00_01W_00_01C_01_4_01_4.html", null ],
      [ "orm::query::detail::IsTypedProjection< TypedProjection< M > >", "structorm_1_1query_1_1detail_1_1IsTypedProjection_3_01TypedProjection_3_01M_01_4_01_4.html", null ]
    ] ],
    [ "orm::query::detail::compiled::TupleEligible&lt; Tuple &gt;", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible.html", null ],
    [ "soci::type_conversion&lt; BindingPayload&lt; T, SchemaType, JoinedValues &gt; &gt;", "structsoci_1_1type__conversion_3_01BindingPayload_3_01T_00_01SchemaType_00_01JoinedValues_01_4_01_4.html", null ],
    [ "soci::type_conversion&lt; orm::db::binding::CollectionPayload&lt; Owner, Target, SchemaType, JoinedValues &gt; &gt;", "structsoci_1_1type__conversion_3_01orm_1_1db_1_1binding_1_1CollectionPayload_3_01Owner_00_01Targffa2c747085deef29bc443f637394051.html", null ],
    [ "soci::type_conversion&lt; ProjectionPayload&lt; T &gt; &gt;", "structsoci_1_1type__conversion_3_01ProjectionPayload_3_01T_01_4_01_4.html", null ],
    [ "orm::query::detail::TypedAccess", "structorm_1_1query_1_1detail_1_1TypedAccess.html", null ],
    [ "orm::query::TypedAggregate&lt; Owner, ResultValue, Nullable &gt;", "classorm_1_1query_1_1TypedAggregate.html", null ],
    [ "orm::query::TypedAggregatePredicate&lt; Owner &gt;", "classorm_1_1query_1_1TypedAggregatePredicate.html", null ],
    [ "orm::query::TypedColumn&lt; Members &gt;", "classorm_1_1query_1_1TypedColumn.html", null ],
    [ "orm::query::TypedOrderBy&lt; Owner &gt;", "classorm_1_1query_1_1TypedOrderBy.html", null ],
    [ "orm::query::TypedPredicate&lt; Owner, WriteSafe, ContainsCollection &gt;", "classorm_1_1query_1_1TypedPredicate.html", null ],
    [ "orm::query::TypedProjection&lt; Owner &gt;", "classorm_1_1query_1_1TypedProjection.html", null ],
    [ "orm::model::TypeId", "structorm_1_1model_1_1TypeId.html", null ],
    [ "orm::reflection::detail::TypeNameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1TypeNameSignatureSentinel.html", null ],
    [ "orm::db::TypeTranslator", "classorm_1_1db_1_1TypeTranslator.html", null ],
    [ "orm::Update&lt; T &gt;", "classorm_1_1Update.html", null ],
    [ "orm::query::detail::UpdateAssignment", "structorm_1_1query_1_1detail_1_1UpdateAssignment.html", null ],
    [ "orm::db::commands::UpdateCommand", "classorm_1_1db_1_1commands_1_1UpdateCommand.html", [
      [ "orm::db::commands::DefaultUpdateCommand", "classorm_1_1db_1_1commands_1_1DefaultUpdateCommand.html", null ]
    ] ],
    [ "orm::query::detail::UpdateSpec", "structorm_1_1query_1_1detail_1_1UpdateSpec.html", null ],
    [ "orm::query::detail::UpdateValue", "structorm_1_1query_1_1detail_1_1UpdateValue.html", null ],
    [ "orm::db::commands::WriteColumn", "structorm_1_1db_1_1commands_1_1WriteColumn.html", null ]
];