var hierarchy =
[
    [ "orm::query::detail::AggregateComparisonExpression", "structorm_1_1query_1_1detail_1_1AggregateComparisonExpression.html", null ],
    [ "orm::query::detail::AggregateExpression", "structorm_1_1query_1_1detail_1_1AggregateExpression.html", null ],
    [ "orm::query::detail::AggregateLogicalExpression", "structorm_1_1query_1_1detail_1_1AggregateLogicalExpression.html", null ],
    [ "orm::query::detail::AggregateNotExpression", "structorm_1_1query_1_1detail_1_1AggregateNotExpression.html", null ],
    [ "orm::query::detail::AggregatePredicate", "classorm_1_1query_1_1detail_1_1AggregatePredicate.html", null ],
    [ "orm::query::detail::AggregatePredicateNode", "structorm_1_1query_1_1detail_1_1AggregatePredicateNode.html", null ],
    [ "orm::reflection::detail::Any", "structorm_1_1reflection_1_1detail_1_1Any.html", null ],
    [ "orm::query::detail::Assignment< Column, ValueStorage >", "structorm_1_1query_1_1detail_1_1Assignment.html", null ],
    [ "orm::model::AutoIncrement< Members >", "structorm_1_1model_1_1AutoIncrement.html", null ],
    [ "orm::db::BackendCapabilities", "structorm_1_1db_1_1BackendCapabilities.html", null ],
    [ "orm::db::BackendProvider", "classorm_1_1db_1_1BackendProvider.html", null ],
    [ "orm::db::BackendRuntime", "classorm_1_1db_1_1BackendRuntime.html", null ],
    [ "orm::db::BackendRuntimeLimits", "structorm_1_1db_1_1BackendRuntimeLimits.html", null ],
    [ "orm::db::BackendValueLimits", "structorm_1_1db_1_1BackendValueLimits.html", null ],
    [ "orm::query::detail::BetweenExpression", "structorm_1_1query_1_1detail_1_1BetweenExpression.html", null ],
    [ "orm::db::binding::BindingInfo", "structorm_1_1db_1_1binding_1_1BindingInfo.html", null ],
    [ "orm::db::binding::BindingPayload< T, SchemaType, JoinedValues >", "structorm_1_1db_1_1binding_1_1BindingPayload.html", null ],
    [ "orm::reflection::detail::BindingTraits< TupleType, FieldsAreAddressable >", "structorm_1_1reflection_1_1detail_1_1BindingTraits.html", null ],
    [ "std::bool_constant", null, [
      [ "orm::model::detail::IsRelations< std::tuple< Descriptors... > >", "structorm_1_1model_1_1detail_1_1IsRelations_3_01std_1_1tuple_3_01Descriptors_8_8_8_01_4_01_4.html", null ],
      [ "orm::query::detail::compiled::TupleEligible< std::tuple< Items... > >", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible_3_01std_1_1tuple_3_01Items_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "orm::db::BoundValue", "structorm_1_1db_1_1BoundValue.html", null ],
    [ "orm::query::detail::CollectionExpression", "structorm_1_1query_1_1detail_1_1CollectionExpression.html", null ],
    [ "orm::db::binding::CollectionPayload< Owner, Target, SchemaType, JoinedValues >", "structorm_1_1db_1_1binding_1_1CollectionPayload.html", null ],
    [ "orm::query::detail::CollectionTraits< Member >", "structorm_1_1query_1_1detail_1_1CollectionTraits.html", null ],
    [ "orm::query::detail::Column", "classorm_1_1query_1_1detail_1_1Column.html", null ],
    [ "orm::model::ColumnName< Member, SqlName >", "structorm_1_1model_1_1ColumnName.html", null ],
    [ "orm::model::ColumnNames< Definitions >", "structorm_1_1model_1_1ColumnNames.html", null ],
    [ "orm::query::detail::ColumnTraits< Members >", "structorm_1_1query_1_1detail_1_1ColumnTraits.html", null ],
    [ "orm::query::detail::ColumnTraits< Member >", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Member_01_4.html", null ],
    [ "orm::query::detail::ColumnTraits< Relation, Member >", "structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Relation_00_01Member_01_4.html", null ],
    [ "orm::model::ColumnView", "structorm_1_1model_1_1ColumnView.html", null ],
    [ "orm::db::CommandGenerator", "classorm_1_1db_1_1CommandGenerator.html", null ],
    [ "orm::query::detail::ComparisonExpression", "structorm_1_1query_1_1detail_1_1ComparisonExpression.html", null ],
    [ "orm::query::detail::compiled::CompiledStatement< Frozen, Length >", "structorm_1_1query_1_1detail_1_1compiled_1_1CompiledStatement.html", null ],
    [ "orm::db::commands::CreateTableCommand", "classorm_1_1db_1_1commands_1_1CreateTableCommand.html", [
      [ "orm::db::commands::DefaultCreateTableCommand", "classorm_1_1db_1_1commands_1_1DefaultCreateTableCommand.html", null ]
    ] ],
    [ "orm::Database", "classorm_1_1Database.html", null ],
    [ "orm::model::detail::DefaultJunctionColumnStorage< Model, SchemaType >", "structorm_1_1model_1_1detail_1_1DefaultJunctionColumnStorage.html", null ],
    [ "orm::db::commands::DeleteCommand", "classorm_1_1db_1_1commands_1_1DeleteCommand.html", [
      [ "orm::db::commands::DefaultDeleteCommand", "classorm_1_1db_1_1commands_1_1DefaultDeleteCommand.html", null ]
    ] ],
    [ "orm::db::commands::DropTableCommand", "classorm_1_1db_1_1commands_1_1DropTableCommand.html", null ],
    [ "std::false_type", null, [
      [ "orm::db::binding::IsOptional< T >", "structorm_1_1db_1_1binding_1_1IsOptional.html", null ],
      [ "orm::db::binding::IsOptionalBoundField< T >", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField.html", null ],
      [ "orm::db::binding::IsOptionalScalarField< T >", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField.html", null ],
      [ "orm::detail::IsManyToManyDescriptor< T >", "structorm_1_1detail_1_1IsManyToManyDescriptor.html", null ],
      [ "orm::detail::IsOneToManyDescriptor< T >", "structorm_1_1detail_1_1IsOneToManyDescriptor.html", null ],
      [ "orm::detail::IsRelationDescriptor< T >", "structorm_1_1detail_1_1IsRelationDescriptor.html", null ],
      [ "orm::model::detail::IsAutoIncrement< typename >", "structorm_1_1model_1_1detail_1_1IsAutoIncrement.html", null ],
      [ "orm::model::detail::IsColumnNames< typename >", "structorm_1_1model_1_1detail_1_1IsColumnNames.html", null ],
      [ "orm::model::detail::IsFixedString< typename >", "structorm_1_1model_1_1detail_1_1IsFixedString.html", null ],
      [ "orm::model::detail::IsPrimaryKey< typename >", "structorm_1_1model_1_1detail_1_1IsPrimaryKey.html", null ],
      [ "orm::model::detail::IsRelations< typename >", "structorm_1_1model_1_1detail_1_1IsRelations.html", null ]
    ] ],
    [ "orm::reflection::FieldDescriptor", "structorm_1_1reflection_1_1FieldDescriptor.html", null ],
    [ "orm::reflection::FixedString< N >", "structorm_1_1reflection_1_1FixedString.html", null ],
    [ "orm::query::detail::compiled::FrozenProgram< Nodes, Orders, Groups, Projections, Assignments, Includes, Bindings >", "structorm_1_1query_1_1detail_1_1compiled_1_1FrozenProgram.html", null ],
    [ "orm::reflection::detail::InactiveStorage< T >", "unionorm_1_1reflection_1_1detail_1_1InactiveStorage.html", null ],
    [ "orm::query::detail::IncludeTag< Member >", "structorm_1_1query_1_1detail_1_1IncludeTag.html", null ],
    [ "orm::db::commands::InsertCommand", "classorm_1_1db_1_1commands_1_1InsertCommand.html", null ],
    [ "orm::model::detail::JunctionStorage< Descriptor, Owner, Target, SchemaType >", "structorm_1_1model_1_1detail_1_1JunctionStorage.html", null ],
    [ "orm::model::JunctionView", "structorm_1_1model_1_1JunctionView.html", null ],
    [ "orm::query::detail::ListExpression", "structorm_1_1query_1_1detail_1_1ListExpression.html", null ],
    [ "orm::query::detail::LogicalExpression", "structorm_1_1query_1_1detail_1_1LogicalExpression.html", null ],
    [ "orm::model::LogicalTypeTraits< T >", "structorm_1_1model_1_1LogicalTypeTraits.html", null ],
    [ "orm::model::LogicalTypeTraits< bool >", "structorm_1_1model_1_1LogicalTypeTraits_3_01bool_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< char >", "structorm_1_1model_1_1LogicalTypeTraits_3_01char_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< double >", "structorm_1_1model_1_1LogicalTypeTraits_3_01double_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< float >", "structorm_1_1model_1_1LogicalTypeTraits_3_01float_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< int >", "structorm_1_1model_1_1LogicalTypeTraits_3_01int_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< long long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< short >", "structorm_1_1model_1_1LogicalTypeTraits_3_01short_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< signed char >", "structorm_1_1model_1_1LogicalTypeTraits_3_01signed_01char_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< std::string >", "structorm_1_1model_1_1LogicalTypeTraits_3_01std_1_1string_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< unsigned char >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01char_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< unsigned int >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01int_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< unsigned long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< unsigned long long >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01long_01_4.html", null ],
    [ "orm::model::LogicalTypeTraits< unsigned short >", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01short_01_4.html", null ],
    [ "orm::model::detail::MemberPointerTraits< T >", "structorm_1_1model_1_1detail_1_1MemberPointerTraits.html", null ],
    [ "orm::model::detail::MemberPointerTraits< Value Owner::* >", "structorm_1_1model_1_1detail_1_1MemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ],
    [ "orm::model::ModelDataView", "structorm_1_1model_1_1ModelDataView.html", null ],
    [ "orm::model::ModelView", "structorm_1_1model_1_1ModelView.html", null ],
    [ "orm::db::MutationCapabilities", "structorm_1_1db_1_1MutationCapabilities.html", null ],
    [ "orm::reflection::detail::NameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1NameSignatureSentinel.html", null ],
    [ "orm::query::detail::NoClause", "structorm_1_1query_1_1detail_1_1NoClause.html", null ],
    [ "orm::query::detail::NotExpression", "structorm_1_1query_1_1detail_1_1NotExpression.html", null ],
    [ "orm::query::detail::NullExpression", "structorm_1_1query_1_1detail_1_1NullExpression.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValues< std::optional< ResultField > >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01std_1_1optional_3_01ResultField_01_4_01_4.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast< ResultField, SociType >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", null ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast< ResultField, double >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast< ResultField, int >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast< ResultField, long long >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromProjectionValuesWithCast< ResultField, unsigned long long >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html", [
      [ "orm::db::binding::ObjectFieldFromProjectionValues< ResultField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html", null ]
    ] ],
    [ "orm::db::binding::ObjectFieldFromValues< ModelField >", "structorm_1_1db_1_1binding_1_1ObjectFieldFromValues.html", null ],
    [ "orm::db::binding::ObjectFieldToValues< ModelField >", "structorm_1_1db_1_1binding_1_1ObjectFieldToValues.html", null ],
    [ "orm::detail::OptionalRelationCollectionTraits< T >", "structorm_1_1detail_1_1OptionalRelationCollectionTraits.html", null ],
    [ "orm::detail::OptionalRelationCollectionTraits< std::optional< T > >", "structorm_1_1detail_1_1OptionalRelationCollectionTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
    [ "orm::db::binding::OptionalValue< T >", "structorm_1_1db_1_1binding_1_1OptionalValue.html", null ],
    [ "orm::db::binding::OptionalValue< std::optional< T > >", "structorm_1_1db_1_1binding_1_1OptionalValue_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
    [ "orm::query::detail::OrderBy", "structorm_1_1query_1_1detail_1_1OrderBy.html", null ],
    [ "orm::OrmContext< SchemaType >", "classorm_1_1OrmContext.html", null ],
    [ "orm::query::detail::PlanAccess", "structorm_1_1query_1_1detail_1_1PlanAccess.html", null ],
    [ "orm::reflection::detail::PointerWrapper< T >", "structorm_1_1reflection_1_1detail_1_1PointerWrapper.html", null ],
    [ "orm::query::detail::Predicate", "classorm_1_1query_1_1detail_1_1Predicate.html", null ],
    [ "orm::query::detail::PredicateNode", "structorm_1_1query_1_1detail_1_1PredicateNode.html", null ],
    [ "orm::model::PrimaryKey< Members >", "structorm_1_1model_1_1PrimaryKey.html", null ],
    [ "orm::db::binding::PrimaryKeyLess", "structorm_1_1db_1_1binding_1_1PrimaryKeyLess.html", null ],
    [ "orm::query::detail::Projection", "structorm_1_1query_1_1detail_1_1Projection.html", null ],
    [ "orm::db::binding::ProjectionPayload< T >", "structorm_1_1db_1_1binding_1_1ProjectionPayload.html", null ],
    [ "orm::Query< T >", "classorm_1_1Query.html", null ],
    [ "orm::db::QueryCapabilities", "structorm_1_1db_1_1QueryCapabilities.html", null ],
    [ "orm::query::QueryParameter", "structorm_1_1query_1_1QueryParameter.html", null ],
    [ "orm::query::QueryValue", "classorm_1_1query_1_1QueryValue.html", null ],
    [ "orm::query::detail::RawExpression", "structorm_1_1query_1_1detail_1_1RawExpression.html", null ],
    [ "orm::reflection::detail::ReflectionTraits< T, bool >", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits.html", null ],
    [ "orm::reflection::detail::ReflectionTraits< T, false >", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01false_01_4.html", null ],
    [ "orm::reflection::detail::ReflectionTraits< T, true >", "structorm_1_1reflection_1_1detail_1_1ReflectionTraits_3_01T_00_01true_01_4.html", null ],
    [ "orm::db::RelationCapabilities", "structorm_1_1db_1_1RelationCapabilities.html", null ],
    [ "orm::detail::RelationCollectionTraits< T >", "structorm_1_1detail_1_1RelationCollectionTraits.html", null ],
    [ "orm::detail::RelationCollectionTraits< ManyToMany< T > >", "structorm_1_1detail_1_1RelationCollectionTraits_3_01ManyToMany_3_01T_01_4_01_4.html", null ],
    [ "orm::detail::RelationCollectionTraits< OneToMany< T > >", "structorm_1_1detail_1_1RelationCollectionTraits_3_01OneToMany_3_01T_01_4_01_4.html", null ],
    [ "orm::detail::RelationColumnNames< Names >", "structorm_1_1detail_1_1RelationColumnNames.html", null ],
    [ "orm::detail::RelationMemberPointerTraits< typename >", "structorm_1_1detail_1_1RelationMemberPointerTraits.html", null ],
    [ "orm::detail::RelationMemberPointerTraits< Value Owner::* >", "structorm_1_1detail_1_1RelationMemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ],
    [ "orm::model::detail::RelationNameBuffer< Capacity >", "structorm_1_1model_1_1detail_1_1RelationNameBuffer.html", null ],
    [ "orm::model::RelationView", "structorm_1_1model_1_1RelationView.html", null ],
    [ "orm::db::commands::RenderContext", "structorm_1_1db_1_1commands_1_1RenderContext.html", null ],
    [ "std::runtime_error", null, [
      [ "orm::DatabaseError", "classorm_1_1DatabaseError.html", null ],
      [ "orm::db::binding::ConversionError", "classorm_1_1db_1_1binding_1_1ConversionError.html", null ]
    ] ],
    [ "orm::db::detail::RuntimeSqlPolicy", "structorm_1_1db_1_1detail_1_1RuntimeSqlPolicy.html", null ],
    [ "orm::model::Schema< Models >", "structorm_1_1model_1_1Schema.html", null ],
    [ "orm::db::SchemaCapabilities", "structorm_1_1db_1_1SchemaCapabilities.html", null ],
    [ "orm::model::SchemaView", "structorm_1_1model_1_1SchemaView.html", null ],
    [ "orm::db::commands::SelectCommand", "classorm_1_1db_1_1commands_1_1SelectCommand.html", null ],
    [ "orm::query::detail::SelectSpec", "structorm_1_1query_1_1detail_1_1SelectSpec.html", null ],
    [ "orm::db::detail::SqlAssignment", "structorm_1_1db_1_1detail_1_1SqlAssignment.html", null ],
    [ "orm::db::detail::SqlBindingDescriptor", "structorm_1_1db_1_1detail_1_1SqlBindingDescriptor.html", null ],
    [ "orm::db::detail::SqlColumnInfo", "structorm_1_1db_1_1detail_1_1SqlColumnInfo.html", null ],
    [ "orm::db::detail::SqlNode", "structorm_1_1db_1_1detail_1_1SqlNode.html", null ],
    [ "orm::db::detail::SqlOrder", "structorm_1_1db_1_1detail_1_1SqlOrder.html", null ],
    [ "orm::db::detail::SqlProgram", "structorm_1_1db_1_1detail_1_1SqlProgram.html", null ],
    [ "orm::db::detail::SqlProjection", "structorm_1_1db_1_1detail_1_1SqlProjection.html", null ],
    [ "orm::db::detail::SqlQueryView", "structorm_1_1db_1_1detail_1_1SqlQueryView.html", null ],
    [ "orm::db::detail::SqlRenderScope", "structorm_1_1db_1_1detail_1_1SqlRenderScope.html", null ],
    [ "orm::db::detail::SqlSource", "structorm_1_1db_1_1detail_1_1SqlSource.html", null ],
    [ "orm::db::Statement", "structorm_1_1db_1_1Statement.html", null ],
    [ "orm::db::StatementParameter", "structorm_1_1db_1_1StatementParameter.html", null ],
    [ "orm::db::StatementView", "structorm_1_1db_1_1StatementView.html", null ],
    [ "orm::model::StaticModel< T, SchemaType >", "structorm_1_1model_1_1StaticModel.html", null ],
    [ "orm::model::detail::StaticOptionalTraits< T >", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits.html", null ],
    [ "orm::model::detail::StaticOptionalTraits< std::optional< T > >", "structorm_1_1model_1_1detail_1_1StaticOptionalTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
    [ "orm::query::StaticPlan< Operation, Owner, ResultType, StateTuple, Distinct, Join >", "classorm_1_1query_1_1StaticPlan.html", null ],
    [ "orm::model::detail::StaticSchemaTraits< typename >", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits.html", null ],
    [ "orm::model::detail::StaticSchemaTraits< Schema< Models... > >", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits_3_01Schema_3_01Models_8_8_8_01_4_01_4.html", null ],
    [ "orm::db::detail::StaticSqlPolicy< Flavor >", "structorm_1_1db_1_1detail_1_1StaticSqlPolicy.html", [
      [ "orm::query::detail::compiled::CheckingPolicy< Flavor >", "structorm_1_1query_1_1detail_1_1compiled_1_1CheckingPolicy.html", null ]
    ] ],
    [ "std::true_type", null, [
      [ "orm::db::binding::IsOptional< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptional_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::db::binding::IsOptionalBoundField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalBoundField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::db::binding::IsOptionalScalarField< std::optional< T > >", "structorm_1_1db_1_1binding_1_1IsOptionalScalarField_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
      [ "orm::detail::IsManyToManyDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsManyToManyDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMfa910bcc35e07f6cd9a576dac2955950.html", null ],
      [ "orm::detail::IsOneToManyDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsOneToManyDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
      [ "orm::detail::IsRelationDescriptor< ManyToManyDescriptor< Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMemdc34019d2abea938502bc7c526da741a.html", null ],
      [ "orm::detail::IsRelationDescriptor< OneToManyDescriptor< Member, MappedByMember, MappedByName > >", "structorm_1_1detail_1_1IsRelationDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
      [ "orm::model::detail::IsAutoIncrement< AutoIncrement< Members... > >", "structorm_1_1model_1_1detail_1_1IsAutoIncrement_3_01AutoIncrement_3_01Members_8_8_8_01_4_01_4.html", null ],
      [ "orm::model::detail::IsColumnNames< ColumnNames< Definitions... > >", "structorm_1_1model_1_1detail_1_1IsColumnNames_3_01ColumnNames_3_01Definitions_8_8_8_01_4_01_4.html", null ],
      [ "orm::model::detail::IsFixedString< reflection::FixedString< Size > >", "structorm_1_1model_1_1detail_1_1IsFixedString_3_01reflection_1_1FixedString_3_01Size_01_4_01_4.html", null ],
      [ "orm::model::detail::IsPrimaryKey< PrimaryKey< Members... > >", "structorm_1_1model_1_1detail_1_1IsPrimaryKey_3_01PrimaryKey_3_01Members_8_8_8_01_4_01_4.html", null ]
    ] ],
    [ "orm::query::detail::compiled::TupleEligible< Tuple >", "structorm_1_1query_1_1detail_1_1compiled_1_1TupleEligible.html", null ],
    [ "soci::type_conversion< BindingPayload< T, SchemaType, JoinedValues > >", "structsoci_1_1type__conversion_3_01BindingPayload_3_01T_00_01SchemaType_00_01JoinedValues_01_4_01_4.html", null ],
    [ "soci::type_conversion< orm::db::binding::CollectionPayload< Owner, Target, SchemaType, JoinedValues > >", "structsoci_1_1type__conversion_3_01orm_1_1db_1_1binding_1_1CollectionPayload_3_01Owner_00_01Targffa2c747085deef29bc443f637394051.html", null ],
    [ "soci::type_conversion< ProjectionPayload< T > >", "structsoci_1_1type__conversion_3_01ProjectionPayload_3_01T_01_4_01_4.html", null ],
    [ "orm::query::TypedColumn< Members >", "classorm_1_1query_1_1TypedColumn.html", null ],
    [ "orm::query::TypedOrderBy< Owner >", "classorm_1_1query_1_1TypedOrderBy.html", null ],
    [ "orm::query::TypedProjection< Owner >", "classorm_1_1query_1_1TypedProjection.html", null ],
    [ "orm::model::TypeId", "structorm_1_1model_1_1TypeId.html", null ],
    [ "orm::reflection::detail::TypeNameSignatureSentinel", "structorm_1_1reflection_1_1detail_1_1TypeNameSignatureSentinel.html", null ],
    [ "orm::db::TypeTranslator", "classorm_1_1db_1_1TypeTranslator.html", null ],
    [ "orm::query::detail::UpdateAssignment", "structorm_1_1query_1_1detail_1_1UpdateAssignment.html", null ],
    [ "orm::db::commands::UpdateCommand", "classorm_1_1db_1_1commands_1_1UpdateCommand.html", null ],
    [ "orm::query::detail::UpdateSpec", "structorm_1_1query_1_1detail_1_1UpdateSpec.html", null ],
    [ "orm::query::detail::UpdateValue", "structorm_1_1query_1_1detail_1_1UpdateValue.html", null ],
    [ "orm::db::commands::WriteColumn", "structorm_1_1db_1_1commands_1_1WriteColumn.html", null ]
];