var module__orm =
[
    [ "DatabaseError", "classorm_1_1DatabaseError.html", null ],
    [ "Database", "classorm_1_1Database.html", "classorm_1_1Database" ],
    [ "RelationCollection", "classorm_1_1detail_1_1RelationCollection.html", null ],
    [ "OneToMany", "classorm_1_1OneToMany.html", null ],
    [ "ManyToMany", "classorm_1_1ManyToMany.html", null ],
    [ "RelationCollectionTraits", "structorm_1_1detail_1_1RelationCollectionTraits.html", null ],
    [ "RelationCollectionTraits&lt; OneToMany&lt; T &gt; &gt;", "structorm_1_1detail_1_1RelationCollectionTraits_3_01OneToMany_3_01T_01_4_01_4.html", null ],
    [ "RelationCollectionTraits&lt; ManyToMany&lt; T &gt; &gt;", "structorm_1_1detail_1_1RelationCollectionTraits_3_01ManyToMany_3_01T_01_4_01_4.html", null ],
    [ "OptionalRelationCollectionTraits", "structorm_1_1detail_1_1OptionalRelationCollectionTraits.html", null ],
    [ "OptionalRelationCollectionTraits&lt; std::optional&lt; T &gt; &gt;", "structorm_1_1detail_1_1OptionalRelationCollectionTraits_3_01std_1_1optional_3_01T_01_4_01_4.html", null ],
    [ "RelationMemberPointerTraits", "structorm_1_1detail_1_1RelationMemberPointerTraits.html", null ],
    [ "RelationMemberPointerTraits&lt; Value Owner::* &gt;", "structorm_1_1detail_1_1RelationMemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html", null ],
    [ "RelationColumnNames", "structorm_1_1detail_1_1RelationColumnNames.html", null ],
    [ "IsRelationDescriptor", "structorm_1_1detail_1_1IsRelationDescriptor.html", null ],
    [ "IsOneToManyDescriptor", "structorm_1_1detail_1_1IsOneToManyDescriptor.html", null ],
    [ "IsManyToManyDescriptor", "structorm_1_1detail_1_1IsManyToManyDescriptor.html", null ],
    [ "OneToManyDescriptor", "structorm_1_1OneToManyDescriptor.html", null ],
    [ "IsRelationDescriptor&lt; OneToManyDescriptor&lt; Member, MappedByMember, MappedByName &gt; &gt;", "structorm_1_1detail_1_1IsRelationDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
    [ "IsOneToManyDescriptor&lt; OneToManyDescriptor&lt; Member, MappedByMember, MappedByName &gt; &gt;", "structorm_1_1detail_1_1IsOneToManyDescriptor_3_01OneToManyDescriptor_3_01Member_00_01MappedByMember_00_01MappedByName_01_4_01_4.html", null ],
    [ "ManyToManyDescriptor", "structorm_1_1ManyToManyDescriptor.html", null ],
    [ "IsRelationDescriptor&lt; ManyToManyDescriptor&lt; Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames &gt; &gt;", "structorm_1_1detail_1_1IsRelationDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMemdc34019d2abea938502bc7c526da741a.html", null ],
    [ "IsManyToManyDescriptor&lt; ManyToManyDescriptor&lt; Member, MappedByMember, MappedByName, ThroughTable, OwnerColumnNames, TargetColumnNames &gt; &gt;", "structorm_1_1detail_1_1IsManyToManyDescriptor_3_01ManyToManyDescriptor_3_01Member_00_01MappedByMfa910bcc35e07f6cd9a576dac2955950.html", null ],
    [ "StaticPlan", "classorm_1_1query_1_1StaticPlan.html", null ],
    [ "ColumnName", "structorm_1_1model_1_1ColumnName.html", null ],
    [ "ColumnNames", "structorm_1_1model_1_1ColumnNames.html", null ],
    [ "PrimaryKey", "structorm_1_1model_1_1PrimaryKey.html", null ],
    [ "AutoIncrement", "structorm_1_1model_1_1AutoIncrement.html", null ],
    [ "LogicalTypeTraits", "structorm_1_1model_1_1LogicalTypeTraits.html", null ],
    [ "LogicalTypeTraits&lt; bool &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01bool_01_4.html", null ],
    [ "LogicalTypeTraits&lt; char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01char_01_4.html", null ],
    [ "LogicalTypeTraits&lt; signed char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01signed_01char_01_4.html", null ],
    [ "LogicalTypeTraits&lt; unsigned char &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01char_01_4.html", null ],
    [ "LogicalTypeTraits&lt; short &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01short_01_4.html", null ],
    [ "LogicalTypeTraits&lt; unsigned short &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01short_01_4.html", null ],
    [ "LogicalTypeTraits&lt; int &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01int_01_4.html", null ],
    [ "LogicalTypeTraits&lt; unsigned int &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01int_01_4.html", null ],
    [ "LogicalTypeTraits&lt; long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01_4.html", null ],
    [ "LogicalTypeTraits&lt; unsigned long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01_4.html", null ],
    [ "LogicalTypeTraits&lt; long long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01long_01long_01_4.html", null ],
    [ "LogicalTypeTraits&lt; unsigned long long &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01unsigned_01long_01long_01_4.html", null ],
    [ "LogicalTypeTraits&lt; float &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01float_01_4.html", null ],
    [ "LogicalTypeTraits&lt; double &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01double_01_4.html", null ],
    [ "LogicalTypeTraits&lt; std::string &gt;", "structorm_1_1model_1_1LogicalTypeTraits_3_01std_1_1string_01_4.html", null ],
    [ "TypeId", "structorm_1_1model_1_1TypeId.html", null ],
    [ "ColumnView", "structorm_1_1model_1_1ColumnView.html", "structorm_1_1model_1_1ColumnView" ],
    [ "JunctionView", "structorm_1_1model_1_1JunctionView.html", null ],
    [ "RelationView", "structorm_1_1model_1_1RelationView.html", null ],
    [ "ModelDataView", "structorm_1_1model_1_1ModelDataView.html", null ],
    [ "ModelView", "structorm_1_1model_1_1ModelView.html", null ],
    [ "SchemaView", "structorm_1_1model_1_1SchemaView.html", null ],
    [ "Schema", "structorm_1_1model_1_1Schema.html", null ],
    [ "StaticSchemaTraits", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits.html", null ],
    [ "StaticSchemaTraits&lt; Schema&lt; Models... &gt; &gt;", "structorm_1_1model_1_1detail_1_1StaticSchemaTraits_3_01Schema_3_01Models_8_8_8_01_4_01_4.html", null ],
    [ "IsFixedString", "structorm_1_1model_1_1detail_1_1IsFixedString.html", null ],
    [ "IsFixedString&lt; reflection::FixedString&lt; Size &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsFixedString_3_01reflection_1_1FixedString_3_01Size_01_4_01_4.html", null ],
    [ "IsColumnNames", "structorm_1_1model_1_1detail_1_1IsColumnNames.html", null ],
    [ "IsColumnNames&lt; ColumnNames&lt; Definitions... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsColumnNames_3_01ColumnNames_3_01Definitions_8_8_8_01_4_01_4.html", null ],
    [ "IsPrimaryKey", "structorm_1_1model_1_1detail_1_1IsPrimaryKey.html", null ],
    [ "IsPrimaryKey&lt; PrimaryKey&lt; Members... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsPrimaryKey_3_01PrimaryKey_3_01Members_8_8_8_01_4_01_4.html", null ],
    [ "IsAutoIncrement", "structorm_1_1model_1_1detail_1_1IsAutoIncrement.html", null ],
    [ "IsAutoIncrement&lt; AutoIncrement&lt; Members... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsAutoIncrement_3_01AutoIncrement_3_01Members_8_8_8_01_4_01_4.html", null ],
    [ "IsRelations", "structorm_1_1model_1_1detail_1_1IsRelations.html", null ],
    [ "IsRelations&lt; std::tuple&lt; Descriptors... &gt; &gt;", "structorm_1_1model_1_1detail_1_1IsRelations_3_01std_1_1tuple_3_01Descriptors_8_8_8_01_4_01_4.html", null ],
    [ "RelationNameBuffer", "structorm_1_1model_1_1detail_1_1RelationNameBuffer.html", null ],
    [ "DefaultJunctionColumnStorage", "structorm_1_1model_1_1detail_1_1DefaultJunctionColumnStorage.html", null ],
    [ "JunctionStorage", "structorm_1_1model_1_1detail_1_1JunctionStorage.html", null ],
    [ "StaticModel", "structorm_1_1model_1_1StaticModel.html", null ],
    [ "QueryValue", "classorm_1_1query_1_1QueryValue.html", null ],
    [ "QueryParameter", "structorm_1_1query_1_1QueryParameter.html", null ],
    [ "Parameter", "classorm_1_1query_1_1Parameter.html", null ],
    [ "TypedPredicate", "classorm_1_1query_1_1TypedPredicate.html", null ],
    [ "TypedAggregatePredicate", "classorm_1_1query_1_1TypedAggregatePredicate.html", null ],
    [ "Expression", "classorm_1_1query_1_1Expression.html", null ],
    [ "TypedColumn", "classorm_1_1query_1_1TypedColumn.html", null ],
    [ "TypedAggregate", "classorm_1_1query_1_1TypedAggregate.html", null ],
    [ "TypedOrderBy", "classorm_1_1query_1_1TypedOrderBy.html", null ],
    [ "TypedProjection", "classorm_1_1query_1_1TypedProjection.html", null ],
    [ "SchemaCapabilities", "structorm_1_1db_1_1SchemaCapabilities.html", null ],
    [ "QueryCapabilities", "structorm_1_1db_1_1QueryCapabilities.html", null ],
    [ "MutationCapabilities", "structorm_1_1db_1_1MutationCapabilities.html", null ],
    [ "RelationCapabilities", "structorm_1_1db_1_1RelationCapabilities.html", null ],
    [ "BackendValueLimits", "structorm_1_1db_1_1BackendValueLimits.html", "structorm_1_1db_1_1BackendValueLimits" ],
    [ "BackendCapabilities", "structorm_1_1db_1_1BackendCapabilities.html", null ],
    [ "BackendRuntimeLimits", "structorm_1_1db_1_1BackendRuntimeLimits.html", null ],
    [ "BackendProvider", "classorm_1_1db_1_1BackendProvider.html", null ],
    [ "BoundValue", "structorm_1_1db_1_1BoundValue.html", null ],
    [ "StatementParameter", "structorm_1_1db_1_1StatementParameter.html", null ],
    [ "Statement", "structorm_1_1db_1_1Statement.html", null ],
    [ "StatementView", "structorm_1_1db_1_1StatementView.html", null ],
    [ "BackendRuntime", "classorm_1_1db_1_1BackendRuntime.html", null ],
    [ "CreateTableCommand", "classorm_1_1db_1_1commands_1_1CreateTableCommand.html", null ],
    [ "DeleteCommand", "classorm_1_1db_1_1commands_1_1DeleteCommand.html", null ],
    [ "DropTableCommand", "classorm_1_1db_1_1commands_1_1DropTableCommand.html", null ],
    [ "InsertCommand", "classorm_1_1db_1_1commands_1_1InsertCommand.html", null ],
    [ "SelectCommand", "classorm_1_1db_1_1commands_1_1SelectCommand.html", null ],
    [ "UpdateCommand", "classorm_1_1db_1_1commands_1_1UpdateCommand.html", null ],
    [ "CommandGenerator", "classorm_1_1db_1_1CommandGenerator.html", null ],
    [ "CommandGeneratorFactory", "classorm_1_1db_1_1CommandGeneratorFactory.html", null ],
    [ "PaginationSpec", "structorm_1_1db_1_1PaginationSpec.html", null ],
    [ "InsertIfAbsentSpec", "structorm_1_1db_1_1InsertIfAbsentSpec.html", null ],
    [ "SqlDialect", "classorm_1_1db_1_1SqlDialect.html", null ],
    [ "TypeTranslator", "classorm_1_1db_1_1TypeTranslator.html", null ],
    [ "Query", "classorm_1_1Query.html", "classorm_1_1Query" ],
    [ "ProjectionQuery", "classorm_1_1ProjectionQuery.html", null ],
    [ "Update", "classorm_1_1Update.html", null ],
    [ "type_conversion&lt; BindingPayload&lt; T, SchemaType, JoinedValues &gt; &gt;", "structsoci_1_1type__conversion_3_01BindingPayload_3_01T_00_01SchemaType_00_01JoinedValues_01_4_01_4.html", null ],
    [ "type_conversion&lt; orm::db::binding::CollectionPayload&lt; Owner, Target, SchemaType, JoinedValues &gt; &gt;", "structsoci_1_1type__conversion_3_01orm_1_1db_1_1binding_1_1CollectionPayload_3_01Owner_00_01Targffa2c747085deef29bc443f637394051.html", null ],
    [ "type_conversion&lt; ProjectionPayload&lt; T &gt; &gt;", "structsoci_1_1type__conversion_3_01ProjectionPayload_3_01T_01_4_01_4.html", null ],
    [ "DatabaseCore", "classorm_1_1DatabaseCore.html", "classorm_1_1DatabaseCore" ],
    [ "StaticPlanType", "conceptorm_1_1query_1_1detail_1_1StaticPlanType.html", null ]
];