var searchData=
[
  ['schema_0',['Schema',['../structorm_1_1model_1_1Schema.html',1,'orm::model']]],
  ['schema_1',['schema',['../md_docs_2relations.html#autotoc_md107',1,'Migrating an existing schema'],['../md_docs_2model.html#autotoc_md53',1,'Static schema']]],
  ['schema_20lifecycle_2',['Schema lifecycle',['../md_docs_2relations.html#autotoc_md99',1,'']]],
  ['schema_3c_20models_2e_2e_2e_20_3e_3',['Schema&lt; Models... &gt;',['../structorm_1_1model_1_1Schema.html',1,'orm::model']]],
  ['schemacapabilities_4',['SchemaCapabilities',['../structorm_1_1db_1_1SchemaCapabilities.html',1,'orm::db']]],
  ['schemamodel_5',['SchemaModel',['../conceptorm_1_1db_1_1binding_1_1SchemaModel.html',1,'orm::db::binding']]],
  ['schemaview_6',['SchemaView',['../structorm_1_1model_1_1SchemaView.html',1,'orm::model']]],
  ['select_7',['Build select',['../md_docs_2query.html#autotoc_md80',1,'']]],
  ['selectcommand_8',['SelectCommand',['../classorm_1_1db_1_1commands_1_1SelectCommand.html',1,'orm::db::commands']]],
  ['selectplanimpl_9',['selectPlanImpl',['../classorm_1_1DatabaseCore.html#a71cc2254b98daa4cc02394321c3c67b1',1,'orm::DatabaseCore']]],
  ['selectspec_10',['SelectSpec',['../structorm_1_1query_1_1detail_1_1SelectSpec.html',1,'orm::query::detail']]],
  ['setup_20and_20publishing_11',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md69',1,'']]],
  ['shapes_20and_20explicit_20conversion_12',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md110',1,'']]],
  ['slotindices_13',['SlotIndices',['../structorm_1_1query_1_1detail_1_1SlotIndices.html',1,'orm::query::detail']]],
  ['slotindices_3c_20std_3a_3atuple_3c_20p_2e_2e_2e_20_3e_20_3e_14',['SlotIndices&lt; std::tuple&lt; P... &gt; &gt;',['../structorm_1_1query_1_1detail_1_1SlotIndices_3_01std_1_1tuple_3_01P_8_8_8_01_4_01_4.html',1,'orm::query::detail']]],
  ['slottypescompatible_15',['SlotTypesCompatible',['../structorm_1_1query_1_1detail_1_1SlotTypesCompatible.html',1,'orm::query::detail']]],
  ['slottypescompatible_3c_20p_2c_20std_3a_3atuple_3c_20slots_2e_2e_2e_20_3e_20_3e_16',['SlotTypesCompatible&lt; P, std::tuple&lt; Slots... &gt; &gt;',['../structorm_1_1query_1_1detail_1_1SlotTypesCompatible_3_01P_00_01std_1_1tuple_3_01Slots_8_8_8_01_4_01_4.html',1,'orm::query::detail']]],
  ['soci_17',['Binding and SOCI',['../md_docs_2backend-portability.html#autotoc_md14',1,'']]],
  ['soci_20boundary_18',['SOCI boundary',['../md_docs_2backend-extension.html#autotoc_md4',1,'']]],
  ['sociconvertabletodouble_19',['SociConvertableToDouble',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToDouble.html',1,'orm::db::binding']]],
  ['sociconvertabletoint_20',['SociConvertableToInt',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToInt.html',1,'orm::db::binding']]],
  ['sociconvertabletolonglong_21',['SociConvertableToLongLong',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToLongLong.html',1,'orm::db::binding']]],
  ['sociconvertabletounsignedlonglong_22',['SociConvertableToUnsignedLongLong',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToUnsignedLongLong.html',1,'orm::db::binding']]],
  ['socidefaultsupported_23',['SociDefaultSupported',['../conceptorm_1_1db_1_1binding_1_1SociDefaultSupported.html',1,'orm::db::binding']]],
  ['sql_24',['SQL',['../md_docs_2backend-extension.html#autotoc_md5',1,'Raw SQL'],['../md_docs_2backend-portability.html#autotoc_md15',1,'Raw SQL']]],
  ['sql_20fragments_25',['Raw SQL fragments',['../md_docs_2query.html#autotoc_md88',1,'']]],
  ['sql_20portability_26',['Raw SQL portability',['../md_docs_2backends.html#autotoc_md26',1,'']]],
  ['sqlassignment_27',['SqlAssignment',['../structorm_1_1db_1_1detail_1_1SqlAssignment.html',1,'orm::db::detail']]],
  ['sqlbindingdescriptor_28',['SqlBindingDescriptor',['../structorm_1_1db_1_1detail_1_1SqlBindingDescriptor.html',1,'orm::db::detail']]],
  ['sqlcolumninfo_29',['SqlColumnInfo',['../structorm_1_1db_1_1detail_1_1SqlColumnInfo.html',1,'orm::db::detail']]],
  ['sqldialect_30',['SqlDialect',['../classorm_1_1db_1_1SqlDialect.html',1,'orm::db']]],
  ['sqlite_31',['SQLite',['../md_docs_2backends.html#autotoc_md22',1,'']]],
  ['sqlnode_32',['SqlNode',['../structorm_1_1db_1_1detail_1_1SqlNode.html',1,'orm::db::detail']]],
  ['sqlorder_33',['SqlOrder',['../structorm_1_1db_1_1detail_1_1SqlOrder.html',1,'orm::db::detail']]],
  ['sqlprogram_34',['SqlProgram',['../structorm_1_1db_1_1detail_1_1SqlProgram.html',1,'orm::db::detail']]],
  ['sqlprojection_35',['SqlProjection',['../structorm_1_1db_1_1detail_1_1SqlProjection.html',1,'orm::db::detail']]],
  ['sqlqueryview_36',['SqlQueryView',['../structorm_1_1db_1_1detail_1_1SqlQueryView.html',1,'orm::db::detail']]],
  ['sqlrenderscope_37',['SqlRenderScope',['../structorm_1_1db_1_1detail_1_1SqlRenderScope.html',1,'orm::db::detail']]],
  ['sqlsource_38',['SqlSource',['../structorm_1_1db_1_1detail_1_1SqlSource.html',1,'orm::db::detail']]],
  ['statement_39',['Statement',['../structorm_1_1db_1_1Statement.html',1,'orm::db']]],
  ['statementparameter_40',['StatementParameter',['../structorm_1_1db_1_1StatementParameter.html',1,'orm::db']]],
  ['statementview_41',['StatementView',['../structorm_1_1db_1_1StatementView.html',1,'orm::db']]],
  ['static_20query_20plans_42',['Static query plans',['../md_docs_2static-queries.html',1,'']]],
  ['static_20schema_43',['Static schema',['../md_docs_2model.html#autotoc_md53',1,'']]],
  ['staticmodel_44',['StaticModel',['../structorm_1_1model_1_1StaticModel.html',1,'orm::model']]],
  ['staticoptionaltraits_45',['StaticOptionalTraits',['../structorm_1_1model_1_1detail_1_1StaticOptionalTraits.html',1,'orm::model::detail']]],
  ['staticoptionaltraits_3c_20std_3a_3aoptional_3c_20t_20_3e_20_3e_46',['StaticOptionalTraits&lt; std::optional&lt; T &gt; &gt;',['../structorm_1_1model_1_1detail_1_1StaticOptionalTraits_3_01std_1_1optional_3_01T_01_4_01_4.html',1,'orm::model::detail']]],
  ['staticplan_47',['StaticPlan',['../classorm_1_1query_1_1StaticPlan.html',1,'orm::query']]],
  ['staticplantype_48',['StaticPlanType',['../conceptorm_1_1query_1_1detail_1_1StaticPlanType.html',1,'orm::query::detail']]],
  ['staticschematraits_49',['StaticSchemaTraits',['../structorm_1_1model_1_1detail_1_1StaticSchemaTraits.html',1,'orm::model::detail']]],
  ['staticschematraits_3c_20schema_3c_20models_2e_2e_2e_20_3e_20_3e_50',['StaticSchemaTraits&lt; Schema&lt; Models... &gt; &gt;',['../structorm_1_1model_1_1detail_1_1StaticSchemaTraits_3_01Schema_3_01Models_8_8_8_01_4_01_4.html',1,'orm::model::detail']]],
  ['staticsqlpolicy_51',['StaticSqlPolicy',['../structorm_1_1db_1_1detail_1_1StaticSqlPolicy.html',1,'orm::db::detail']]],
  ['status_52',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['status_53',['Support status',['../md_docs_2backends.html#autotoc_md20',1,'']]],
  ['support_20status_54',['Support status',['../md_docs_2backends.html#autotoc_md20',1,'']]],
  ['supported_20field_20types_55',['Supported field types',['../md_docs_2model.html#autotoc_md54',1,'']]]
];
