var searchData=
[
  ['a_20glance_0',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['a_20model_1',['Create a model',['../md_docs_2model.html#autotoc_md69',1,'']]],
  ['acceptance_2',['acceptance',['../md_docs_2packaging.html#autotoc_md82',1,'Consume from ConanCenter after acceptance'],['../md_docs_2packaging.html#autotoc_md81',1,'Consume from vcpkg after acceptance']]],
  ['adding_20new_20compiler_20versions_3',['Adding New Compiler Versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'']]],
  ['after_20acceptance_4',['after acceptance',['../md_docs_2packaging.html#autotoc_md82',1,'Consume from ConanCenter after acceptance'],['../md_docs_2packaging.html#autotoc_md81',1,'Consume from vcpkg after acceptance']]],
  ['aggregate_20projection_20queries_5',['Aggregate projection queries',['../md_docs_2query.html#autotoc_md105',1,'']]],
  ['aggregate_20result_20queries_6',['Aggregate result queries',['../md_docs_2partial-result-queries.html#autotoc_md90',1,'']]],
  ['an_20existing_20schema_7',['Migrating an existing schema',['../md_docs_2relations.html#autotoc_md121',1,'']]],
  ['and_20checks_8',['Policy and checks',['../md_docs_2migration-macro-free.html#autotoc_md52',1,'']]],
  ['and_20ci_20integration_9',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['and_20consistency_10',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md118',1,'']]],
  ['and_20delete_20relation_20tables_11',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['and_20dialect_20differences_12',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['and_20errors_13',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['and_20explicit_20conversion_14',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md124',1,'']]],
  ['and_20having_15',['Full-model grouping and HAVING',['../md_docs_2query.html#autotoc_md104',1,'']]],
  ['and_20offset_16',['Limit and offset',['../md_docs_2query.html#autotoc_md101',1,'']]],
  ['and_20publishing_17',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md83',1,'']]],
  ['and_20relations_18',['and relations',['../md_docs_2migration-static-schema.html#autotoc_md60',1,'5. Migrate query fields and relations'],['../md_docs_2query.html#autotoc_md98',1,'Column names and relations']]],
  ['and_20releases_19',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['and_20soci_20',['Binding and SOCI',['../md_docs_2backend-portability.html#autotoc_md14',1,'']]],
  ['and_20static_20schemas_21',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['and_20unlink_22',['Link and unlink',['../md_docs_2relations.html#autotoc_md114',1,'']]],
  ['and_20unlink_20relations_23',['Link and unlink relations',['../md_docs_2database.html#autotoc_md44',1,'']]],
  ['and_20unsupported_20mappings_24',['Validation and unsupported mappings',['../md_docs_2relations.html#autotoc_md119',1,'']]],
  ['and_20writes_25',['Projections and writes',['../md_docs_2static-queries.html#autotoc_md123',1,'']]],
  ['and_20writes_20explicit_26',['Make NULL and writes explicit',['../md_docs_2migration-typed-queries.html#autotoc_md66',1,'']]],
  ['andhaving_27',['andHaving',['../classorm_1_1Query.html#ae9ee888eaadd043c931ff3fbe146717f',1,'orm::Query']]],
  ['andwhere_28',['andWhere',['../classorm_1_1Query.html#aa01f058326d165d0616dcfdf379c5d35',1,'orm::Query']]],
  ['at_20a_20glance_29',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['at_20the_20database_20boundary_30',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md67',1,'']]],
  ['auto_20increment_20primary_20key_31',['Auto-increment primary key',['../md_docs_2model.html#autotoc_md76',1,'']]]
];
