var searchData=
[
  ['schema_0',['schema',['../md_docs_2migration-static-schema.html#autotoc_md55',1,'4. Define the closed schema'],['../md_docs_2relations.html#autotoc_md117',1,'Migrating an existing schema'],['../md_docs_2model.html#autotoc_md66',1,'Static schema']]],
  ['schema_20lifecycle_1',['Schema lifecycle',['../md_docs_2relations.html#autotoc_md109',1,'']]],
  ['schemas_2',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['select_3',['Build select',['../md_docs_2query.html#autotoc_md90',1,'']]],
  ['selectplanimpl_4',['selectPlanImpl',['../classorm_1_1DatabaseCore.html#a71cc2254b98daa4cc02394321c3c67b1',1,'orm::DatabaseCore']]],
  ['setup_20and_20publishing_5',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md79',1,'']]],
  ['shapes_20and_20explicit_20conversion_6',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md120',1,'']]],
  ['soci_7',['Binding and SOCI',['../md_docs_2backend-portability.html#autotoc_md14',1,'']]],
  ['soci_20boundary_8',['SOCI boundary',['../md_docs_2backend-extension.html#autotoc_md4',1,'']]],
  ['sql_9',['SQL',['../md_docs_2backend-extension.html#autotoc_md5',1,'Raw SQL'],['../md_docs_2backend-portability.html#autotoc_md15',1,'Raw SQL']]],
  ['sql_20fragments_10',['Raw SQL fragments',['../md_docs_2query.html#autotoc_md98',1,'']]],
  ['sql_20portability_11',['Raw SQL portability',['../md_docs_2backends.html#autotoc_md26',1,'']]],
  ['sqlite_12',['SQLite',['../md_docs_2backends.html#autotoc_md22',1,'']]],
  ['static_20query_20plans_13',['Static query plans',['../md_docs_2static-queries.html',1,'']]],
  ['static_20schema_14',['Static schema',['../md_docs_2model.html#autotoc_md66',1,'']]],
  ['static_20schemas_15',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['status_16',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['status_17',['Support status',['../md_docs_2backends.html#autotoc_md20',1,'']]],
  ['suggested_20rollout_18',['Suggested rollout',['../md_docs_2migration-static-schema.html#autotoc_md57',1,'']]],
  ['summary_19',['Migration summary',['../md_docs_2migration-static-schema.html#autotoc_md51',1,'']]],
  ['support_20status_20',['Support status',['../md_docs_2backends.html#autotoc_md20',1,'']]],
  ['supported_20field_20types_21',['Supported field types',['../md_docs_2model.html#autotoc_md67',1,'']]]
];
