var searchData=
[
  ['range_0',['Use values that preserve their entire type range',['../md_docs_2migration-typed-queries.html#autotoc_md65',1,'']]],
  ['raw_20sql_1',['Raw SQL',['../md_docs_2backend-extension.html#autotoc_md5',1,'Raw SQL'],['../md_docs_2backend-portability.html#autotoc_md15',1,'Raw SQL']]],
  ['raw_20sql_20fragments_2',['Raw SQL fragments',['../md_docs_2query.html#autotoc_md102',1,'']]],
  ['raw_20sql_20portability_3',['Raw SQL portability',['../md_docs_2backends.html#autotoc_md26',1,'']]],
  ['read_20the_20configuration_20in_20c_4',['Read the configuration in C++',['../md_docs_2migration-macro-free.html#autotoc_md50',1,'']]],
  ['reflectable_5',['1. Keep models reflectable',['../md_docs_2migration-static-schema.html#autotoc_md56',1,'']]],
  ['relation_20tables_6',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['relationcollection_7',['RelationCollection',['../classorm_1_1detail_1_1RelationCollection.html',1,'orm::detail']]],
  ['relationcollectiontraits_8',['RelationCollectionTraits',['../structorm_1_1detail_1_1RelationCollectionTraits.html',1,'orm::detail']]],
  ['relationcollectiontraits_3c_20manytomany_3c_20t_20_3e_20_3e_9',['RelationCollectionTraits&lt; ManyToMany&lt; T &gt; &gt;',['../structorm_1_1detail_1_1RelationCollectionTraits_3_01ManyToMany_3_01T_01_4_01_4.html',1,'orm::detail']]],
  ['relationcollectiontraits_3c_20onetomany_3c_20t_20_3e_20_3e_10',['RelationCollectionTraits&lt; OneToMany&lt; T &gt; &gt;',['../structorm_1_1detail_1_1RelationCollectionTraits_3_01OneToMany_3_01T_01_4_01_4.html',1,'orm::detail']]],
  ['relationcolumnnames_11',['RelationColumnNames',['../structorm_1_1detail_1_1RelationColumnNames.html',1,'orm::detail']]],
  ['relationmemberpointertraits_12',['RelationMemberPointerTraits',['../structorm_1_1detail_1_1RelationMemberPointerTraits.html',1,'orm::detail']]],
  ['relationmemberpointertraits_3c_20value_20owner_3a_3a_2a_20_3e_13',['RelationMemberPointerTraits&lt; Value Owner::* &gt;',['../structorm_1_1detail_1_1RelationMemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html',1,'orm::detail']]],
  ['relations_14',['relations',['../md_docs_2migration-static-schema.html#autotoc_md60',1,'5. Migrate query fields and relations'],['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md78',1,'Collection relations'],['../md_docs_2query.html#autotoc_md98',1,'Column names and relations'],['../md_docs_2database.html#autotoc_md44',1,'Link and unlink relations'],['../md_docs_2model.html#autotoc_md77',1,'One-to-one relations']]],
  ['release_15',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md84',1,'']]],
  ['releases_16',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['remove_20objects_17',['Remove objects',['../md_docs_2database.html#autotoc_md47',1,'']]],
  ['removeimpl_18',['removeImpl',['../classorm_1_1DatabaseCore.html#a52e2d23d75aad96891051c9dbc08365c',1,'orm::DatabaseCore']]],
  ['replace_200_201_20expressions_19',['Replace 0.1 expressions',['../md_docs_2migration-typed-queries.html#autotoc_md63',1,'']]],
  ['replace_20runtime_20model_20configuration_20',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md57',1,'']]],
  ['reporting_21',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['required_20backend_20responsibilities_22',['Required backend responsibilities',['../md_docs_2backend-extension.html#autotoc_md2',1,'']]],
  ['responsibilities_23',['Required backend responsibilities',['../md_docs_2backend-extension.html#autotoc_md2',1,'']]],
  ['result_20dto_20rules_24',['Result DTO rules',['../md_docs_2partial-result-queries.html#autotoc_md91',1,'']]],
  ['result_20queries_25',['result queries',['../md_docs_2partial-result-queries.html#autotoc_md90',1,'Aggregate result queries'],['../md_docs_2partial-result-queries.html',1,'Partial-result queries'],['../md_docs_2query.html#autotoc_md103',1,'Partial-result queries']]],
  ['retain_20runtime_20validation_20at_20the_20database_20boundary_26',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md67',1,'']]],
  ['retry_20without_20changing_20the_20release_27',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md84',1,'']]],
  ['rollbacktransaction_28',['rollbackTransaction',['../classorm_1_1DatabaseCore.html#a5ca1f8fd77ea6d27226a2cb2e4451442',1,'orm::DatabaseCore']]],
  ['rollout_29',['Suggested rollout',['../md_docs_2migration-static-schema.html#autotoc_md61',1,'']]],
  ['rules_30',['Result DTO rules',['../md_docs_2partial-result-queries.html#autotoc_md91',1,'']]],
  ['runtime_20model_20configuration_31',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md57',1,'']]],
  ['runtime_20shapes_20and_20explicit_20conversion_32',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md124',1,'']]],
  ['runtime_20validation_20at_20the_20database_20boundary_33',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md67',1,'']]]
];
