var searchData=
[
  ['package_20managers_20and_20releases_0',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['package_20verification_1',['Local package verification',['../md_docs_2packaging.html#autotoc_md71',1,'']]],
  ['partial_20result_20queries_2',['partial result queries',['../md_docs_2query.html#autotoc_md89',1,'Partial-result queries'],['../md_docs_2partial-result-queries.html',1,'Partial-result queries']]],
  ['partition_20dependencies_3',['Partition dependencies',['../md_docs_2modules.html#autotoc_md64',1,'']]],
  ['planaccess_4',['PlanAccess',['../structorm_1_1query_1_1detail_1_1PlanAccess.html',1,'orm::query::detail']]],
  ['plans_5',['Static query plans',['../md_docs_2static-queries.html',1,'']]],
  ['pointerwrapper_6',['PointerWrapper',['../structorm_1_1reflection_1_1detail_1_1PointerWrapper.html',1,'orm::reflection::detail']]],
  ['points_7',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['policy_8',['policy',['../index.html#autotoc_md50',1,'Build configuration and macro policy'],['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'Coverage Policy']]],
  ['portability_9',['portability',['../md_docs_2backend-portability.html',1,'Backend portability'],['../md_docs_2backends.html#autotoc_md26',1,'Raw SQL portability']]],
  ['portability_20layers_10',['Portability layers',['../md_docs_2backend-portability.html#autotoc_md11',1,'']]],
  ['portable_20behavior_11',['Portable behavior',['../md_docs_2backend-portability.html#autotoc_md12',1,'']]],
  ['postgresql_12',['PostgreSQL',['../md_docs_2backends.html#autotoc_md23',1,'']]],
  ['postgresql_20compiler_20matrix_13',['PostgreSQL Compiler Matrix',['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'']]],
  ['predicate_14',['predicate',['../classorm_1_1query_1_1detail_1_1Predicate.html#ac2c127d544cff99eba703fcdfc1ea592',1,'orm::query::detail::Predicate::Predicate()'],['../classorm_1_1query_1_1detail_1_1Predicate.html',1,'orm::query::detail::Predicate']]],
  ['predicatenode_15',['PredicateNode',['../structorm_1_1query_1_1detail_1_1PredicateNode.html',1,'orm::query::detail']]],
  ['predicates_16',['predicates',['../md_docs_2query.html#autotoc_md83',1,'Collection predicates'],['../md_docs_2query.html#autotoc_md82',1,'Where predicates'],['../md_docs_2query.html#autotoc_md92',1,'Write predicates']]],
  ['presets_17',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['primary_20key_18',['primary key',['../md_docs_2model.html#autotoc_md59',1,'Auto-increment primary key'],['../md_docs_2model.html#autotoc_md58',1,'Primary key']]],
  ['primarykey_19',['PrimaryKey',['../structorm_1_1model_1_1PrimaryKey.html',1,'orm::model']]],
  ['primarykeyless_20',['PrimaryKeyLess',['../structorm_1_1db_1_1binding_1_1PrimaryKeyLess.html',1,'orm::db::binding']]],
  ['projection_21',['Projection',['../structorm_1_1query_1_1detail_1_1Projection.html',1,'orm::query::detail']]],
  ['projection_20queries_22',['Aggregate projection queries',['../md_docs_2query.html#autotoc_md91',1,'']]],
  ['projectionpayload_23',['ProjectionPayload',['../structorm_1_1db_1_1binding_1_1ProjectionPayload.html',1,'orm::db::binding']]],
  ['projections_20and_20writes_24',['Projections and writes',['../md_docs_2static-queries.html#autotoc_md109',1,'']]],
  ['publishing_25',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md69',1,'']]]
];
