var searchData=
[
  ['package_20managers_20and_20releases_0',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['package_20verification_1',['Local package verification',['../md_docs_2packaging.html#autotoc_md71',1,'']]],
  ['paginationspec_2',['PaginationSpec',['../structorm_1_1db_1_1PaginationSpec.html',1,'orm::db']]],
  ['parameter_3',['Parameter',['../classorm_1_1query_1_1Parameter.html',1,'orm::query']]],
  ['parametertypestrait_4',['ParameterTypesTrait',['../structorm_1_1query_1_1detail_1_1ParameterTypesTrait.html',1,'orm::query::detail']]],
  ['parametertypestrait_3c_20std_3a_3atuple_3c_20t_2e_2e_2e_20_3e_2c_20void_20_3e_5',['ParameterTypesTrait&lt; std::tuple&lt; T... &gt;, void &gt;',['../structorm_1_1query_1_1detail_1_1ParameterTypesTrait_3_01std_1_1tuple_3_01T_8_8_8_01_4_00_01void_01_4.html',1,'orm::query::detail']]],
  ['parametertypestrait_3c_20t_2c_20std_3a_3avoid_5ft_3c_20typename_20t_3a_3aparametertypes_20_3e_20_3e_6',['ParameterTypesTrait&lt; T, std::void_t&lt; typename T::ParameterTypes &gt; &gt;',['../structorm_1_1query_1_1detail_1_1ParameterTypesTrait_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1ParameterTypes_01_4_01_4.html',1,'orm::query::detail']]],
  ['parametervalue_7',['ParameterValue',['../structorm_1_1query_1_1detail_1_1ParameterValue.html',1,'orm::query::detail']]],
  ['parametervalue_3c_20parameter_3c_20t_2c_20i_20_3e_20_3e_8',['ParameterValue&lt; Parameter&lt; T, I &gt; &gt;',['../structorm_1_1query_1_1detail_1_1ParameterValue_3_01Parameter_3_01T_00_01I_01_4_01_4.html',1,'orm::query::detail']]],
  ['partial_20result_20queries_9',['Partial result queries',['../md_docs_2partial-result-queries.html',1,'Partial-result queries'],['../md_docs_2query.html#autotoc_md89',1,'Partial-result queries']]],
  ['partition_20dependencies_10',['Partition dependencies',['../md_docs_2modules.html#autotoc_md64',1,'']]],
  ['planaccess_11',['PlanAccess',['../structorm_1_1query_1_1detail_1_1PlanAccess.html',1,'orm::query::detail']]],
  ['planaggregatepredicatefor_12',['PlanAggregatePredicateFor',['../conceptorm_1_1query_1_1detail_1_1PlanAggregatePredicateFor.html',1,'orm::query::detail']]],
  ['planpredicatefor_13',['PlanPredicateFor',['../conceptorm_1_1query_1_1detail_1_1PlanPredicateFor.html',1,'orm::query::detail']]],
  ['plans_14',['Static query plans',['../md_docs_2static-queries.html',1,'']]],
  ['pointerwrapper_15',['PointerWrapper',['../structorm_1_1reflection_1_1detail_1_1PointerWrapper.html',1,'orm::reflection::detail']]],
  ['points_16',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['policy_17',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['policy_18',['Build configuration and macro policy',['../index.html#autotoc_md50',1,'']]],
  ['portability_19',['portability',['../md_docs_2backend-portability.html',1,'Backend portability'],['../md_docs_2backends.html#autotoc_md26',1,'Raw SQL portability']]],
  ['portability_20layers_20',['Portability layers',['../md_docs_2backend-portability.html#autotoc_md11',1,'']]],
  ['portable_20behavior_21',['Portable behavior',['../md_docs_2backend-portability.html#autotoc_md12',1,'']]],
  ['postgresql_22',['PostgreSQL',['../md_docs_2backends.html#autotoc_md23',1,'']]],
  ['postgresql_20compiler_20matrix_23',['PostgreSQL Compiler Matrix',['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'']]],
  ['predicate_24',['Predicate',['../classorm_1_1query_1_1detail_1_1Predicate.html',1,'orm::query::detail::Predicate'],['../classorm_1_1query_1_1detail_1_1Predicate.html#ac2c127d544cff99eba703fcdfc1ea592',1,'orm::query::detail::Predicate::Predicate()']]],
  ['predicateexpression_25',['PredicateExpression',['../conceptorm_1_1query_1_1detail_1_1PredicateExpression.html',1,'orm::query::detail']]],
  ['predicatefor_26',['PredicateFor',['../conceptorm_1_1query_1_1detail_1_1PredicateFor.html',1,'orm::query::detail']]],
  ['predicatenode_27',['PredicateNode',['../structorm_1_1query_1_1detail_1_1PredicateNode.html',1,'orm::query::detail']]],
  ['predicates_28',['predicates',['../md_docs_2query.html#autotoc_md83',1,'Collection predicates'],['../md_docs_2query.html#autotoc_md82',1,'Where predicates'],['../md_docs_2query.html#autotoc_md92',1,'Write predicates']]],
  ['presets_29',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['primary_20key_30',['Primary key',['../md_docs_2model.html#autotoc_md58',1,'']]],
  ['primary_20key_31',['Auto-increment primary key',['../md_docs_2model.html#autotoc_md59',1,'']]],
  ['primarykey_32',['PrimaryKey',['../structorm_1_1model_1_1PrimaryKey.html',1,'orm::model']]],
  ['primarykeyless_33',['PrimaryKeyLess',['../structorm_1_1db_1_1binding_1_1PrimaryKeyLess.html',1,'orm::db::binding']]],
  ['projection_34',['Projection',['../structorm_1_1query_1_1detail_1_1Projection.html',1,'orm::query::detail']]],
  ['projection_20queries_35',['Aggregate projection queries',['../md_docs_2query.html#autotoc_md91',1,'']]],
  ['projectionfor_36',['ProjectionFor',['../conceptorm_1_1query_1_1detail_1_1ProjectionFor.html',1,'orm::query::detail']]],
  ['projectionmeta_37',['ProjectionMeta',['../structorm_1_1query_1_1detail_1_1ProjectionMeta.html',1,'orm::query::detail']]],
  ['projectionpayload_38',['ProjectionPayload',['../structorm_1_1db_1_1binding_1_1ProjectionPayload.html',1,'orm::db::binding']]],
  ['projectionquery_39',['ProjectionQuery',['../classorm_1_1ProjectionQuery.html',1,'orm']]],
  ['projectionresultfield_40',['ProjectionResultField',['../structorm_1_1detail_1_1ProjectionResultField.html',1,'orm::detail']]],
  ['projections_20and_20writes_41',['Projections and writes',['../md_docs_2static-queries.html#autotoc_md109',1,'']]],
  ['projectionsourceexpression_42',['ProjectionSourceExpression',['../conceptorm_1_1query_1_1detail_1_1ProjectionSourceExpression.html',1,'orm::query::detail']]],
  ['publishing_43',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md69',1,'']]]
];
