var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_1',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_2',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['capabilities_20versus_20dialect_3',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_4',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['ci_20compiler_20matrix_5',['CI Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'']]],
  ['ci_20integration_6',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_7',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['ci_20status_8',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['clang_9',['Clang',['../md_docs_2ci-compiler-matrix.html#autotoc_md31',1,'']]],
  ['closed_20schema_10',['4. Define the closed schema',['../md_docs_2migration-static-schema.html#autotoc_md54',1,'']]],
  ['cmake_20presets_11',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['collection_20mappings_12',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md53',1,'']]],
  ['collection_20predicates_13',['Collection predicates',['../md_docs_2query.html#autotoc_md79',1,'']]],
  ['collection_20relations_14',['Collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md67',1,'Collection relations']]],
  ['collection_20wrappers_15',['Collection wrappers',['../md_docs_2relations.html#autotoc_md91',1,'']]],
  ['collections_16',['collections',['../md_docs_2relations.html#autotoc_md98',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md77',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md97',1,'Loading collections']]],
  ['column_20names_17',['Column names',['../md_docs_2model.html#autotoc_md63',1,'']]],
  ['column_20names_18',['Junction column names',['../md_docs_2relations.html#autotoc_md94',1,'']]],
  ['column_20names_20and_20relations_19',['Column names and relations',['../md_docs_2query.html#autotoc_md80',1,'']]],
  ['committransaction_20',['commitTransaction',['../classorm_1_1DatabaseCore.html#ab867a949d0b37aeb452955c28dcee72c',1,'orm::DatabaseCore']]],
  ['common_20mistakes_21',['Common mistakes',['../md_docs_2relations.html#autotoc_md102',1,'']]],
  ['compatibility_20at_20a_20glance_22',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['compile_20time_20mappings_20and_20static_20schemas_23',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['compiler_20matrix_24',['Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['compiler_20versions_25',['Compiler Versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'Adding New Compiler Versions'],['../md_docs_2ci-compiler-matrix.html#autotoc_md29',1,'Tested Compiler Versions']]],
  ['concrete_20extension_20points_26',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_27',['configuration',['../md_docs_2migration-static-schema.html#autotoc_md52',1,'2. Replace runtime model configuration'],['../md_docs_2backends.html#autotoc_md24',1,'Build configuration']]],
  ['conformance_20tests_28',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_29',['Connect',['../md_docs_2database.html#autotoc_md38',1,'']]],
  ['connect_30',['connect',['../classorm_1_1DatabaseCore.html#a4fd6a2b78915e33468c808e3e14f8319',1,'orm::DatabaseCore::connect(const std::string &amp;connectionString) -&gt; void'],['../classorm_1_1DatabaseCore.html#a9089cbdeb18b77659c89517f7df8c14e',1,'orm::DatabaseCore::connect(db::BackendType requestedBackend, const std::string &amp;connectionString) -&gt; void']]],
  ['consistency_31',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md100',1,'']]],
  ['contract_32',['Contract',['../md_docs_2partial-result-queries.html#autotoc_md70',1,'']]],
  ['contract_33',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['convert_20collection_20mappings_34',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md53',1,'']]],
  ['coverage_20policy_35',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['create_20a_20model_36',['Create a model',['../md_docs_2model.html#autotoc_md58',1,'']]],
  ['create_20and_20delete_20relation_20tables_37',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['create_20table_38',['Create table',['../md_docs_2database.html#autotoc_md40',1,'']]],
  ['createrelationtablesimpl_39',['createRelationTablesImpl',['../classorm_1_1DatabaseCore.html#ac278df3368bf370aedaa35d1da0f789a',1,'orm::DatabaseCore']]],
  ['createtableimpl_40',['createTableImpl',['../classorm_1_1DatabaseCore.html#ad7cb162365dcbcfc96a39a6146d5958f',1,'orm::DatabaseCore']]],
  ['current_20limitations_41',['Current limitations',['../md_docs_2model.html#autotoc_md68',1,'']]]
];
