var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['c_2020_20modules_1',['C++20 modules',['../md_docs_2modules.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_2',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_3',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['capabilities_20versus_20dialect_4',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_5',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['capturedtext_6',['CapturedText',['../structorm_1_1query_1_1detail_1_1CapturedText.html',1,'orm::query::detail']]],
  ['changing_20the_20release_7',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md70',1,'']]],
  ['checkingpolicy_8',['CheckingPolicy',['../structorm_1_1query_1_1detail_1_1compiled_1_1CheckingPolicy.html',1,'orm::query::detail::compiled']]],
  ['ci_20compiler_20matrix_9',['CI Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'']]],
  ['ci_20integration_10',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_11',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['ci_20status_12',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['clang_13',['Clang',['../md_docs_2ci-compiler-matrix.html#autotoc_md31',1,'']]],
  ['cmake_20consumers_20and_20installation_14',['CMake consumers and installation',['../md_docs_2modules.html#autotoc_md65',1,'']]],
  ['cmake_20installation_15',['Native CMake installation',['../md_docs_2packaging.html#autotoc_md72',1,'']]],
  ['cmake_20presets_16',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['collection_20predicates_17',['Collection predicates',['../md_docs_2query.html#autotoc_md83',1,'']]],
  ['collection_20relations_18',['Collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md61',1,'Collection relations']]],
  ['collection_20wrappers_19',['Collection wrappers',['../md_docs_2relations.html#autotoc_md95',1,'']]],
  ['collectionexpression_20',['CollectionExpression',['../structorm_1_1query_1_1detail_1_1CollectionExpression.html',1,'orm::query::detail']]],
  ['collectionmeta_21',['CollectionMeta',['../structorm_1_1query_1_1detail_1_1CollectionMeta.html',1,'orm::query::detail']]],
  ['collectionpayload_22',['CollectionPayload',['../structorm_1_1db_1_1binding_1_1CollectionPayload.html',1,'orm::db::binding']]],
  ['collections_23',['collections',['../md_docs_2relations.html#autotoc_md102',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md81',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md101',1,'Loading collections']]],
  ['collectiontraits_24',['CollectionTraits',['../structorm_1_1query_1_1detail_1_1CollectionTraits.html',1,'orm::query::detail']]],
  ['column_25',['Column',['../classorm_1_1query_1_1detail_1_1Column.html',1,'orm::query::detail::Column'],['../classorm_1_1query_1_1detail_1_1Column.html#a5af4e1f718c7de332efc1083d46b96dc',1,'orm::query::detail::Column::Column()']]],
  ['column_20names_26',['Column names',['../md_docs_2model.html#autotoc_md57',1,'']]],
  ['column_20names_27',['Junction column names',['../md_docs_2relations.html#autotoc_md98',1,'']]],
  ['column_20names_20and_20relations_28',['Column names and relations',['../md_docs_2query.html#autotoc_md84',1,'']]],
  ['columnfor_29',['ColumnFor',['../conceptorm_1_1query_1_1detail_1_1ColumnFor.html',1,'orm::query::detail']]],
  ['columnname_30',['ColumnName',['../structorm_1_1model_1_1ColumnName.html',1,'orm::model']]],
  ['columnnames_31',['ColumnNames',['../structorm_1_1model_1_1ColumnNames.html',1,'orm::model']]],
  ['columntraits_32',['ColumnTraits',['../structorm_1_1query_1_1detail_1_1ColumnTraits.html',1,'orm::query::detail']]],
  ['columntraits_3c_20member_20_3e_33',['ColumnTraits&lt; Member &gt;',['../structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Member_01_4.html',1,'orm::query::detail']]],
  ['columntraits_3c_20members_2e_2e_2e_20_3e_34',['ColumnTraits&lt; Members... &gt;',['../structorm_1_1query_1_1detail_1_1ColumnTraits.html',1,'orm::query::detail']]],
  ['columntraits_3c_20relation_2c_20member_20_3e_35',['ColumnTraits&lt; Relation, Member &gt;',['../structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Relation_00_01Member_01_4.html',1,'orm::query::detail']]],
  ['columnview_36',['ColumnView',['../structorm_1_1model_1_1ColumnView.html',1,'orm::model']]],
  ['commandgenerator_37',['CommandGenerator',['../classorm_1_1db_1_1CommandGenerator.html',1,'orm::db']]],
  ['commandgeneratorfactory_38',['CommandGeneratorFactory',['../classorm_1_1db_1_1CommandGeneratorFactory.html',1,'orm::db']]],
  ['committransaction_39',['commitTransaction',['../classorm_1_1DatabaseCore.html#ab867a949d0b37aeb452955c28dcee72c',1,'orm::DatabaseCore']]],
  ['common_20mistakes_40',['Common mistakes',['../md_docs_2relations.html#autotoc_md106',1,'']]],
  ['comparisonexpression_41',['ComparisonExpression',['../structorm_1_1query_1_1detail_1_1ComparisonExpression.html',1,'orm::query::detail']]],
  ['comparisonmeta_42',['ComparisonMeta',['../structorm_1_1query_1_1detail_1_1ComparisonMeta.html',1,'orm::query::detail']]],
  ['compatibility_20at_20a_20glance_43',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['compiledstatement_44',['CompiledStatement',['../structorm_1_1query_1_1detail_1_1compiled_1_1CompiledStatement.html',1,'orm::query::detail::compiled']]],
  ['compiler_20matrix_45',['Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['compiler_20versions_46',['Compiler Versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'Adding New Compiler Versions'],['../md_docs_2ci-compiler-matrix.html#autotoc_md29',1,'Tested Compiler Versions']]],
  ['conancenter_20after_20acceptance_47',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md68',1,'']]],
  ['concrete_20extension_20points_48',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_49',['Build configuration',['../md_docs_2backends.html#autotoc_md24',1,'']]],
  ['configuration_20and_20macro_20policy_50',['Build configuration and macro policy',['../index.html#autotoc_md50',1,'']]],
  ['conformance_20tests_51',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_52',['Connect',['../md_docs_2database.html#autotoc_md38',1,'']]],
  ['connect_53',['connect',['../classorm_1_1DatabaseCore.html#a4fd6a2b78915e33468c808e3e14f8319',1,'orm::DatabaseCore::connect(const std::string &amp;connectionString) -&gt; void'],['../classorm_1_1DatabaseCore.html#a9089cbdeb18b77659c89517f7df8c14e',1,'orm::DatabaseCore::connect(db::BackendType requestedBackend, const std::string &amp;connectionString) -&gt; void']]],
  ['consistency_54',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md104',1,'']]],
  ['consume_20from_20conancenter_20after_20acceptance_55',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md68',1,'']]],
  ['consume_20from_20vcpkg_20after_20acceptance_56',['Consume from vcpkg after acceptance',['../md_docs_2packaging.html#autotoc_md67',1,'']]],
  ['consumers_20and_20installation_57',['CMake consumers and installation',['../md_docs_2modules.html#autotoc_md65',1,'']]],
  ['containertraits_58',['ContainerTraits',['../structorm_1_1query_1_1detail_1_1ContainerTraits.html',1,'orm::query::detail']]],
  ['containertraits_3c_20std_3a_3aarray_3c_20t_2c_20n_20_3e_20_3e_59',['ContainerTraits&lt; std::array&lt; T, N &gt; &gt;',['../structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1array_3_01T_00_01N_01_4_01_4.html',1,'orm::query::detail']]],
  ['containertraits_3c_20std_3a_3ainitializer_5flist_3c_20t_20_3e_20_3e_60',['ContainerTraits&lt; std::initializer_list&lt; T &gt; &gt;',['../structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1initializer__list_3_01T_01_4_01_4.html',1,'orm::query::detail']]],
  ['containertraits_3c_20std_3a_3avector_3c_20t_2c_20a_20_3e_20_3e_61',['ContainerTraits&lt; std::vector&lt; T, A &gt; &gt;',['../structorm_1_1query_1_1detail_1_1ContainerTraits_3_01std_1_1vector_3_01T_00_01A_01_4_01_4.html',1,'orm::query::detail']]],
  ['contract_62',['Contract',['../md_docs_2partial-result-queries.html#autotoc_md74',1,'']]],
  ['contract_63',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['conversion_64',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md110',1,'']]],
  ['conversionerror_65',['ConversionError',['../classorm_1_1db_1_1binding_1_1ConversionError.html',1,'orm::db::binding']]],
  ['coverage_20policy_66',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['create_20a_20model_67',['Create a model',['../md_docs_2model.html#autotoc_md52',1,'']]],
  ['create_20and_20delete_20relation_20tables_68',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['create_20table_69',['Create table',['../md_docs_2database.html#autotoc_md40',1,'']]],
  ['createrelationtablesimpl_70',['createRelationTablesImpl',['../classorm_1_1DatabaseCore.html#ac278df3368bf370aedaa35d1da0f789a',1,'orm::DatabaseCore']]],
  ['createtablecommand_71',['CreateTableCommand',['../classorm_1_1db_1_1commands_1_1CreateTableCommand.html',1,'orm::db::commands']]],
  ['createtableimpl_72',['createTableImpl',['../classorm_1_1DatabaseCore.html#ad7cb162365dcbcfc96a39a6146d5958f',1,'orm::DatabaseCore']]],
  ['current_20limitations_73',['Current limitations',['../md_docs_2model.html#autotoc_md62',1,'']]]
];
