var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['c_2020_20modules_1',['C++20 modules',['../md_docs_2modules.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_2',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_3',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['capabilities_20versus_20dialect_4',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_5',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['changing_20the_20release_6',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md70',1,'']]],
  ['checkingpolicy_7',['CheckingPolicy',['../structorm_1_1query_1_1detail_1_1compiled_1_1CheckingPolicy.html',1,'orm::query::detail::compiled']]],
  ['ci_20compiler_20matrix_8',['CI Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'']]],
  ['ci_20integration_9',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_10',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['ci_20status_11',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['clang_12',['Clang',['../md_docs_2ci-compiler-matrix.html#autotoc_md31',1,'']]],
  ['cmake_20consumers_20and_20installation_13',['CMake consumers and installation',['../md_docs_2modules.html#autotoc_md65',1,'']]],
  ['cmake_20installation_14',['Native CMake installation',['../md_docs_2packaging.html#autotoc_md72',1,'']]],
  ['cmake_20presets_15',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['collection_20predicates_16',['Collection predicates',['../md_docs_2query.html#autotoc_md83',1,'']]],
  ['collection_20relations_17',['collection relations',['../md_docs_2model.html#autotoc_md61',1,'Collection relations'],['../md_docs_2relations.html',1,'Collection relations']]],
  ['collection_20wrappers_18',['Collection wrappers',['../md_docs_2relations.html#autotoc_md95',1,'']]],
  ['collectionexpression_19',['CollectionExpression',['../structorm_1_1query_1_1detail_1_1CollectionExpression.html',1,'orm::query::detail']]],
  ['collectionpayload_20',['CollectionPayload',['../structorm_1_1db_1_1binding_1_1CollectionPayload.html',1,'orm::db::binding']]],
  ['collections_21',['collections',['../md_docs_2relations.html#autotoc_md102',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md81',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md101',1,'Loading collections']]],
  ['collectiontraits_22',['CollectionTraits',['../structorm_1_1query_1_1detail_1_1CollectionTraits.html',1,'orm::query::detail']]],
  ['column_23',['column',['../classorm_1_1query_1_1detail_1_1Column.html',1,'orm::query::detail::Column'],['../classorm_1_1query_1_1detail_1_1Column.html#a5af4e1f718c7de332efc1083d46b96dc',1,'orm::query::detail::Column::Column()']]],
  ['column_20names_24',['column names',['../md_docs_2model.html#autotoc_md57',1,'Column names'],['../md_docs_2relations.html#autotoc_md98',1,'Junction column names']]],
  ['column_20names_20and_20relations_25',['Column names and relations',['../md_docs_2query.html#autotoc_md84',1,'']]],
  ['columnname_26',['ColumnName',['../structorm_1_1model_1_1ColumnName.html',1,'orm::model']]],
  ['columnnames_27',['ColumnNames',['../structorm_1_1model_1_1ColumnNames.html',1,'orm::model']]],
  ['columntraits_28',['ColumnTraits',['../structorm_1_1query_1_1detail_1_1ColumnTraits.html',1,'orm::query::detail']]],
  ['columntraits_3c_20member_20_3e_29',['ColumnTraits&lt; Member &gt;',['../structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Member_01_4.html',1,'orm::query::detail']]],
  ['columntraits_3c_20relation_2c_20member_20_3e_30',['ColumnTraits&lt; Relation, Member &gt;',['../structorm_1_1query_1_1detail_1_1ColumnTraits_3_01Relation_00_01Member_01_4.html',1,'orm::query::detail']]],
  ['columnview_31',['ColumnView',['../structorm_1_1model_1_1ColumnView.html',1,'orm::model']]],
  ['commandgenerator_32',['CommandGenerator',['../classorm_1_1db_1_1CommandGenerator.html',1,'orm::db']]],
  ['committransaction_33',['commitTransaction',['../classorm_1_1Database.html#a8e53db9a678a64b874158b175c02ff24',1,'orm::Database']]],
  ['common_20mistakes_34',['Common mistakes',['../md_docs_2relations.html#autotoc_md106',1,'']]],
  ['comparisonexpression_35',['ComparisonExpression',['../structorm_1_1query_1_1detail_1_1ComparisonExpression.html',1,'orm::query::detail']]],
  ['compatibility_20at_20a_20glance_36',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['compiledstatement_37',['CompiledStatement',['../structorm_1_1query_1_1detail_1_1compiled_1_1CompiledStatement.html',1,'orm::query::detail::compiled']]],
  ['compiler_20matrix_38',['compiler matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['compiler_20versions_39',['compiler versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'Adding New Compiler Versions'],['../md_docs_2ci-compiler-matrix.html#autotoc_md29',1,'Tested Compiler Versions']]],
  ['conancenter_20after_20acceptance_40',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md68',1,'']]],
  ['concrete_20extension_20points_41',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_42',['Build configuration',['../md_docs_2backends.html#autotoc_md24',1,'']]],
  ['configuration_20and_20macro_20policy_43',['Build configuration and macro policy',['../index.html#autotoc_md50',1,'']]],
  ['conformance_20tests_44',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_45',['connect',['../classorm_1_1Database.html#a838dec6f6358add79205f223cd164e04',1,'orm::Database::connect()'],['../md_docs_2database.html#autotoc_md38',1,'Connect'],['../classorm_1_1Database.html#a86f01ed300b1a8a7a74bedbf61e45fa2',1,'orm::Database::connect()']]],
  ['consistency_46',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md104',1,'']]],
  ['consume_20from_20conancenter_20after_20acceptance_47',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md68',1,'']]],
  ['consume_20from_20vcpkg_20after_20acceptance_48',['Consume from vcpkg after acceptance',['../md_docs_2packaging.html#autotoc_md67',1,'']]],
  ['consumers_20and_20installation_49',['CMake consumers and installation',['../md_docs_2modules.html#autotoc_md65',1,'']]],
  ['contract_50',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2partial-result-queries.html#autotoc_md74',1,'Contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['conversion_51',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md110',1,'']]],
  ['conversionerror_52',['ConversionError',['../classorm_1_1db_1_1binding_1_1ConversionError.html',1,'orm::db::binding']]],
  ['coverage_20policy_53',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['create_20a_20model_54',['Create a model',['../md_docs_2model.html#autotoc_md52',1,'']]],
  ['create_20and_20delete_20relation_20tables_55',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['create_20table_56',['Create table',['../md_docs_2database.html#autotoc_md40',1,'']]],
  ['createtablecommand_57',['CreateTableCommand',['../classorm_1_1db_1_1commands_1_1CreateTableCommand.html',1,'orm::db::commands']]],
  ['current_20limitations_58',['Current limitations',['../md_docs_2model.html#autotoc_md62',1,'']]]
];
