var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_1',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_2',['Capabilities and errors',['../md_docs_2database.html#autotoc_md29',1,'']]],
  ['capabilities_20versus_20dialect_3',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_4',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['ci_20integration_5',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_6',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['collection_20predicates_7',['Collection predicates',['../md_docs_2query.html#autotoc_md60',1,'']]],
  ['collection_20relations_8',['Collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md48',1,'Collection relations']]],
  ['collection_20wrappers_9',['Collection wrappers',['../md_docs_2relations.html#autotoc_md72',1,'']]],
  ['collections_10',['collections',['../md_docs_2relations.html#autotoc_md79',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md58',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md78',1,'Loading collections']]],
  ['column_20names_11',['Column names',['../md_docs_2model.html#autotoc_md44',1,'']]],
  ['column_20names_12',['Junction column names',['../md_docs_2relations.html#autotoc_md75',1,'']]],
  ['column_20names_20and_20relations_13',['Column names and relations',['../md_docs_2query.html#autotoc_md61',1,'']]],
  ['committransaction_14',['commitTransaction',['../classorm_1_1Database.html#a8e53db9a678a64b874158b175c02ff24',1,'orm::Database']]],
  ['common_20mistakes_15',['Common mistakes',['../md_docs_2relations.html#autotoc_md83',1,'']]],
  ['compatibility_20at_20a_20glance_16',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['concrete_20extension_20points_17',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_18',['Build configuration',['../md_docs_2backends.html#autotoc_md24',1,'']]],
  ['conformance_20tests_19',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_20',['Connect',['../md_docs_2database.html#autotoc_md28',1,'']]],
  ['connect_21',['connect',['../classorm_1_1Database.html#a86f01ed300b1a8a7a74bedbf61e45fa2',1,'orm::Database::connect(const std::string &amp;connectionString) -&gt; void'],['../classorm_1_1Database.html#a838dec6f6358add79205f223cd164e04',1,'orm::Database::connect(db::BackendType requestedBackend, const std::string &amp;connectionString) -&gt; void']]],
  ['consistency_22',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md81',1,'']]],
  ['contract_23',['Contract',['../md_docs_2partial-result-queries.html#autotoc_md51',1,'']]],
  ['contract_24',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['create_20a_20model_25',['Create a model',['../md_docs_2model.html#autotoc_md40',1,'']]],
  ['create_20and_20delete_20relation_20tables_26',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md32',1,'']]],
  ['create_20table_27',['Create table',['../md_docs_2database.html#autotoc_md30',1,'']]],
  ['createrelationtables_28',['createRelationTables',['../classorm_1_1Database.html#a56193616d588084845aeef03a2c44615',1,'orm::Database']]],
  ['createtable_29',['createTable',['../classorm_1_1Database.html#a5dc553baa29a3ec7fd46b81e412ffa5d',1,'orm::Database']]],
  ['current_20limitations_30',['Current limitations',['../md_docs_2model.html#autotoc_md49',1,'Current limitations'],['../md_docs_2query.html#autotoc_md70',1,'Current limitations']]]
];
