var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['c_2020_20modules_1',['C++20 modules',['../md_docs_2modules.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_2',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_3',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['capabilities_20versus_20dialect_4',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_5',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['changing_20the_20release_6',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md70',1,'']]],
  ['ci_20compiler_20matrix_7',['CI Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'']]],
  ['ci_20integration_8',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_9',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['ci_20status_10',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['clang_11',['Clang',['../md_docs_2ci-compiler-matrix.html#autotoc_md31',1,'']]],
  ['cmake_20consumers_20and_20installation_12',['CMake consumers and installation',['../md_docs_2modules.html#autotoc_md65',1,'']]],
  ['cmake_20installation_13',['Native CMake installation',['../md_docs_2packaging.html#autotoc_md72',1,'']]],
  ['cmake_20presets_14',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['collection_20predicates_15',['Collection predicates',['../md_docs_2query.html#autotoc_md83',1,'']]],
  ['collection_20relations_16',['collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md61',1,'Collection relations']]],
  ['collection_20wrappers_17',['Collection wrappers',['../md_docs_2relations.html#autotoc_md95',1,'']]],
  ['collections_18',['collections',['../md_docs_2relations.html#autotoc_md102',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md81',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md101',1,'Loading collections']]],
  ['column_20names_19',['column names',['../md_docs_2model.html#autotoc_md57',1,'Column names'],['../md_docs_2relations.html#autotoc_md98',1,'Junction column names']]],
  ['column_20names_20and_20relations_20',['Column names and relations',['../md_docs_2query.html#autotoc_md84',1,'']]],
  ['common_20mistakes_21',['Common mistakes',['../md_docs_2relations.html#autotoc_md106',1,'']]],
  ['compatibility_20at_20a_20glance_22',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['compiler_20matrix_23',['compiler matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['compiler_20versions_24',['compiler versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'Adding New Compiler Versions'],['../md_docs_2ci-compiler-matrix.html#autotoc_md29',1,'Tested Compiler Versions']]],
  ['conancenter_20after_20acceptance_25',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md68',1,'']]],
  ['concrete_20extension_20points_26',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_27',['Build configuration',['../md_docs_2backends.html#autotoc_md24',1,'']]],
  ['configuration_20and_20macro_20policy_28',['Build configuration and macro policy',['../index.html#autotoc_md50',1,'']]],
  ['conformance_20tests_29',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_30',['Connect',['../md_docs_2database.html#autotoc_md38',1,'']]],
  ['consistency_31',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md104',1,'']]],
  ['consume_20from_20conancenter_20after_20acceptance_32',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md68',1,'']]],
  ['consume_20from_20vcpkg_20after_20acceptance_33',['Consume from vcpkg after acceptance',['../md_docs_2packaging.html#autotoc_md67',1,'']]],
  ['consumers_20and_20installation_34',['CMake consumers and installation',['../md_docs_2modules.html#autotoc_md65',1,'']]],
  ['contract_35',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2partial-result-queries.html#autotoc_md74',1,'Contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['conversion_36',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md110',1,'']]],
  ['coverage_20policy_37',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['create_20a_20model_38',['Create a model',['../md_docs_2model.html#autotoc_md52',1,'']]],
  ['create_20and_20delete_20relation_20tables_39',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['create_20table_40',['Create table',['../md_docs_2database.html#autotoc_md40',1,'']]],
  ['current_20limitations_41',['Current limitations',['../md_docs_2model.html#autotoc_md62',1,'']]]
];
