var searchData=
[
  ['objectfieldfromprojectionvalues_0',['ObjectFieldFromProjectionValues',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues.html',1,'orm::db::binding']]],
  ['objectfieldfromprojectionvalues_3c_20resultfield_20_3e_1',['ObjectFieldFromProjectionValues&lt; ResultField &gt;',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01ResultField_01_4.html',1,'orm::db::binding']]],
  ['objectfieldfromprojectionvalues_3c_20std_3a_3aoptional_3c_20resultfield_20_3e_20_3e_2',['ObjectFieldFromProjectionValues&lt; std::optional&lt; ResultField &gt; &gt;',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValues_3_01std_1_1optional_3_01ResultField_01_4_01_4.html',1,'orm::db::binding']]],
  ['objectfieldfromprojectionvalueswithcast_3',['ObjectFieldFromProjectionValuesWithCast',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html',1,'orm::db::binding']]],
  ['objectfieldfromprojectionvalueswithcast_3c_20resultfield_2c_20double_20_3e_4',['ObjectFieldFromProjectionValuesWithCast&lt; ResultField, double &gt;',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html',1,'orm::db::binding']]],
  ['objectfieldfromprojectionvalueswithcast_3c_20resultfield_2c_20int_20_3e_5',['ObjectFieldFromProjectionValuesWithCast&lt; ResultField, int &gt;',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html',1,'orm::db::binding']]],
  ['objectfieldfromprojectionvalueswithcast_3c_20resultfield_2c_20long_20long_20_3e_6',['ObjectFieldFromProjectionValuesWithCast&lt; ResultField, long long &gt;',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html',1,'orm::db::binding']]],
  ['objectfieldfromprojectionvalueswithcast_3c_20resultfield_2c_20unsigned_20long_20long_20_3e_7',['ObjectFieldFromProjectionValuesWithCast&lt; ResultField, unsigned long long &gt;',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromProjectionValuesWithCast.html',1,'orm::db::binding']]],
  ['objectfieldfromvalues_8',['ObjectFieldFromValues',['../structorm_1_1db_1_1binding_1_1ObjectFieldFromValues.html',1,'orm::db::binding']]],
  ['objectfieldtovalues_9',['ObjectFieldToValues',['../structorm_1_1db_1_1binding_1_1ObjectFieldToValues.html',1,'orm::db::binding']]],
  ['objects_10',['objects',['../md_docs_2database.html#autotoc_md43',1,'Insert objects'],['../md_docs_2database.html#autotoc_md45',1,'Query objects'],['../md_docs_2database.html#autotoc_md47',1,'Remove objects'],['../md_docs_2database.html#autotoc_md46',1,'Update objects']]],
  ['of_20done_11',['of done',['../md_docs_2backend-extension.html#autotoc_md9',1,'Backend Definition of Done'],['../md_docs_2backend-portability.html#autotoc_md18',1,'Definition of Done']]],
  ['offset_12',['offset',['../md_docs_2query.html#autotoc_md87',1,'Limit and offset'],['../classorm_1_1Query.html#ad277561652627e31187604dd6487fec8',1,'orm::Query::offset()']]],
  ['one_20relations_13',['One-to-one relations',['../md_docs_2model.html#autotoc_md60',1,'']]],
  ['one_20to_20many_14',['One-to-many',['../md_docs_2relations.html#autotoc_md96',1,'']]],
  ['one_20to_20one_20relations_15',['One-to-one relations',['../md_docs_2model.html#autotoc_md60',1,'']]],
  ['optional_20fields_16',['Optional fields',['../md_docs_2model.html#autotoc_md55',1,'']]],
  ['optionalrelationcollectiontraits_17',['OptionalRelationCollectionTraits',['../structorm_1_1detail_1_1OptionalRelationCollectionTraits.html',1,'orm::detail']]],
  ['optionalrelationcollectiontraits_3c_20std_3a_3aoptional_3c_20t_20_3e_20_3e_18',['OptionalRelationCollectionTraits&lt; std::optional&lt; T &gt; &gt;',['../structorm_1_1detail_1_1OptionalRelationCollectionTraits_3_01std_1_1optional_3_01T_01_4_01_4.html',1,'orm::detail']]],
  ['optionalvalue_19',['OptionalValue',['../structorm_1_1db_1_1binding_1_1OptionalValue.html',1,'orm::db::binding']]],
  ['optionalvalue_3c_20std_3a_3aoptional_3c_20t_20_3e_20_3e_20',['OptionalValue&lt; std::optional&lt; T &gt; &gt;',['../structorm_1_1db_1_1binding_1_1OptionalValue_3_01std_1_1optional_3_01T_01_4_01_4.html',1,'orm::db::binding']]],
  ['orderby_21',['orderby',['../classorm_1_1Query.html#a465a0203fde67022b95fdc578a88796a',1,'orm::Query::orderBy()'],['../structorm_1_1query_1_1detail_1_1OrderBy.html',1,'orm::query::detail::OrderBy']]],
  ['ordering_22',['Ordering',['../md_docs_2query.html#autotoc_md85',1,'']]],
  ['orhaving_23',['orHaving',['../classorm_1_1Query.html#a7fd213e9328f2d27b94aab2dbbcc2232',1,'orm::Query']]],
  ['orm_20c_24',['ORM C++',['../index.html',1,'']]],
  ['orm_3a_3adatabase_25',['Database',['../classorm_1_1Query.html#ae0f742b2920b17d9a95c91c6239abc24',1,'orm::Query']]],
  ['orm_3a_3adb_3a_3abinding_3a_3aisoneoftypes_26',['IsOneOfTypes',['../conceptorm_1_1db_1_1binding_1_1IsOneOfTypes.html',1,'orm::db::binding']]],
  ['orm_3a_3adb_3a_3abinding_3a_3aschemamodel_27',['SchemaModel',['../conceptorm_1_1db_1_1binding_1_1SchemaModel.html',1,'orm::db::binding']]],
  ['orm_3a_3adb_3a_3abinding_3a_3asociconvertabletodouble_28',['SociConvertableToDouble',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToDouble.html',1,'orm::db::binding']]],
  ['orm_3a_3adb_3a_3abinding_3a_3asociconvertabletoint_29',['SociConvertableToInt',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToInt.html',1,'orm::db::binding']]],
  ['orm_3a_3adb_3a_3abinding_3a_3asociconvertabletolonglong_30',['SociConvertableToLongLong',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToLongLong.html',1,'orm::db::binding']]],
  ['orm_3a_3adb_3a_3abinding_3a_3asociconvertabletounsignedlonglong_31',['SociConvertableToUnsignedLongLong',['../conceptorm_1_1db_1_1binding_1_1SociConvertableToUnsignedLongLong.html',1,'orm::db::binding']]],
  ['orm_3a_3adb_3a_3abinding_3a_3asocidefaultsupported_32',['SociDefaultSupported',['../conceptorm_1_1db_1_1binding_1_1SociDefaultSupported.html',1,'orm::db::binding']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aaggregateexpressiontype_33',['AggregateExpressionType',['../conceptorm_1_1query_1_1detail_1_1AggregateExpressionType.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aaggregatepredicatefor_34',['AggregatePredicateFor',['../conceptorm_1_1query_1_1detail_1_1AggregatePredicateFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aanyaggregatepredicatefor_35',['AnyAggregatePredicateFor',['../conceptorm_1_1query_1_1detail_1_1AnyAggregatePredicateFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aanypredicatefor_36',['AnyPredicateFor',['../conceptorm_1_1query_1_1detail_1_1AnyPredicateFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3acolumnfor_37',['ColumnFor',['../conceptorm_1_1query_1_1detail_1_1ColumnFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3alogicalpredicate_38',['LogicalPredicate',['../conceptorm_1_1query_1_1detail_1_1LogicalPredicate.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorderfor_39',['OrderFor',['../conceptorm_1_1query_1_1detail_1_1OrderFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fbound_40',['ORM_QUERY_BOUND',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__BOUND.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fcollection_41',['ORM_QUERY_COLLECTION',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__COLLECTION.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fmember_42',['ORM_QUERY_MEMBER',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__MEMBER.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fmodel_43',['ORM_QUERY_MODEL',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__MODEL.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fmodel_5fcolumns_44',['ORM_QUERY_MODEL_COLUMNS',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__MODEL__COLUMNS.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fmodel_5forders_45',['ORM_QUERY_MODEL_ORDERS',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__MODEL__ORDERS.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fmodel_5fprojections_46',['ORM_QUERY_MODEL_PROJECTIONS',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__MODEL__PROJECTIONS.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fmodel_5ftype_47',['ORM_QUERY_MODEL_TYPE',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__MODEL__TYPE.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fno_5fnested_5fcollection_48',['ORM_QUERY_NO_NESTED_COLLECTION',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__NO__NESTED__COLLECTION.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fnullable_49',['ORM_QUERY_NULLABLE',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__NULLABLE.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fnumeric_50',['ORM_QUERY_NUMERIC',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__NUMERIC.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5forderable_51',['ORM_QUERY_ORDERABLE',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__ORDERABLE.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fset_5fvalue_52',['ORM_QUERY_SET_VALUE',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__SET__VALUE.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fstring_53',['ORM_QUERY_STRING',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__STRING.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5funbound_5fparameter_54',['ORM_QUERY_UNBOUND_PARAMETER',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__UNBOUND__PARAMETER.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5funbound_5fparameter_5fvalue_55',['ORM_QUERY_UNBOUND_PARAMETER_VALUE',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__UNBOUND__PARAMETER__VALUE.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fvalue_56',['ORM_QUERY_VALUE',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__VALUE.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fvalue_5for_5fparameter_57',['ORM_QUERY_VALUE_OR_PARAMETER',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__VALUE__OR__PARAMETER.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aorm_5fquery_5fwrite_5fsafe_58',['ORM_QUERY_WRITE_SAFE',['../conceptorm_1_1query_1_1detail_1_1ORM__QUERY__WRITE__SAFE.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aplanaggregatepredicatefor_59',['PlanAggregatePredicateFor',['../conceptorm_1_1query_1_1detail_1_1PlanAggregatePredicateFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aplanpredicatefor_60',['PlanPredicateFor',['../conceptorm_1_1query_1_1detail_1_1PlanPredicateFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3apredicateexpression_61',['PredicateExpression',['../conceptorm_1_1query_1_1detail_1_1PredicateExpression.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3apredicatefor_62',['PredicateFor',['../conceptorm_1_1query_1_1detail_1_1PredicateFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aprojectionfor_63',['ProjectionFor',['../conceptorm_1_1query_1_1detail_1_1ProjectionFor.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3aprojectionsourceexpression_64',['ProjectionSourceExpression',['../conceptorm_1_1query_1_1detail_1_1ProjectionSourceExpression.html',1,'orm::query::detail']]],
  ['orm_3a_3aquery_3a_3adetail_3a_3astaticplantype_65',['StaticPlanType',['../conceptorm_1_1query_1_1detail_1_1StaticPlanType.html',1,'orm::query::detail']]],
  ['orwhere_66',['orWhere',['../classorm_1_1Query.html#a1280c34a4025e89600e25654c9513808',1,'orm::Query']]]
];
