var searchData=
[
  ['macro_20policy_0',['Build configuration and macro policy',['../index.html#autotoc_md50',1,'']]],
  ['maintainer_20setup_20and_20publishing_1',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md69',1,'']]],
  ['managers_20and_20releases_2',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['many_3',['many',['../md_docs_2relations.html#autotoc_md97',1,'Many-to-many'],['../md_docs_2relations.html#autotoc_md96',1,'One-to-many']]],
  ['many_20to_20many_4',['Many-to-many',['../md_docs_2relations.html#autotoc_md97',1,'']]],
  ['manytomany_5',['ManyToMany',['../classorm_1_1ManyToMany.html',1,'orm']]],
  ['manytomanydescriptor_6',['ManyToManyDescriptor',['../structorm_1_1ManyToManyDescriptor.html',1,'orm']]],
  ['mappings_7',['Validation and unsupported mappings',['../md_docs_2relations.html#autotoc_md105',1,'']]],
  ['matrix_8',['Matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['matrix_9',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['maxunsignedlonglong_10',['maxUnsignedLongLong',['../structorm_1_1db_1_1BackendValueLimits.html#a509fe1ba15b48a040a66ae0836c30a3c',1,'orm::db::BackendValueLimits']]],
  ['memberpointertraits_11',['MemberPointerTraits',['../structorm_1_1model_1_1detail_1_1MemberPointerTraits.html',1,'orm::model::detail']]],
  ['memberpointertraits_3c_20value_20owner_3a_3a_2a_20_3e_12',['MemberPointerTraits&lt; Value Owner::* &gt;',['../structorm_1_1model_1_1detail_1_1MemberPointerTraits_3_01Value_01Owner_1_1_5_01_4.html',1,'orm::model::detail']]],
  ['migrating_20an_20existing_20schema_13',['Migrating an existing schema',['../md_docs_2relations.html#autotoc_md107',1,'']]],
  ['minimum_20ci_20matrix_14',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['mistakes_15',['Common mistakes',['../md_docs_2relations.html#autotoc_md106',1,'']]],
  ['model_16',['Model',['../md_docs_2model.html',1,'']]],
  ['model_17',['model',['../md_docs_2model.html#autotoc_md52',1,'Create a model'],['../md_docs_2backend-portability.html#autotoc_md16',1,'Verification model']]],
  ['model_20grouping_20and_20having_18',['Full-model grouping and HAVING',['../md_docs_2query.html#autotoc_md90',1,'']]],
  ['modeldataview_19',['ModelDataView',['../structorm_1_1model_1_1ModelDataView.html',1,'orm::model']]],
  ['modelview_20',['ModelView',['../structorm_1_1model_1_1ModelView.html',1,'orm::model']]],
  ['modules_21',['C++20 modules',['../md_docs_2modules.html',1,'']]],
  ['msvc_22',['MSVC',['../md_docs_2ci-compiler-matrix.html#autotoc_md32',1,'']]],
  ['mutationcapabilities_23',['MutationCapabilities',['../structorm_1_1db_1_1MutationCapabilities.html',1,'orm::db']]]
];
