var searchData=
[
  ['schema_0',['schema',['../md_docs_2relations.html#autotoc_md107',1,'Migrating an existing schema'],['../structorm_1_1model_1_1Schema.html',1,'orm::model::Schema&lt; Models &gt;'],['../md_docs_2model.html#autotoc_md53',1,'Static schema']]],
  ['schema_20lifecycle_1',['Schema lifecycle',['../md_docs_2relations.html#autotoc_md99',1,'']]],
  ['schemacapabilities_2',['SchemaCapabilities',['../structorm_1_1db_1_1SchemaCapabilities.html',1,'orm::db']]],
  ['schemaview_3',['SchemaView',['../structorm_1_1model_1_1SchemaView.html',1,'orm::model']]],
  ['select_4',['Build select',['../md_docs_2query.html#autotoc_md80',1,'']]],
  ['selectcommand_5',['SelectCommand',['../classorm_1_1db_1_1commands_1_1SelectCommand.html',1,'orm::db::commands']]],
  ['selectspec_6',['SelectSpec',['../structorm_1_1query_1_1detail_1_1SelectSpec.html',1,'orm::query::detail']]],
  ['setup_20and_20publishing_7',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md69',1,'']]],
  ['shapes_20and_20explicit_20conversion_8',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md110',1,'']]],
  ['soci_9',['Binding and SOCI',['../md_docs_2backend-portability.html#autotoc_md14',1,'']]],
  ['soci_20boundary_10',['SOCI boundary',['../md_docs_2backend-extension.html#autotoc_md4',1,'']]],
  ['sql_11',['sql',['../md_docs_2backend-portability.html#autotoc_md15',1,'Raw SQL'],['../md_docs_2backend-extension.html#autotoc_md5',1,'Raw SQL']]],
  ['sql_20fragments_12',['Raw SQL fragments',['../md_docs_2query.html#autotoc_md88',1,'']]],
  ['sql_20portability_13',['Raw SQL portability',['../md_docs_2backends.html#autotoc_md26',1,'']]],
  ['sqlassignment_14',['SqlAssignment',['../structorm_1_1db_1_1detail_1_1SqlAssignment.html',1,'orm::db::detail']]],
  ['sqlbindingdescriptor_15',['SqlBindingDescriptor',['../structorm_1_1db_1_1detail_1_1SqlBindingDescriptor.html',1,'orm::db::detail']]],
  ['sqlcolumninfo_16',['SqlColumnInfo',['../structorm_1_1db_1_1detail_1_1SqlColumnInfo.html',1,'orm::db::detail']]],
  ['sqlite_17',['SQLite',['../md_docs_2backends.html#autotoc_md22',1,'']]],
  ['sqlnode_18',['SqlNode',['../structorm_1_1db_1_1detail_1_1SqlNode.html',1,'orm::db::detail']]],
  ['sqlorder_19',['SqlOrder',['../structorm_1_1db_1_1detail_1_1SqlOrder.html',1,'orm::db::detail']]],
  ['sqlprogram_20',['SqlProgram',['../structorm_1_1db_1_1detail_1_1SqlProgram.html',1,'orm::db::detail']]],
  ['sqlprojection_21',['SqlProjection',['../structorm_1_1db_1_1detail_1_1SqlProjection.html',1,'orm::db::detail']]],
  ['sqlqueryview_22',['SqlQueryView',['../structorm_1_1db_1_1detail_1_1SqlQueryView.html',1,'orm::db::detail']]],
  ['sqlrenderscope_23',['SqlRenderScope',['../structorm_1_1db_1_1detail_1_1SqlRenderScope.html',1,'orm::db::detail']]],
  ['sqlsource_24',['SqlSource',['../structorm_1_1db_1_1detail_1_1SqlSource.html',1,'orm::db::detail']]],
  ['statement_25',['Statement',['../structorm_1_1db_1_1Statement.html',1,'orm::db']]],
  ['statementparameter_26',['StatementParameter',['../structorm_1_1db_1_1StatementParameter.html',1,'orm::db']]],
  ['statementview_27',['StatementView',['../structorm_1_1db_1_1StatementView.html',1,'orm::db']]],
  ['static_20query_20plans_28',['Static query plans',['../md_docs_2static-queries.html',1,'']]],
  ['static_20schema_29',['Static schema',['../md_docs_2model.html#autotoc_md53',1,'']]],
  ['staticmodel_30',['StaticModel',['../structorm_1_1model_1_1StaticModel.html',1,'orm::model']]],
  ['staticoptionaltraits_31',['StaticOptionalTraits',['../structorm_1_1model_1_1detail_1_1StaticOptionalTraits.html',1,'orm::model::detail']]],
  ['staticoptionaltraits_3c_20std_3a_3aoptional_3c_20t_20_3e_20_3e_32',['StaticOptionalTraits&lt; std::optional&lt; T &gt; &gt;',['../structorm_1_1model_1_1detail_1_1StaticOptionalTraits_3_01std_1_1optional_3_01T_01_4_01_4.html',1,'orm::model::detail']]],
  ['staticplan_33',['StaticPlan',['../classorm_1_1query_1_1StaticPlan.html',1,'orm::query']]],
  ['staticschematraits_34',['StaticSchemaTraits',['../structorm_1_1model_1_1detail_1_1StaticSchemaTraits.html',1,'orm::model::detail']]],
  ['staticschematraits_3c_20schema_3c_20models_2e_2e_2e_20_3e_20_3e_35',['StaticSchemaTraits&lt; Schema&lt; Models... &gt; &gt;',['../structorm_1_1model_1_1detail_1_1StaticSchemaTraits_3_01Schema_3_01Models_8_8_8_01_4_01_4.html',1,'orm::model::detail']]],
  ['staticsqlpolicy_36',['StaticSqlPolicy',['../structorm_1_1db_1_1detail_1_1StaticSqlPolicy.html',1,'orm::db::detail']]],
  ['status_37',['status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'CI Status'],['../md_docs_2backends.html#autotoc_md20',1,'Support status']]],
  ['support_20status_38',['Support status',['../md_docs_2backends.html#autotoc_md20',1,'']]],
  ['supported_20field_20types_39',['Supported field types',['../md_docs_2model.html#autotoc_md54',1,'']]]
];
