var searchData=
[
  ['maintainer_20setup_20and_20publishing_0',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md79',1,'']]],
  ['make_20null_20and_20writes_20explicit_1',['Make NULL and writes explicit',['../md_docs_2migration-typed-queries.html#autotoc_md62',1,'']]],
  ['managers_20and_20releases_2',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['many_3',['many',['../md_docs_2relations.html#autotoc_md107',1,'Many-to-many'],['../md_docs_2relations.html#autotoc_md106',1,'One-to-many']]],
  ['many_20to_20many_4',['Many-to-many',['../md_docs_2relations.html#autotoc_md107',1,'']]],
  ['manytomany_5',['ManyToMany',['../classorm_1_1ManyToMany.html',1,'orm']]],
  ['manytomanydescriptor_6',['ManyToManyDescriptor',['../structorm_1_1ManyToManyDescriptor.html',1,'orm']]],
  ['mappings_7',['mappings',['../md_docs_2migration-static-schema.html#autotoc_md54',1,'3. Convert collection mappings'],['../md_docs_2relations.html#autotoc_md115',1,'Validation and unsupported mappings']]],
  ['mappings_20and_20static_20schemas_8',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['matrix_9',['Matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['matrix_10',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['migrate_20query_20fields_20and_20relations_11',['5. Migrate query fields and relations',['../md_docs_2migration-static-schema.html#autotoc_md56',1,'']]],
  ['migrating_20an_20existing_20schema_12',['Migrating an existing schema',['../md_docs_2relations.html#autotoc_md117',1,'']]],
  ['migrating_20queries_20to_200_203_13',['Migrating queries to 0.3',['../md_docs_2migration-static-queries.html',1,'']]],
  ['migrating_20to_20compile_20time_20mappings_20and_20static_20schemas_14',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['migrating_20to_20typed_20queries_20in_200_202_15',['Migrating to typed queries in 0.2',['../md_docs_2migration-typed-queries.html',1,'']]],
  ['migration_20summary_16',['Migration summary',['../md_docs_2migration-static-schema.html#autotoc_md51',1,'']]],
  ['minimum_20ci_20matrix_17',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['mistakes_18',['Common mistakes',['../md_docs_2relations.html#autotoc_md116',1,'']]],
  ['model_19',['Model',['../md_docs_2model.html',1,'']]],
  ['model_20',['model',['../md_docs_2model.html#autotoc_md65',1,'Create a model'],['../md_docs_2backend-portability.html#autotoc_md16',1,'Verification model']]],
  ['model_20configuration_21',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md53',1,'']]],
  ['model_20grouping_20and_20having_22',['Full-model grouping and HAVING',['../md_docs_2query.html#autotoc_md100',1,'']]],
  ['models_20reflectable_23',['1. Keep models reflectable',['../md_docs_2migration-static-schema.html#autotoc_md52',1,'']]],
  ['msvc_24',['MSVC',['../md_docs_2ci-compiler-matrix.html#autotoc_md32',1,'']]]
];
