var searchData=
[
  ['package_20managers_20and_20releases_0',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['package_20verification_1',['Local package verification',['../md_docs_2packaging.html#autotoc_md85',1,'']]],
  ['partial_20result_20queries_2',['Partial result queries',['../md_docs_2partial-result-queries.html',1,'Partial-result queries'],['../md_docs_2query.html#autotoc_md103',1,'Partial-result queries']]],
  ['plans_3',['Static query plans',['../md_docs_2static-queries.html',1,'']]],
  ['points_4',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['policy_5',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['policy_20and_20checks_6',['Policy and checks',['../md_docs_2migration-macro-free.html#autotoc_md52',1,'']]],
  ['portability_7',['portability',['../md_docs_2backend-portability.html',1,'Backend portability'],['../md_docs_2backends.html#autotoc_md26',1,'Raw SQL portability']]],
  ['portability_20layers_8',['Portability layers',['../md_docs_2backend-portability.html#autotoc_md11',1,'']]],
  ['portable_20behavior_9',['Portable behavior',['../md_docs_2backend-portability.html#autotoc_md12',1,'']]],
  ['postgresql_10',['PostgreSQL',['../md_docs_2backends.html#autotoc_md23',1,'']]],
  ['postgresql_20compiler_20matrix_11',['PostgreSQL Compiler Matrix',['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'']]],
  ['predicates_12',['predicates',['../md_docs_2query.html#autotoc_md97',1,'Collection predicates'],['../md_docs_2query.html#autotoc_md96',1,'Where predicates'],['../md_docs_2query.html#autotoc_md106',1,'Write predicates']]],
  ['preserve_20their_20entire_20type_20range_13',['Use values that preserve their entire type range',['../md_docs_2migration-typed-queries.html#autotoc_md65',1,'']]],
  ['presets_14',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['primary_20key_15',['Primary key',['../md_docs_2model.html#autotoc_md75',1,'']]],
  ['primary_20key_16',['Auto-increment primary key',['../md_docs_2model.html#autotoc_md76',1,'']]],
  ['projection_20queries_17',['Aggregate projection queries',['../md_docs_2query.html#autotoc_md105',1,'']]],
  ['projectionquery_18',['ProjectionQuery',['../classorm_1_1ProjectionQuery.html',1,'orm']]],
  ['projectionresultfield_19',['ProjectionResultField',['../structorm_1_1detail_1_1ProjectionResultField.html',1,'orm::detail']]],
  ['projections_20and_20writes_20',['Projections and writes',['../md_docs_2static-queries.html#autotoc_md123',1,'']]],
  ['publishing_21',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md83',1,'']]]
];
