var searchData=
[
  ['macros_0',['Backend configuration without macros',['../md_docs_2migration-macro-free.html',1,'']]],
  ['maintainer_20setup_20and_20publishing_1',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md83',1,'']]],
  ['make_20null_20and_20writes_20explicit_2',['Make NULL and writes explicit',['../md_docs_2migration-typed-queries.html#autotoc_md66',1,'']]],
  ['managers_20and_20releases_3',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['many_4',['many',['../md_docs_2relations.html#autotoc_md111',1,'Many-to-many'],['../md_docs_2relations.html#autotoc_md110',1,'One-to-many']]],
  ['many_20to_20many_5',['Many-to-many',['../md_docs_2relations.html#autotoc_md111',1,'']]],
  ['manytomany_6',['ManyToMany',['../classorm_1_1ManyToMany.html',1,'orm']]],
  ['manytomanydescriptor_7',['ManyToManyDescriptor',['../structorm_1_1ManyToManyDescriptor.html',1,'orm']]],
  ['mappings_8',['mappings',['../md_docs_2migration-static-schema.html#autotoc_md58',1,'3. Convert collection mappings'],['../md_docs_2relations.html#autotoc_md119',1,'Validation and unsupported mappings']]],
  ['mappings_20and_20static_20schemas_9',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['matrix_10',['Matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['matrix_11',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['migrate_20query_20fields_20and_20relations_12',['5. Migrate query fields and relations',['../md_docs_2migration-static-schema.html#autotoc_md60',1,'']]],
  ['migrating_20an_20existing_20schema_13',['Migrating an existing schema',['../md_docs_2relations.html#autotoc_md121',1,'']]],
  ['migrating_20queries_20to_200_203_14',['Migrating queries to 0.3',['../md_docs_2migration-static-queries.html',1,'']]],
  ['migrating_20to_20compile_20time_20mappings_20and_20static_20schemas_15',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['migrating_20to_20typed_20queries_20in_200_202_16',['Migrating to typed queries in 0.2',['../md_docs_2migration-typed-queries.html',1,'']]],
  ['migration_20summary_17',['Migration summary',['../md_docs_2migration-static-schema.html#autotoc_md55',1,'']]],
  ['minimum_20ci_20matrix_18',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['mistakes_19',['Common mistakes',['../md_docs_2relations.html#autotoc_md120',1,'']]],
  ['model_20',['Model',['../md_docs_2model.html',1,'']]],
  ['model_21',['model',['../md_docs_2model.html#autotoc_md69',1,'Create a model'],['../md_docs_2backend-portability.html#autotoc_md16',1,'Verification model']]],
  ['model_20configuration_22',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md57',1,'']]],
  ['model_20grouping_20and_20having_23',['Full-model grouping and HAVING',['../md_docs_2query.html#autotoc_md104',1,'']]],
  ['models_20reflectable_24',['1. Keep models reflectable',['../md_docs_2migration-static-schema.html#autotoc_md56',1,'']]],
  ['msvc_25',['MSVC',['../md_docs_2ci-compiler-matrix.html#autotoc_md32',1,'']]]
];
