var searchData=
[
  ['backend_20definition_20of_20done_0',['Backend Definition of Done',['../md_docs_2backend-extension.html#autotoc_md9',1,'']]],
  ['backend_20extension_20contract_1',['Backend extension contract',['../md_docs_2backend-extension.html',1,'']]],
  ['backend_20portability_2',['Backend portability',['../md_docs_2backend-portability.html',1,'']]],
  ['backend_20responsibilities_3',['Required backend responsibilities',['../md_docs_2backend-extension.html#autotoc_md2',1,'']]],
  ['backendcapabilities_4',['BackendCapabilities',['../structorm_1_1db_1_1BackendCapabilities.html',1,'orm::db']]],
  ['backendprovider_5',['BackendProvider',['../classorm_1_1db_1_1BackendProvider.html',1,'orm::db']]],
  ['backendruntime_6',['BackendRuntime',['../classorm_1_1db_1_1BackendRuntime.html',1,'orm::db']]],
  ['backendruntimelimits_7',['BackendRuntimeLimits',['../structorm_1_1db_1_1BackendRuntimeLimits.html',1,'orm::db']]],
  ['backends_8',['Backends',['../md_docs_2backends.html',1,'']]],
  ['backendvaluelimits_9',['BackendValueLimits',['../structorm_1_1db_1_1BackendValueLimits.html',1,'orm::db']]],
  ['begintransaction_10',['beginTransaction',['../classorm_1_1DatabaseCore.html#a97f7b62ddae43ba47fb43bce0d420cfa',1,'orm::DatabaseCore']]],
  ['behavior_11',['behavior',['../md_docs_2backend-portability.html#autotoc_md12',1,'Portable behavior'],['../md_docs_2partial-result-queries.html#autotoc_md75',1,'Query behavior']]],
  ['betweenexpression_12',['BetweenExpression',['../structorm_1_1query_1_1detail_1_1BetweenExpression.html',1,'orm::query::detail']]],
  ['binding_20and_20soci_13',['Binding and SOCI',['../md_docs_2backend-portability.html#autotoc_md14',1,'']]],
  ['bindinginfo_14',['BindingInfo',['../structorm_1_1db_1_1binding_1_1BindingInfo.html',1,'orm::db::binding']]],
  ['bindingpayload_15',['BindingPayload',['../structorm_1_1db_1_1binding_1_1BindingPayload.html',1,'orm::db::binding']]],
  ['bindingtraits_16',['BindingTraits',['../structorm_1_1reflection_1_1detail_1_1BindingTraits.html',1,'orm::reflection::detail']]],
  ['boundary_17',['SOCI boundary',['../md_docs_2backend-extension.html#autotoc_md4',1,'']]],
  ['boundvalue_18',['BoundValue',['../structorm_1_1db_1_1BoundValue.html',1,'orm::db']]],
  ['build_20and_20ci_20integration_19',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['build_20configuration_20',['Build configuration',['../md_docs_2backends.html#autotoc_md24',1,'']]],
  ['build_20configuration_20and_20macro_20policy_21',['Build configuration and macro policy',['../index.html#autotoc_md50',1,'']]],
  ['build_20select_22',['Build select',['../md_docs_2query.html#autotoc_md80',1,'']]],
  ['by_20collections_23',['Filtering by collections',['../md_docs_2relations.html#autotoc_md102',1,'']]]
];
