var searchData=
[
  ['database_0',['Database',['../classorm_1_1Database.html',1,'orm::Database&lt; SchemaType &gt;'],['../md_docs_2database.html',1,'Database']]],
  ['databasecore_1',['DatabaseCore',['../classorm_1_1DatabaseCore.html',1,'orm::DatabaseCore'],['../classorm_1_1DatabaseCore.html#a918187290120417d85097a787b05153f',1,'orm::DatabaseCore::DatabaseCore()'],['../classorm_1_1DatabaseCore.html#a454c22e6671a38b7a93ed091f4c5f79f',1,'orm::DatabaseCore::DatabaseCore(db::CommandGeneratorFactory factory)'],['../classorm_1_1Database.html#a918187290120417d85097a787b05153f',1,'orm::Database::DatabaseCore()'],['../classorm_1_1Database.html#a454c22e6671a38b7a93ed091f4c5f79f',1,'orm::Database::DatabaseCore(db::CommandGeneratorFactory factory)']]],
  ['databaseerror_2',['DatabaseError',['../classorm_1_1DatabaseError.html',1,'orm']]],
  ['defaultcreatetablecommand_3',['DefaultCreateTableCommand',['../classorm_1_1db_1_1commands_1_1DefaultCreateTableCommand.html',1,'orm::db::commands']]],
  ['defaultdeletecommand_4',['DefaultDeleteCommand',['../classorm_1_1db_1_1commands_1_1DefaultDeleteCommand.html',1,'orm::db::commands']]],
  ['defaultdroptablecommand_5',['DefaultDropTableCommand',['../classorm_1_1db_1_1commands_1_1DefaultDropTableCommand.html',1,'orm::db::commands']]],
  ['defaultinsertcommand_6',['DefaultInsertCommand',['../classorm_1_1db_1_1commands_1_1DefaultInsertCommand.html',1,'orm::db::commands']]],
  ['defaultjunctioncolumnstorage_7',['DefaultJunctionColumnStorage',['../structorm_1_1model_1_1detail_1_1DefaultJunctionColumnStorage.html',1,'orm::model::detail']]],
  ['defaultselectcommand_8',['DefaultSelectCommand',['../classorm_1_1db_1_1commands_1_1DefaultSelectCommand.html',1,'orm::db::commands']]],
  ['defaultupdatecommand_9',['DefaultUpdateCommand',['../classorm_1_1db_1_1commands_1_1DefaultUpdateCommand.html',1,'orm::db::commands']]],
  ['definition_20of_20done_10',['Definition of Done',['../md_docs_2backend-extension.html#autotoc_md9',1,'Backend Definition of Done'],['../md_docs_2backend-portability.html#autotoc_md18',1,'Definition of Done']]],
  ['delete_20relation_20tables_11',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['delete_20table_12',['Delete table',['../md_docs_2database.html#autotoc_md41',1,'']]],
  ['deletecommand_13',['DeleteCommand',['../classorm_1_1db_1_1commands_1_1DeleteCommand.html',1,'orm::db::commands']]],
  ['deleterelationtablesimpl_14',['deleteRelationTablesImpl',['../classorm_1_1DatabaseCore.html#ac07741bddeeb1fe565c9b602bb85fc95',1,'orm::DatabaseCore']]],
  ['deletetableimpl_15',['deleteTableImpl',['../classorm_1_1DatabaseCore.html#a2c03d81186257bee78003f51be24ff14',1,'orm::DatabaseCore']]],
  ['dependencies_16',['Partition dependencies',['../md_docs_2modules.html#autotoc_md64',1,'']]],
  ['dialect_17',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['dialect_20differences_18',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['differences_19',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['disablejoining_20',['disableJoining',['../classorm_1_1Query.html#ab7a1cc60776eeb29212199765e4eaaba',1,'orm::Query']]],
  ['disconnect_21',['disconnect',['../classorm_1_1DatabaseCore.html#a2c1f18188748bf3717d28444e4f46520',1,'orm::DatabaseCore']]],
  ['distinct_22',['Distinct',['../md_docs_2query.html#autotoc_md86',1,'']]],
  ['distinct_23',['distinct',['../classorm_1_1Query.html#a6b9e97270d5af0c1aebfcc6c408cf9e2',1,'orm::Query']]],
  ['done_24',['Done',['../md_docs_2backend-extension.html#autotoc_md9',1,'Backend Definition of Done'],['../md_docs_2backend-portability.html#autotoc_md18',1,'Definition of Done']]],
  ['droptablecommand_25',['DropTableCommand',['../classorm_1_1db_1_1commands_1_1DropTableCommand.html',1,'orm::db::commands']]],
  ['dto_20rules_26',['Result DTO rules',['../md_docs_2partial-result-queries.html#autotoc_md77',1,'']]]
];
