var searchData=
[
  ['c_0',['C',['../index.html',1,'ORM C++'],['../md_docs_2migration-macro-free.html#autotoc_md50',1,'Read the configuration in C++']]],
  ['capabilities_20and_20dialect_20differences_1',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_2',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['capabilities_20versus_20dialect_3',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_4',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['changes_5',['Compatibility changes',['../md_docs_2migration-macro-free.html#autotoc_md51',1,'']]],
  ['changing_20the_20release_6',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md84',1,'']]],
  ['checks_7',['Policy and checks',['../md_docs_2migration-macro-free.html#autotoc_md52',1,'']]],
  ['ci_20compiler_20matrix_8',['CI Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'']]],
  ['ci_20integration_9',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_10',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['ci_20status_11',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['clang_12',['Clang',['../md_docs_2ci-compiler-matrix.html#autotoc_md31',1,'']]],
  ['closed_20schema_13',['4. Define the closed schema',['../md_docs_2migration-static-schema.html#autotoc_md59',1,'']]],
  ['cmake_20installation_14',['Native CMake installation',['../md_docs_2packaging.html#autotoc_md86',1,'']]],
  ['cmake_20presets_15',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['collection_20mappings_16',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md58',1,'']]],
  ['collection_20predicates_17',['Collection predicates',['../md_docs_2query.html#autotoc_md97',1,'']]],
  ['collection_20relations_18',['Collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md78',1,'Collection relations']]],
  ['collection_20wrappers_19',['Collection wrappers',['../md_docs_2relations.html#autotoc_md109',1,'']]],
  ['collections_20',['collections',['../md_docs_2relations.html#autotoc_md116',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md95',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md115',1,'Loading collections']]],
  ['column_20names_21',['Column names',['../md_docs_2model.html#autotoc_md74',1,'']]],
  ['column_20names_22',['Junction column names',['../md_docs_2relations.html#autotoc_md112',1,'']]],
  ['column_20names_20and_20relations_23',['Column names and relations',['../md_docs_2query.html#autotoc_md98',1,'']]],
  ['common_20mistakes_24',['Common mistakes',['../md_docs_2relations.html#autotoc_md120',1,'']]],
  ['compatibility_20at_20a_20glance_25',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['compatibility_20changes_26',['Compatibility changes',['../md_docs_2migration-macro-free.html#autotoc_md51',1,'']]],
  ['compile_20time_20mappings_20and_20static_20schemas_27',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['compiler_20matrix_28',['Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['compiler_20versions_29',['Compiler Versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'Adding New Compiler Versions'],['../md_docs_2ci-compiler-matrix.html#autotoc_md29',1,'Tested Compiler Versions']]],
  ['conancenter_20after_20acceptance_30',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md82',1,'']]],
  ['concrete_20extension_20points_31',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_32',['configuration',['../md_docs_2migration-static-schema.html#autotoc_md57',1,'2. Replace runtime model configuration'],['../md_docs_2backends.html#autotoc_md24',1,'Build configuration']]],
  ['configuration_20in_20c_33',['Read the configuration in C++',['../md_docs_2migration-macro-free.html#autotoc_md50',1,'']]],
  ['configuration_20without_20macros_34',['Backend configuration without macros',['../md_docs_2migration-macro-free.html',1,'']]],
  ['conformance_20tests_35',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_36',['Connect',['../md_docs_2database.html#autotoc_md38',1,'']]],
  ['consistency_37',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md118',1,'']]],
  ['consistent_38',['Keep expression ownership consistent',['../md_docs_2migration-typed-queries.html#autotoc_md64',1,'']]],
  ['consume_20from_20conancenter_20after_20acceptance_39',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md82',1,'']]],
  ['consume_20from_20vcpkg_20after_20acceptance_40',['Consume from vcpkg after acceptance',['../md_docs_2packaging.html#autotoc_md81',1,'']]],
  ['contract_41',['Contract',['../md_docs_2partial-result-queries.html#autotoc_md88',1,'']]],
  ['contract_42',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['conversion_43',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md124',1,'']]],
  ['convert_20collection_20mappings_44',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md58',1,'']]],
  ['coverage_20policy_45',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['create_20a_20model_46',['Create a model',['../md_docs_2model.html#autotoc_md69',1,'']]],
  ['create_20and_20delete_20relation_20tables_47',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['create_20table_48',['Create table',['../md_docs_2database.html#autotoc_md40',1,'']]],
  ['current_20limitations_49',['Current limitations',['../md_docs_2model.html#autotoc_md79',1,'']]]
];
