var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_1',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_2',['Capabilities and errors',['../md_docs_2database.html#autotoc_md29',1,'']]],
  ['capabilities_20versus_20dialect_3',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_4',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['ci_20integration_5',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_6',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['closed_20schema_7',['4. Define the closed schema',['../md_docs_2migration-static-schema.html#autotoc_md44',1,'']]],
  ['collection_20mappings_8',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md43',1,'']]],
  ['collection_20predicates_9',['Collection predicates',['../md_docs_2query.html#autotoc_md69',1,'']]],
  ['collection_20relations_10',['Collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md57',1,'Collection relations']]],
  ['collection_20wrappers_11',['Collection wrappers',['../md_docs_2relations.html#autotoc_md81',1,'']]],
  ['collections_12',['collections',['../md_docs_2relations.html#autotoc_md88',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md67',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md87',1,'Loading collections']]],
  ['column_20names_13',['Column names',['../md_docs_2model.html#autotoc_md53',1,'']]],
  ['column_20names_14',['Junction column names',['../md_docs_2relations.html#autotoc_md84',1,'']]],
  ['column_20names_20and_20relations_15',['Column names and relations',['../md_docs_2query.html#autotoc_md70',1,'']]],
  ['common_20mistakes_16',['Common mistakes',['../md_docs_2relations.html#autotoc_md92',1,'']]],
  ['compatibility_20at_20a_20glance_17',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['compile_20time_20mappings_20and_20static_20schemas_18',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['concrete_20extension_20points_19',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_20',['configuration',['../md_docs_2migration-static-schema.html#autotoc_md42',1,'2. Replace runtime model configuration'],['../md_docs_2backends.html#autotoc_md24',1,'Build configuration']]],
  ['conformance_20tests_21',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_22',['Connect',['../md_docs_2database.html#autotoc_md28',1,'']]],
  ['consistency_23',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md90',1,'']]],
  ['contract_24',['Contract',['../md_docs_2partial-result-queries.html#autotoc_md60',1,'']]],
  ['contract_25',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['convert_20collection_20mappings_26',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md43',1,'']]],
  ['create_20a_20model_27',['Create a model',['../md_docs_2model.html#autotoc_md48',1,'']]],
  ['create_20and_20delete_20relation_20tables_28',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md32',1,'']]],
  ['create_20table_29',['Create table',['../md_docs_2database.html#autotoc_md30',1,'']]],
  ['current_20limitations_30',['Current limitations',['../md_docs_2model.html#autotoc_md58',1,'']]]
];
