var searchData=
[
  ['a_20glance_0',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['a_20model_1',['Create a model',['../md_docs_2model.html#autotoc_md65',1,'']]],
  ['acceptance_2',['acceptance',['../md_docs_2packaging.html#autotoc_md78',1,'Consume from ConanCenter after acceptance'],['../md_docs_2packaging.html#autotoc_md77',1,'Consume from vcpkg after acceptance']]],
  ['adding_20new_20compiler_20versions_3',['Adding New Compiler Versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'']]],
  ['after_20acceptance_4',['after acceptance',['../md_docs_2packaging.html#autotoc_md78',1,'Consume from ConanCenter after acceptance'],['../md_docs_2packaging.html#autotoc_md77',1,'Consume from vcpkg after acceptance']]],
  ['aggregate_20projection_20queries_5',['Aggregate projection queries',['../md_docs_2query.html#autotoc_md101',1,'']]],
  ['aggregate_20result_20queries_6',['Aggregate result queries',['../md_docs_2partial-result-queries.html#autotoc_md86',1,'']]],
  ['an_20existing_20schema_7',['Migrating an existing schema',['../md_docs_2relations.html#autotoc_md117',1,'']]],
  ['and_20ci_20integration_8',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['and_20consistency_9',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md114',1,'']]],
  ['and_20delete_20relation_20tables_10',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['and_20dialect_20differences_11',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['and_20errors_12',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['and_20explicit_20conversion_13',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md120',1,'']]],
  ['and_20having_14',['Full-model grouping and HAVING',['../md_docs_2query.html#autotoc_md100',1,'']]],
  ['and_20offset_15',['Limit and offset',['../md_docs_2query.html#autotoc_md97',1,'']]],
  ['and_20publishing_16',['Maintainer setup and publishing',['../md_docs_2packaging.html#autotoc_md79',1,'']]],
  ['and_20relations_17',['and relations',['../md_docs_2migration-static-schema.html#autotoc_md56',1,'5. Migrate query fields and relations'],['../md_docs_2query.html#autotoc_md94',1,'Column names and relations']]],
  ['and_20releases_18',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['and_20soci_19',['Binding and SOCI',['../md_docs_2backend-portability.html#autotoc_md14',1,'']]],
  ['and_20static_20schemas_20',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['and_20unlink_21',['Link and unlink',['../md_docs_2relations.html#autotoc_md110',1,'']]],
  ['and_20unlink_20relations_22',['Link and unlink relations',['../md_docs_2database.html#autotoc_md44',1,'']]],
  ['and_20unsupported_20mappings_23',['Validation and unsupported mappings',['../md_docs_2relations.html#autotoc_md115',1,'']]],
  ['and_20writes_24',['Projections and writes',['../md_docs_2static-queries.html#autotoc_md119',1,'']]],
  ['and_20writes_20explicit_25',['Make NULL and writes explicit',['../md_docs_2migration-typed-queries.html#autotoc_md62',1,'']]],
  ['at_20a_20glance_26',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['at_20the_20database_20boundary_27',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md63',1,'']]],
  ['auto_20increment_20primary_20key_28',['Auto-increment primary key',['../md_docs_2model.html#autotoc_md72',1,'']]]
];
