var searchData=
[
  ['range_0',['Use values that preserve their entire type range',['../md_docs_2migration-typed-queries.html#autotoc_md60',1,'']]],
  ['raw_20sql_1',['Raw SQL',['../md_docs_2backend-extension.html#autotoc_md5',1,'Raw SQL'],['../md_docs_2backend-portability.html#autotoc_md15',1,'Raw SQL']]],
  ['raw_20sql_20fragments_2',['Raw SQL fragments',['../md_docs_2query.html#autotoc_md97',1,'']]],
  ['raw_20sql_20portability_3',['Raw SQL portability',['../md_docs_2backends.html#autotoc_md26',1,'']]],
  ['reflectable_4',['1. Keep models reflectable',['../md_docs_2migration-static-schema.html#autotoc_md51',1,'']]],
  ['relation_20tables_5',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['relations_6',['relations',['../md_docs_2migration-static-schema.html#autotoc_md55',1,'5. Migrate query fields and relations'],['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md73',1,'Collection relations'],['../md_docs_2query.html#autotoc_md93',1,'Column names and relations'],['../md_docs_2database.html#autotoc_md44',1,'Link and unlink relations'],['../md_docs_2model.html#autotoc_md72',1,'One-to-one relations']]],
  ['release_7',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md79',1,'']]],
  ['releases_8',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['remove_20objects_9',['Remove objects',['../md_docs_2database.html#autotoc_md47',1,'']]],
  ['replace_200_201_20expressions_10',['Replace 0.1 expressions',['../md_docs_2migration-typed-queries.html#autotoc_md58',1,'']]],
  ['replace_20runtime_20model_20configuration_11',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md52',1,'']]],
  ['reporting_12',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['required_20backend_20responsibilities_13',['Required backend responsibilities',['../md_docs_2backend-extension.html#autotoc_md2',1,'']]],
  ['responsibilities_14',['Required backend responsibilities',['../md_docs_2backend-extension.html#autotoc_md2',1,'']]],
  ['result_20dto_20rules_15',['Result DTO rules',['../md_docs_2partial-result-queries.html#autotoc_md86',1,'']]],
  ['result_20queries_16',['result queries',['../md_docs_2partial-result-queries.html#autotoc_md85',1,'Aggregate result queries'],['../md_docs_2partial-result-queries.html',1,'Partial-result queries'],['../md_docs_2query.html#autotoc_md98',1,'Partial-result queries']]],
  ['retain_20runtime_20validation_20at_20the_20database_20boundary_17',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md62',1,'']]],
  ['retry_20without_20changing_20the_20release_18',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md79',1,'']]],
  ['rollout_19',['Suggested rollout',['../md_docs_2migration-static-schema.html#autotoc_md56',1,'']]],
  ['rules_20',['Result DTO rules',['../md_docs_2partial-result-queries.html#autotoc_md86',1,'']]],
  ['runtime_20model_20configuration_21',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md52',1,'']]],
  ['runtime_20validation_20at_20the_20database_20boundary_22',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md62',1,'']]]
];
