var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_1',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_2',['Capabilities and errors',['../md_docs_2database.html#autotoc_md39',1,'']]],
  ['capabilities_20versus_20dialect_3',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_4',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['changing_20the_20release_5',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md79',1,'']]],
  ['ci_20compiler_20matrix_6',['CI Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'']]],
  ['ci_20integration_7',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_8',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['ci_20status_9',['CI Status',['../md_docs_2ci-compiler-matrix.html#autotoc_md28',1,'']]],
  ['clang_10',['Clang',['../md_docs_2ci-compiler-matrix.html#autotoc_md31',1,'']]],
  ['closed_20schema_11',['4. Define the closed schema',['../md_docs_2migration-static-schema.html#autotoc_md54',1,'']]],
  ['cmake_20installation_12',['Native CMake installation',['../md_docs_2packaging.html#autotoc_md81',1,'']]],
  ['cmake_20presets_13',['CMake Presets',['../md_docs_2ci-compiler-matrix.html#autotoc_md35',1,'']]],
  ['collection_20mappings_14',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md53',1,'']]],
  ['collection_20predicates_15',['Collection predicates',['../md_docs_2query.html#autotoc_md92',1,'']]],
  ['collection_20relations_16',['Collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md73',1,'Collection relations']]],
  ['collection_20wrappers_17',['Collection wrappers',['../md_docs_2relations.html#autotoc_md104',1,'']]],
  ['collections_18',['collections',['../md_docs_2relations.html#autotoc_md111',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md90',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md110',1,'Loading collections']]],
  ['column_20names_19',['Column names',['../md_docs_2model.html#autotoc_md69',1,'']]],
  ['column_20names_20',['Junction column names',['../md_docs_2relations.html#autotoc_md107',1,'']]],
  ['column_20names_20and_20relations_21',['Column names and relations',['../md_docs_2query.html#autotoc_md93',1,'']]],
  ['common_20mistakes_22',['Common mistakes',['../md_docs_2relations.html#autotoc_md115',1,'']]],
  ['compatibility_20at_20a_20glance_23',['Compatibility at a glance',['../md_docs_2backends.html#autotoc_md21',1,'']]],
  ['compile_20time_20mappings_20and_20static_20schemas_24',['Migrating to compile-time mappings and static schemas',['../md_docs_2migration-static-schema.html',1,'']]],
  ['compiler_20matrix_25',['Compiler Matrix',['../md_docs_2ci-compiler-matrix.html',1,'CI Compiler Matrix'],['../md_docs_2ci-compiler-matrix.html#autotoc_md33',1,'PostgreSQL Compiler Matrix']]],
  ['compiler_20versions_26',['Compiler Versions',['../md_docs_2ci-compiler-matrix.html#autotoc_md36',1,'Adding New Compiler Versions'],['../md_docs_2ci-compiler-matrix.html#autotoc_md29',1,'Tested Compiler Versions']]],
  ['conancenter_20after_20acceptance_27',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md77',1,'']]],
  ['concrete_20extension_20points_28',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_29',['configuration',['../md_docs_2migration-static-schema.html#autotoc_md52',1,'2. Replace runtime model configuration'],['../md_docs_2backends.html#autotoc_md24',1,'Build configuration']]],
  ['conformance_20tests_30',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_31',['Connect',['../md_docs_2database.html#autotoc_md38',1,'']]],
  ['consistency_32',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md113',1,'']]],
  ['consistent_33',['Keep expression ownership consistent',['../md_docs_2migration-typed-queries.html#autotoc_md59',1,'']]],
  ['consume_20from_20conancenter_20after_20acceptance_34',['Consume from ConanCenter after acceptance',['../md_docs_2packaging.html#autotoc_md77',1,'']]],
  ['consume_20from_20vcpkg_20after_20acceptance_35',['Consume from vcpkg after acceptance',['../md_docs_2packaging.html#autotoc_md76',1,'']]],
  ['contract_36',['Contract',['../md_docs_2partial-result-queries.html#autotoc_md83',1,'']]],
  ['contract_37',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['convert_20collection_20mappings_38',['3. Convert collection mappings',['../md_docs_2migration-static-schema.html#autotoc_md53',1,'']]],
  ['coverage_20policy_39',['Coverage Policy',['../md_docs_2ci-compiler-matrix.html#autotoc_md34',1,'']]],
  ['create_20a_20model_40',['Create a model',['../md_docs_2model.html#autotoc_md64',1,'']]],
  ['create_20and_20delete_20relation_20tables_41',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['create_20table_42',['Create table',['../md_docs_2database.html#autotoc_md40',1,'']]],
  ['current_20limitations_43',['Current limitations',['../md_docs_2model.html#autotoc_md74',1,'']]]
];
