var searchData=
[
  ['c_0',['ORM C++',['../index.html',1,'']]],
  ['capabilities_20and_20dialect_20differences_1',['Capabilities and dialect differences',['../md_docs_2backend-portability.html#autotoc_md13',1,'']]],
  ['capabilities_20and_20errors_2',['Capabilities and errors',['../md_docs_2database.html#autotoc_md27',1,'']]],
  ['capabilities_20versus_20dialect_3',['Capabilities versus dialect',['../md_docs_2backend-extension.html#autotoc_md3',1,'']]],
  ['capability_20reporting_4',['Capability reporting',['../md_docs_2backends.html#autotoc_md23',1,'']]],
  ['ci_20integration_5',['Build and CI integration',['../md_docs_2backend-extension.html#autotoc_md8',1,'']]],
  ['ci_20matrix_6',['Minimum CI matrix',['../md_docs_2backend-portability.html#autotoc_md17',1,'']]],
  ['collection_20predicates_7',['Collection predicates',['../md_docs_2query.html#autotoc_md58',1,'']]],
  ['collection_20relations_8',['Collection relations',['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md46',1,'Collection relations']]],
  ['collection_20wrappers_9',['Collection wrappers',['../md_docs_2relations.html#autotoc_md70',1,'']]],
  ['collections_10',['collections',['../md_docs_2relations.html#autotoc_md77',1,'Filtering by collections'],['../md_docs_2query.html#autotoc_md56',1,'Loading collections'],['../md_docs_2relations.html#autotoc_md76',1,'Loading collections']]],
  ['column_20names_11',['Column names',['../md_docs_2model.html#autotoc_md42',1,'']]],
  ['column_20names_12',['Junction column names',['../md_docs_2relations.html#autotoc_md73',1,'']]],
  ['column_20names_20and_20relations_13',['Column names and relations',['../md_docs_2query.html#autotoc_md59',1,'']]],
  ['common_20mistakes_14',['Common mistakes',['../md_docs_2relations.html#autotoc_md81',1,'']]],
  ['concrete_20extension_20points_15',['Concrete extension points',['../md_docs_2backend-extension.html#autotoc_md1',1,'']]],
  ['configuration_16',['Build configuration',['../md_docs_2backends.html#autotoc_md22',1,'']]],
  ['conformance_20tests_17',['Conformance tests',['../md_docs_2backend-extension.html#autotoc_md7',1,'']]],
  ['connect_18',['Connect',['../md_docs_2database.html#autotoc_md26',1,'']]],
  ['consistency_19',['Transactions and consistency',['../md_docs_2relations.html#autotoc_md79',1,'']]],
  ['contract_20',['Contract',['../md_docs_2partial-result-queries.html#autotoc_md49',1,'']]],
  ['contract_21',['contract',['../md_docs_2backend-extension.html',1,'Backend extension contract'],['../md_docs_2backend-extension.html#autotoc_md6',1,'Error contract']]],
  ['create_20a_20model_22',['Create a model',['../md_docs_2model.html#autotoc_md38',1,'']]],
  ['create_20and_20delete_20relation_20tables_23',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md30',1,'']]],
  ['create_20table_24',['Create table',['../md_docs_2database.html#autotoc_md28',1,'']]],
  ['current_20limitations_25',['Current limitations',['../md_docs_2model.html#autotoc_md47',1,'Current limitations'],['../md_docs_2query.html#autotoc_md68',1,'Current limitations']]]
];
