var searchData=
[
  ['range_0',['Use values that preserve their entire type range',['../md_docs_2migration-typed-queries.html#autotoc_md65',1,'']]],
  ['raw_20sql_1',['Raw SQL',['../md_docs_2backend-extension.html#autotoc_md5',1,'Raw SQL'],['../md_docs_2backend-portability.html#autotoc_md15',1,'Raw SQL']]],
  ['raw_20sql_20fragments_2',['Raw SQL fragments',['../md_docs_2query.html#autotoc_md102',1,'']]],
  ['raw_20sql_20portability_3',['Raw SQL portability',['../md_docs_2backends.html#autotoc_md26',1,'']]],
  ['read_20the_20configuration_20in_20c_4',['Read the configuration in C++',['../md_docs_2migration-macro-free.html#autotoc_md50',1,'']]],
  ['reflectable_5',['1. Keep models reflectable',['../md_docs_2migration-static-schema.html#autotoc_md56',1,'']]],
  ['relation_20tables_6',['Create and delete relation tables',['../md_docs_2database.html#autotoc_md42',1,'']]],
  ['relations_7',['relations',['../md_docs_2migration-static-schema.html#autotoc_md60',1,'5. Migrate query fields and relations'],['../md_docs_2relations.html',1,'Collection relations'],['../md_docs_2model.html#autotoc_md78',1,'Collection relations'],['../md_docs_2query.html#autotoc_md98',1,'Column names and relations'],['../md_docs_2database.html#autotoc_md44',1,'Link and unlink relations'],['../md_docs_2model.html#autotoc_md77',1,'One-to-one relations']]],
  ['release_8',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md84',1,'']]],
  ['releases_9',['Package managers and releases',['../md_docs_2packaging.html',1,'']]],
  ['remove_20objects_10',['Remove objects',['../md_docs_2database.html#autotoc_md47',1,'']]],
  ['replace_200_201_20expressions_11',['Replace 0.1 expressions',['../md_docs_2migration-typed-queries.html#autotoc_md63',1,'']]],
  ['replace_20runtime_20model_20configuration_12',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md57',1,'']]],
  ['reporting_13',['Capability reporting',['../md_docs_2backends.html#autotoc_md25',1,'']]],
  ['required_20backend_20responsibilities_14',['Required backend responsibilities',['../md_docs_2backend-extension.html#autotoc_md2',1,'']]],
  ['responsibilities_15',['Required backend responsibilities',['../md_docs_2backend-extension.html#autotoc_md2',1,'']]],
  ['result_20dto_20rules_16',['Result DTO rules',['../md_docs_2partial-result-queries.html#autotoc_md91',1,'']]],
  ['result_20queries_17',['result queries',['../md_docs_2partial-result-queries.html#autotoc_md90',1,'Aggregate result queries'],['../md_docs_2partial-result-queries.html',1,'Partial-result queries'],['../md_docs_2query.html#autotoc_md103',1,'Partial-result queries']]],
  ['retain_20runtime_20validation_20at_20the_20database_20boundary_18',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md67',1,'']]],
  ['retry_20without_20changing_20the_20release_19',['Retry without changing the release',['../md_docs_2packaging.html#autotoc_md84',1,'']]],
  ['rollout_20',['Suggested rollout',['../md_docs_2migration-static-schema.html#autotoc_md61',1,'']]],
  ['rules_21',['Result DTO rules',['../md_docs_2partial-result-queries.html#autotoc_md91',1,'']]],
  ['runtime_20model_20configuration_22',['2. Replace runtime model configuration',['../md_docs_2migration-static-schema.html#autotoc_md57',1,'']]],
  ['runtime_20shapes_20and_20explicit_20conversion_23',['Runtime shapes and explicit conversion',['../md_docs_2static-queries.html#autotoc_md124',1,'']]],
  ['runtime_20validation_20at_20the_20database_20boundary_24',['Retain runtime validation at the database boundary',['../md_docs_2migration-typed-queries.html#autotoc_md67',1,'']]]
];
