#include "orm-cxx/database/postgresql/PostgresqlDialect.hpp"

#include <format>
#include <stdexcept>

#include "orm-cxx/database/SqlEmitter.hpp"
#include "orm-cxx/database/SqlNameValidation.hpp"
#include "PostgresqlTypeTranslator.hpp"

namespace
{

auto join(const std::vector<std::string>& values, std::string_view separator) -> std::string
{
    std::string result;

    for (const auto& value : values)
    {
        if (not result.empty())
        {
            result += separator;
        }

        result += value;
    }

    return result;
}
} // namespace

namespace orm::db::postgresql
{
auto PostgresqlDialect::quoteIdentifier(std::string_view identifier) const -> std::string
{
    return detail::quoteStandardIdentifier(identifier, CompiledSqlFlavor::PostgreSQL);
}

auto PostgresqlDialect::bindMarker(std::string_view logicalName) const -> std::string
{
    if (not detail::isPortableBindName(logicalName))
    {
        throw std::invalid_argument{"PostgreSQL bind parameter names may contain only ASCII letters, digits, and '_'"};
    }

    return ":" + std::string{logicalName};
}

auto PostgresqlDialect::toSqlType(model::ColumnType type) const -> std::string
{
    static const PostgresqlTypeTranslator translator;

    return translator.toSqlType(type);
}

auto PostgresqlDialect::renderCreateTablePrefix(std::string_view tableName, bool ifNotExists) const -> std::string
{
    return std::format("CREATE TABLE {}{} (", ifNotExists ? "IF NOT EXISTS " : "", quoteIdentifier(tableName));
}

auto PostgresqlDialect::renderDropTable(std::string_view tableName, bool ifExists) const -> std::string
{
    return std::format("DROP TABLE {}{};", ifExists ? "IF EXISTS " : "", quoteIdentifier(tableName));
}

auto PostgresqlDialect::renderAutoIncrementPrimaryKey(std::string_view columnName) const -> std::string
{
    return std::format("{} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", quoteIdentifier(columnName));
}

auto PostgresqlDialect::renderPagination(const PaginationSpec& pagination) const -> std::string
{
    detail::SqlQueryView query;
    query.hasLimit = pagination.limit.has_value();
    query.hasOffset = pagination.offset.has_value();
    query.literalLimit = pagination.limit.value_or(0);
    query.literalOffset = pagination.offset.value_or(0);
    return detail::StaticSqlPolicy<CompiledSqlFlavor::PostgreSQL>{}.pagination(query);
}

auto PostgresqlDialect::renderInsertIfAbsent(const InsertIfAbsentSpec& insert) const -> std::string
{
    if (insert.columns.empty())
    {
        throw std::invalid_argument{"Insert-if-absent requires at least one column"};
    }

    if (insert.columns.size() != insert.valueExpressions.size())
    {
        throw std::invalid_argument{"Insert-if-absent column and value counts must match"};
    }

    if (insert.conflictColumns.empty())
    {
        throw std::invalid_argument{"Insert-if-absent requires conflict columns"};
    }

    std::vector<std::string> columns;
    std::vector<std::string> conflictColumns;
    columns.reserve(insert.columns.size());
    conflictColumns.reserve(insert.conflictColumns.size());

    for (const auto& column : insert.columns)
    {
        columns.push_back(quoteIdentifier(column));
    }

    for (const auto& column : insert.conflictColumns)
    {
        conflictColumns.push_back(quoteIdentifier(column));
    }

    return std::format("INSERT INTO {} ({}) VALUES ({}) ON CONFLICT ({}) DO NOTHING;",
                       quoteIdentifier(insert.tableName), join(columns, ", "), join(insert.valueExpressions, ", "),
                       join(conflictColumns, ", "));
}

auto PostgresqlDialect::renderAggregateResult(std::string_view expression,
                                              bool preserveExactNumeric) const -> std::string
{
    return detail::StaticSqlPolicy<CompiledSqlFlavor::PostgreSQL>{}.renderAggregateResult(expression,
                                                                                          preserveExactNumeric);
}
} // namespace orm::db::postgresql
