#include "orm-cxx/database/postgresql/PostgresqlDialect.hpp"

#include <algorithm>
#include <format>
#include <stdexcept>

#include "PostgresqlTypeTranslator.hpp"

namespace
{
constexpr std::size_t maxPostgresqlIdentifierBytes = 63;

auto isPortableBindName(std::string_view name) -> bool
{
    return not name.empty() and std::ranges::all_of(name,
                                                    [](const char character)
                                                    {
                                                        return (character >= 'a' and character <= 'z') or
                                                               (character >= 'A' and character <= 'Z') or
                                                               (character >= '0' and character <= '9') or
                                                               character == '_';
                                                    });
}

auto join(const std::vector<std::string>& values, std::string_view separator) -> std::string
{
    std::string result;

    for (const auto& value : values)
    {
        if (not result.empty())
        {
            result += separator;
        }

        result += value;
    }

    return result;
}
} // namespace

namespace orm::db::postgresql
{
auto PostgresqlDialect::quoteIdentifier(std::string_view identifier) const -> std::string
{
    if (identifier.empty())
    {
        throw std::invalid_argument{"SQL identifier cannot be empty"};
    }

    if (identifier.find('\0') != std::string_view::npos)
    {
        throw std::invalid_argument{"PostgreSQL identifiers must not contain an embedded NUL byte"};
    }

    if (identifier.size() > maxPostgresqlIdentifierBytes)
    {
        throw std::invalid_argument{"PostgreSQL identifiers must not exceed 63 bytes"};
    }

    std::string quoted{"\""};

    for (const auto character : identifier)
    {
        if (character == '"')
        {
            quoted += "\"\"";
        }
        else
        {
            quoted += character;
        }
    }

    quoted += '"';

    return quoted;
}

auto PostgresqlDialect::bindMarker(std::string_view logicalName) const -> std::string
{
    if (not isPortableBindName(logicalName))
    {
        throw std::invalid_argument{"PostgreSQL bind parameter names may contain only ASCII letters, digits, and '_'"};
    }

    return ":" + std::string{logicalName};
}

auto PostgresqlDialect::toSqlType(model::ColumnType type) const -> std::string
{
    static const PostgresqlTypeTranslator translator;

    return translator.toSqlType(type);
}

auto PostgresqlDialect::renderCreateTablePrefix(std::string_view tableName, bool ifNotExists) const -> std::string
{
    return std::format("CREATE TABLE {}{} (", ifNotExists ? "IF NOT EXISTS " : "", quoteIdentifier(tableName));
}

auto PostgresqlDialect::renderDropTable(std::string_view tableName, bool ifExists) const -> std::string
{
    return std::format("DROP TABLE {}{};", ifExists ? "IF EXISTS " : "", quoteIdentifier(tableName));
}

auto PostgresqlDialect::renderAutoIncrementPrimaryKey(std::string_view columnName) const -> std::string
{
    return std::format("{} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", quoteIdentifier(columnName));
}

auto PostgresqlDialect::renderPagination(const PaginationSpec& pagination) const -> std::string
{
    if (pagination.limit.has_value())
    {
        if (pagination.offset.has_value())
        {
            return std::format(" LIMIT {} OFFSET {}", pagination.limit.value(), pagination.offset.value());
        }

        return std::format(" LIMIT {}", pagination.limit.value());
    }

    if (pagination.offset.has_value())
    {
        return std::format(" OFFSET {}", pagination.offset.value());
    }

    return {};
}

auto PostgresqlDialect::renderInsertIfAbsent(const InsertIfAbsentSpec& insert) const -> std::string
{
    if (insert.columns.empty())
    {
        throw std::invalid_argument{"Insert-if-absent requires at least one column"};
    }

    if (insert.columns.size() != insert.valueExpressions.size())
    {
        throw std::invalid_argument{"Insert-if-absent column and value counts must match"};
    }

    if (insert.conflictColumns.empty())
    {
        throw std::invalid_argument{"Insert-if-absent requires conflict columns"};
    }

    std::vector<std::string> columns;
    std::vector<std::string> conflictColumns;
    columns.reserve(insert.columns.size());
    conflictColumns.reserve(insert.conflictColumns.size());

    for (const auto& column : insert.columns)
    {
        columns.push_back(quoteIdentifier(column));
    }

    for (const auto& column : insert.conflictColumns)
    {
        conflictColumns.push_back(quoteIdentifier(column));
    }

    return std::format("INSERT INTO {} ({}) VALUES ({}) ON CONFLICT ({}) DO NOTHING;",
                       quoteIdentifier(insert.tableName), join(columns, ", "), join(insert.valueExpressions, ", "),
                       join(conflictColumns, ", "));
}

auto PostgresqlDialect::renderAggregateResult(std::string_view expression, bool preserveExactNumeric) const
    -> std::string
{
    if (preserveExactNumeric)
    {
        return std::format("CAST({} AS TEXT)", expression);
    }

    return std::string{expression};
}
} // namespace orm::db::postgresql
