#include "orm-cxx/database/postgresql/PostgresqlDialect.hpp"

#include <gtest/gtest.h>
#include <stdexcept>
#include <string>

#include "../defaults/DefaultSelectCommand.hpp"
#include "orm-cxx/query.hpp"
#include "tests/ModelsDefinitions.hpp"
#include "tests/utils/FakeDatabase.hpp"

namespace
{
const orm::db::postgresql::PostgresqlDialect dialect;
}

TEST(PostgresqlDialectTest, quotesIdentifiersAndBindMarkers)
{
    EXPECT_EQ(dialect.quoteIdentifier("order"), "\"order\"");
    EXPECT_EQ(dialect.quoteIdentifier("odd\"name"), "\"odd\"\"name\"");
    EXPECT_EQ(dialect.bindMarker("value"), ":value");
    EXPECT_THROW((void)dialect.quoteIdentifier(""), std::invalid_argument);
    EXPECT_THROW((void)dialect.quoteIdentifier(std::string{"safe"} + '\0' + "suffix"), std::invalid_argument);
    EXPECT_NO_THROW((void)dialect.quoteIdentifier(std::string(63, 'a')));
    EXPECT_THROW((void)dialect.quoteIdentifier(std::string(64, 'a')), std::invalid_argument);
    EXPECT_THROW((void)dialect.bindMarker(""), std::invalid_argument);
    EXPECT_THROW((void)dialect.bindMarker(":value"), std::invalid_argument);
    EXPECT_THROW((void)dialect.bindMarker("odd-name"), std::invalid_argument);
    EXPECT_THROW((void)dialect.bindMarker("odd name"), std::invalid_argument);
}

TEST(PostgresqlDialectTest, rendersPostgresqlDdlPrimitives)
{
    EXPECT_EQ(dialect.toSqlType(orm::model::ColumnType::Int), "INTEGER");
    EXPECT_EQ(dialect.toSqlType(orm::model::ColumnType::String), "TEXT");
    EXPECT_EQ(dialect.renderCreateTablePrefix("order", true), "CREATE TABLE IF NOT EXISTS \"order\" (");
    EXPECT_EQ(dialect.renderCreateTablePrefix("order", false), "CREATE TABLE \"order\" (");
    EXPECT_EQ(dialect.renderDropTable("order", true), "DROP TABLE IF EXISTS \"order\";");
    EXPECT_EQ(dialect.renderDropTable("order", false), "DROP TABLE \"order\";");
    EXPECT_EQ(dialect.renderAutoIncrementPrimaryKey("id"),
              "\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    EXPECT_THROW((void)dialect.toSqlType(orm::model::ColumnType::Uuid), std::runtime_error);
}

TEST(PostgresqlDialectTest, rendersEveryPaginationCombination)
{
    EXPECT_EQ(dialect.renderPagination({}), "");
    EXPECT_EQ(dialect.renderPagination({.limit = 10}), " LIMIT 10");
    EXPECT_EQ(dialect.renderPagination({.offset = 5}), " OFFSET 5");
    EXPECT_EQ(dialect.renderPagination({.limit = 10, .offset = 5}), " LIMIT 10 OFFSET 5");
}

TEST(PostgresqlDialectTest, rendersNativeAtomicInsertIfAbsent)
{
    const orm::db::InsertIfAbsentSpec insert{
        .tableName = "user_roles",
        .columns = {"user_id", "role_id"},
        .valueExpressions = {":user", ":role"},
        .conflictColumns = {"user_id", "role_id"},
    };

    EXPECT_EQ(dialect.renderInsertIfAbsent(insert),
              "INSERT INTO \"user_roles\" (\"user_id\", \"role_id\") VALUES (:user, :role) ON CONFLICT "
              "(\"user_id\", \"role_id\") DO NOTHING;");
}

TEST(PostgresqlDialectTest, preservesExactNumericAggregateProjectionResultsAsText)
{
    EXPECT_EQ(dialect.renderAggregateResult("SUM(\"all_ints\".\"field7\")", true),
              "CAST(SUM(\"all_ints\".\"field7\") AS TEXT)");
    EXPECT_EQ(dialect.renderAggregateResult("AVG(\"all_ints\".\"field7\")", true),
              "CAST(AVG(\"all_ints\".\"field7\") AS TEXT)");
    EXPECT_EQ(dialect.renderAggregateResult("COUNT(*)", false), "COUNT(*)");
}

TEST(PostgresqlDialectTest, rejectsIncompleteInsertIfAbsentSpecifications)
{
    EXPECT_THROW((void)dialect.renderInsertIfAbsent({}), std::invalid_argument);
    EXPECT_THROW(
        (void)dialect.renderInsertIfAbsent(
            {.tableName = "links", .columns = {"owner_id"}, .valueExpressions = {}, .conflictColumns = {"owner_id"}}),
        std::invalid_argument);
    EXPECT_THROW(
        (void)dialect.renderInsertIfAbsent(
            {.tableName = "links", .columns = {"owner_id"}, .valueExpressions = {":owner"}, .conflictColumns = {}}),
        std::invalid_argument);
}

TEST(PostgresqlDialectTest, rejectsRawParameterNamesThatCannotBeRenderedAsPostgresqlBindMarkers)
{
    orm::db::commands::DefaultSelectCommand command{dialect};
    orm::Query<models::ModelWithOneField> query;
    query.where(orm::query::raw("field1 = :bad-name", orm::query::param("bad-name", 1)));

    EXPECT_THROW((void)command.select(orm::Database::getQueryData(query)), std::invalid_argument);
}
