"""Generate the structured-binding dispatch used by aggregate reflection.

The generated header is intentionally checked in so consumers only need a
C++20 compiler; Python is not part of the library's build.
"""

from pathlib import Path
import shutil
import subprocess
import textwrap


MAX_FIELDS = 128
ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "include" / "orm-cxx" / "reflection" / "detail" / "GeneratedBindings.hpp"
TEST_OUTPUT = ROOT / "tests" / "reflection" / "GeneratedFieldLimitModels.hpp"


def wrapped(items: list[str], indent: str) -> str:
    return textwrap.fill(
        ", ".join(items),
        width=116,
        initial_indent=indent,
        subsequent_indent=indent,
    ).lstrip()


def binding(number: int) -> str:
    if number == 0:
        return """template <typename T>
constexpr auto bindingTraitsImpl(T&, std::integral_constant<std::size_t, 0>) noexcept
{
    return BindingTraits<std::tuple<>, true>{};
}

template <typename T>
constexpr auto tieFieldsImpl(T&, std::integral_constant<std::size_t, 0>) noexcept
{
    return std::tuple{};
}
"""

    names = [f"field{index}" for index in range(number)]
    declarations = wrapped(names, "    ")
    tied = wrapped(names, "        ")
    field_types = wrapped([f"decltype({name})" for name in names], "        ")
    address_requirements = "\n".join(f"        std::addressof({name});" for name in names)
    return f"""template <typename T>
constexpr auto bindingTraitsImpl(T& value, std::integral_constant<std::size_t, {number}>) noexcept
{{
    auto& [{declarations}] = value;
    constexpr auto fieldsAreAddressable = requires {{
{address_requirements}
    }};
    return BindingTraits<std::tuple<{field_types}>, fieldsAreAddressable>{{}};
}}

template <typename T>
constexpr auto tieFieldsImpl(T& value, std::integral_constant<std::size_t, {number}>) noexcept
{{
    auto& [{declarations}] = value;
    // std::tie intentionally rejects bit-fields: C++ cannot form references to them.
    return std::tie({tied});
}}
"""


header = """// Generated by tools/generate_reflection_bindings.py. Do not edit by hand.
//
// The aggregate arity and structured-binding approach is adapted from
// reflect-cpp (https://github.com/getml/reflect-cpp), used under the MIT
// License. See THIRD_PARTY_NOTICES.md.

#pragma once

#include <cstddef>
#include <memory>
#include <tuple>
#include <type_traits>

namespace orm::reflection::detail
{
template <typename>
inline constexpr bool alwaysFalse = false;

template <typename TupleType, bool FieldsAreAddressable>
struct BindingTraits
{
    using Tuple = TupleType;
    inline static constexpr bool fieldsAreAddressable = FieldsAreAddressable;
};

"""

footer = """
} // namespace orm::reflection::detail
"""

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(header + "\n".join(binding(number) for number in range(MAX_FIELDS + 1)) + footer, encoding="utf-8")


def test_model(name: str, field_count: int) -> str:
    fields = "\n".join(f"    int field{index};" for index in range(field_count))
    return f"""struct {name}
{{
{fields}
}};
"""


test_header = """// Generated by tools/generate_reflection_bindings.py. Do not edit by hand.
// These boundary aggregates verify the checked-in 128-field reflection limit.

#pragma once

namespace reflection_limit_models
{
""" + test_model("MaxFields", MAX_FIELDS) + "\n" + test_model("TooManyFields", MAX_FIELDS + 1) + """
} // namespace reflection_limit_models
"""
TEST_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
TEST_OUTPUT.write_text(test_header, encoding="utf-8")

formatter = shutil.which("clang-format-18") or shutil.which("clang-format")
if formatter is None:
    raise RuntimeError("clang-format 18 is required to format the generated header")
formatter_version = subprocess.run(
    [formatter, "--version"], check=True, capture_output=True, text=True
).stdout
if "version 18." not in formatter_version:
    raise RuntimeError(f"clang-format 18 is required; found: {formatter_version.strip()}")
subprocess.run([formatter, "-i", str(OUTPUT), str(TEST_OUTPUT)], check=True)
