"""Generate the structured-binding dispatch used by aggregate reflection.

The generated module partitions are checked in so consumers only need a
C++20 compiler; Python is not part of the library's build.
"""

from pathlib import Path
import argparse
import shutil
import subprocess
import textwrap


MAX_FIELDS = 128
MAX_ARITIES_PER_PARTITION = 8
MAX_PARTITION_LINES = 900
ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIRECTORY = ROOT / "modules" / "reflection" / "generated"
FACADE_OUTPUT = OUTPUT_DIRECTORY.parent / "generated.cppm"
TEST_OUTPUT = ROOT / "tests" / "reflection" / "GeneratedFieldLimitModels.hpp"

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument(
    "--test-models-only",
    action="store_true",
    help="regenerate test models without rewriting library module partitions",
)
args = parser.parse_args()


def wrapped(items: list[str], indent: str) -> str:
    return textwrap.fill(
        ", ".join(items),
        width=116,
        initial_indent=indent,
        subsequent_indent=indent,
    ).lstrip()


def binding(number: int) -> str:
    if number == 0:
        return """template <typename T>
constexpr auto bindingTraitsImpl(T&, std::integral_constant<std::size_t, 0>) noexcept
{
    return BindingTraits<std::tuple<>, true>{};
}

template <typename T>
constexpr auto tieFieldsImpl(T&, std::integral_constant<std::size_t, 0>) noexcept
{
    return std::tuple{};
}
"""

    names = [f"field{index}" for index in range(number)]
    declarations = wrapped(names, "    ")
    tied = wrapped(names, "        ")
    field_types = wrapped([f"decltype({name})" for name in names], "        ")
    address_requirements = "\n".join(f"        std::addressof({name});" for name in names)
    return f"""template <typename T>
constexpr auto bindingTraitsImpl(T& value, std::integral_constant<std::size_t, {number}>) noexcept
{{
    auto& [{declarations}] = value;
    constexpr auto fieldsAreAddressable = requires {{
{address_requirements}
    }};
    return BindingTraits<std::tuple<{field_types}>, fieldsAreAddressable>{{}};
}}

template <typename T>
constexpr auto tieFieldsImpl(T& value, std::integral_constant<std::size_t, {number}>) noexcept
{{
    auto& [{declarations}] = value;
    // std::tie intentionally rejects bit-fields: C++ cannot form references to them.
    return std::tie({tied});
}}
"""


notice = """// Generated by tools/generate_reflection_bindings.py. Do not edit by hand.
//
// The aggregate arity and structured-binding approach is adapted from
// reflect-cpp (https://github.com/getml/reflect-cpp), used under the MIT
// License. See THIRD_PARTY_NOTICES.md.
"""

header = notice + """

module;

#include <cstddef>
#include <memory>
#include <tuple>
#include <type_traits>

export module orm.reflection:generated_arity_{first}_{last};

import :binding_traits;

namespace orm::reflection::detail
{
"""

footer = """
} // namespace orm::reflection::detail
"""

def partition(first: int, last: int) -> str:
    partition_header = header.replace("{first}", str(first)).replace("{last}", str(last))
    return partition_header + "\n".join(binding(number) for number in range(first, last + 1)) + footer


def partition_ranges() -> list[tuple[int, int]]:
    ranges = []
    first = 0
    while first < MAX_FIELDS:
        last = min(first + MAX_ARITIES_PER_PARTITION - 1, MAX_FIELDS - 1)
        while len(partition(first, last).splitlines()) > MAX_PARTITION_LINES and last > first:
            last -= 1
        ranges.append((first, last))
        first = last + 1
    # Keep the maximum supported arity separate as a stable packaging sentinel.
    ranges.append((MAX_FIELDS, MAX_FIELDS))
    return ranges


generated_outputs = []
if not args.test_models_only:
    OUTPUT_DIRECTORY.mkdir(parents=True, exist_ok=True)
    imports = ["export import :binding_traits;"]
    for first, last in partition_ranges():
        output = OUTPUT_DIRECTORY / f"arity_{first}_{last}.cppm"
        output.write_text(partition(first, last), encoding="utf-8", newline="\n")
        generated_outputs.append(output)
        imports.append(f"export import :generated_arity_{first}_{last};")
    for obsolete in OUTPUT_DIRECTORY.glob("arity_*_*.cppm"):
        if obsolete not in generated_outputs:
            obsolete.unlink()
    facade = notice + "\nexport module orm.reflection:generated;\n\n" + "\n".join(imports) + "\n"
    FACADE_OUTPUT.write_text(facade, encoding="utf-8", newline="\n")
    generated_outputs.append(FACADE_OUTPUT)


def test_model(name: str, field_count: int) -> str:
    fields = "\n".join(f"    int field{index};" for index in range(field_count))
    return f"""struct {name}
{{
{fields}
}};
"""


def runtime_test_model(field_count: int) -> str:
    fields = "\n".join(f"    int field{index} = {index};" for index in range(field_count))
    addresses = wrapped([f"&field{index}" for index in range(field_count)], "        ") if field_count else ""
    return f"""template <>
struct RuntimeFields<{field_count}>
{{
{fields}
    [[nodiscard]] auto addresses() noexcept -> std::array<int*, {field_count}>
    {{
        return {{{addresses}}};
    }}
}};
"""


test_header = """// Generated by tools/generate_reflection_bindings.py. Do not edit by hand.
// Boundary and runtime aggregates verify every generated binding from 0 to 128 fields.

#pragma once

#include <array>
#include <cstddef>

namespace reflection_limit_models
{
""" + test_model("MaxFields", MAX_FIELDS) + "\n" + test_model("TooManyFields", MAX_FIELDS + 1) + """

template <std::size_t Count>
struct RuntimeFields;

""" + "\n".join(runtime_test_model(number) for number in range(MAX_FIELDS + 1)) + """
} // namespace reflection_limit_models
"""
TEST_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
TEST_OUTPUT.write_text(test_header, encoding="utf-8", newline="\n")

formatter = shutil.which("clang-format-18") or shutil.which("clang-format")
if formatter is None:
    raise RuntimeError("clang-format is required to format the generated files")
formatter_version = subprocess.run(
    [formatter, "--version"], check=True, capture_output=True, text=True
).stdout
if not args.test_models_only and "version 18." not in formatter_version:
    raise RuntimeError(f"clang-format 18 is required; found: {formatter_version.strip()}")
files_to_format = [str(output) for output in [*generated_outputs, TEST_OUTPUT]]
subprocess.run([formatter, "-i", *files_to_format], check=True)
