// Generated by tools/generate_reflection_bindings.py. Do not edit by hand.
//
// The aggregate arity and structured-binding approach is adapted from
// reflect-cpp (https://github.com/getml/reflect-cpp), used under the MIT
// License. See THIRD_PARTY_NOTICES.md.

export module orm.reflection:generated;

export import :binding_traits;
export import :generated_arity_0_7;
export import :generated_arity_8_15;
export import :generated_arity_16_23;
export import :generated_arity_24_31;
export import :generated_arity_32_39;
export import :generated_arity_40_47;
export import :generated_arity_48_55;
export import :generated_arity_56_63;
export import :generated_arity_64_70;
export import :generated_arity_71_77;
export import :generated_arity_78_83;
export import :generated_arity_84_89;
export import :generated_arity_90_94;
export import :generated_arity_95_99;
export import :generated_arity_100_104;
export import :generated_arity_105_109;
export import :generated_arity_110_113;
export import :generated_arity_114_117;
export import :generated_arity_118_121;
export import :generated_arity_122_125;
export import :generated_arity_126_127;
export import :generated_arity_128_128;
