name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Install documentation tools
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes doxygen graphviz

      - name: Install doxygen css plugin
        run: git clone https://github.com/jothepro/doxygen-awesome-css.git && cd doxygen-awesome-css && sudo make install

      - name: Generate docs
        run: doxygen Doxyfile

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
