name: msvc

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: ${{ github.workspace }}/externals/reflect-cpp/vcpkg/bootstrap-vcpkg.bat \
          && ${{ github.workspace }}/externals/reflect-cpp/vcpkg/vcpkg.exe install

      - run: cmake -E make_directory build

      - working-directory: build/
        run: cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/externals/reflect-cpp/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - working-directory: build/
        run: cmake --build .

      - working-directory: build/
        run: ctest -C Debug --output-on-failure
