name: msvc

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: ${{ github.workspace }}/externals/reflect-cpp/vcpkg/bootstrap-vcpkg.bat

      - run: ${{ github.workspace }}/externals/reflect-cpp/vcpkg/vcpkg.exe install

      - run: cmake -E make_directory build

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - uses: seanmiddleditch/gha-setup-ninja@master

      - working-directory: build/
        run: cmake .. -GNinja -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/externals/reflect-cpp/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl

      - working-directory: build/
        run: cmake --build .

      - working-directory: build/
        run: ctest -C Debug --output-on-failure
